/********************************************************************************
 *
 * This file is part of the Geneva library collection. The following license
 * applies to this file:
 *
 * ------------------------------------------------------------------------------
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ------------------------------------------------------------------------------
 *
 * Note that other files in the Geneva library collection may use a different
 * license. Please see the licensing information in each file.
 *
 ********************************************************************************
 *
 * See the NOTICE file in the top-level directory of the Geneva library
 * collection for a list of contributors and copyright information.
 *
 ********************************************************************************/

#pragma once

// Global checks, defines and includes needed for all of Geneva
#include "common/GGlobalDefines.hpp"

// Standard header files go here
#include <algorithm> // for std::sort
#include <cmath>
#include <cstdlib>
#include <iostream>
#include <list>
#include <sstream>
#include <tuple>
#include <vector>

// Boost header files go here

// Geneva header files go here
#include "common/GCommonMathHelperFunctionsT.hpp"
#include "common/GExceptions.hpp"
#include "common/GParserBuilder.hpp"
#include "common/GSingletonT.hpp"
#include "geneva/GOptimizationEnums.hpp"
#include "geneva/ind/GGenome.hpp"
#include "geneva/ind/GGenomeT.hpp"
#include "geneva/ind/GGenomeBuilder.hpp"

namespace Gem::Geneva::Individuals {

/******************************************************************************/
/**
 * This individual tests different access methods for the values of the flat genome
 * held inside of the individual.
 */
class GTestIndividual3 // NOLINT(cppcoreguidelines-special-member-functions)
  : public gen::GGenomeT<GTestIndividual3> {
    ///////////////////////////////////////////////////////////////////////
    // serialize() / load_() / compare_() / clone_() / name_() are generated by the
    // Gem::Common::GBoilerplateT base (via GGenomeT): this is a genome-only (stateless) leaf.
    // Boost still default-constructs the concrete type on load, so it keeps this friendship.
    friend class boost::serialization::access;
    ///////////////////////////////////////////////////////////////////////

public:
    /** @brief Opt into GGenomeT's generated empty member list (genome-only leaf, no own state). */
    using gemfony_flat_individual = void;
    /** @brief The class name, consumed by the GBoilerplateT-generated name_() and compare token. */
    static constexpr std::string_view class_name = "GTestIndividual3";

    /** @brief The default constructor */
    GTestIndividual3();
    /**
     * @brief The copy constructor
     * @param cp Another GTestIndividual3 object whose data is copied into this one
     */
    GTestIndividual3(const GTestIndividual3 &cp);

    /** @brief The destructor */
    ~GTestIndividual3() override;

    /**
     * @brief Get all data members of this class as a plain array
     * @return A shared pointer to a freshly allocated float array (with array deleter) holding all of this
     *  individual's double parameters, narrowed to float in flat streamline order
     */
    std::shared_ptr<float[]> getPlainData() const;

protected:
    /**
     * @brief The evaluation hook: computes this individual's fitness.
     * @return The fitness as a one-element vector (single criterion)
     */
    std::vector<double> evaluate() final;

    /**
     * @brief Applies modifications to this object.
     * @return A boolean indicating whether a modification was actually carried out
     */
    bool modify_GUnitTests_() override;
    /** @brief Performs self tests that are expected to succeed. */
    void specificTestsNoFailureExpected_GUnitTests_() override;
    /** @brief Performs self tests that are expected to fail. */
    void specificTestsFailuresExpected_GUnitTests_() override;

};

/******************************************************************************/

} /* namespace Gem::Geneva::Individuals */

BOOST_CLASS_EXPORT_KEY(Gem::Geneva::Individuals::GTestIndividual3) // NOLINT
