/********************************************************************************
 *
 * This file is part of the Geneva library collection. The following license
 * applies to this file:
 *
 * ------------------------------------------------------------------------------
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ------------------------------------------------------------------------------
 *
 * Note that other files in the Geneva library collection may use a different
 * license. Please see the licensing information in each file.
 *
 ********************************************************************************
 *
 * See the NOTICE file in the top-level directory of the Geneva library
 * collection for a list of contributors and copyright information.
 *
 ********************************************************************************/

#pragma once

// Global checks, defines and includes needed for all of Geneva
#include "common/GGlobalDefines.hpp"

// Standard header files go here
#include <algorithm> // for std::sort
#include <cmath>
#include <cstdlib>
#include <iostream>
#include <list>
#include <sstream>
#include <vector>

// Boost header files go here

// Geneva header files go here
#include "common/GCommonEnums.hpp"
#include "common/GExceptions.hpp"
#include "geneva/GOptimizationEnums.hpp"
#include "geneva/genome/GGenome.hpp"
#include "geneva/genome/GGenomeT.hpp"
#include "geneva/genome/GGenomeBuilder.hpp"
#include "geneva/oa/GSwarmAlgorithm_PersonalityTraits.hpp"

namespace Gem::Geneva::OptimizationAlgorithms {
class GAdaptionConfigBase;
} // namespace Gem::Geneva::OptimizationAlgorithms

namespace Gem::Geneva::Individuals {

/**
 * The types of objects to be tested in this class
 */
enum class PERFOBJECTTYPE : Gem::Common::ENUMBASETYPE {
    PERFGDOUBLEOBJECT = 0,
    PERFGCONSTRDOUBLEOBJECT = 1,
    PERFGCONSTRAINEDDOUBLEOBJECTCOLLECTION = 2,
    PERFGDOUBLECOLLECTION = 3,
    PERFGCONSTRAINEDDOUBLECOLLECTION = 4
};

// Numeric streaming opt-in for PERFOBJECTTYPE; must precede its first streaming
// use (see numeric_enum_io_v in GCommonEnums.hpp).
} /* namespace Gem::Geneva::Individuals */
namespace Gem::Common {
template <> inline constexpr bool numeric_enum_io_v<Gem::Geneva::Individuals::PERFOBJECTTYPE> = true;
} /* namespace Gem::Common */
namespace Gem::Geneva::Individuals {

const PERFOBJECTTYPE POTMIN = PERFOBJECTTYPE::PERFGDOUBLEOBJECT;
const PERFOBJECTTYPE POTMAX = PERFOBJECTTYPE::PERFGCONSTRAINEDDOUBLEOBJECTCOLLECTION;
constexpr std::size_t NPERFOBJECTTYPES = 5;

/******************************************************************************/
// PERFOBJECTTYPE streams as its underlying numeric value through the shared
// machinery in GCommonEnums.hpp (marker specialization at the end of this
// header). Re-export the operators so ADL finds them in this namespace.
using Gem::Common::operator<<;
using Gem::Common::operator>>;

/******************************************************************************/
/**
 * This individual serves as the basis for unit tests of the individual hierarchy. At the time
 * of writing, it was included in order to be able to set the individual's personality without
 * weakening data protection.
 */
class GTestIndividual2
  : public gen::GGenomeT<GTestIndividual2> { // NOLINT(cppcoreguidelines-special-member-functions)
    ///////////////////////////////////////////////////////////////////////
    // serialize() / load_() / compare_() / clone_() / name_() are generated by the
    // Gem::Common::GReflectiveInterfaceT base (via GGenomeT): this is a genome-only (stateless) leaf.
    // Boost still default-constructs the concrete type on load, so it keeps this friendship; the
    // GArchive registry factory reconstructs it through the same-purpose GReflectiveInterfaceAccess
    // shim, which therefore needs equal reach to the private default constructor.
    friend class boost::serialization::access;
    friend struct Gem::Common::GReflectiveInterfaceAccess;
    ///////////////////////////////////////////////////////////////////////

public:
    /** @brief Opt into GGenomeT's generated empty member list (genome-only leaf, no own state). */
    using gemfony_flat_individual = void;
    /** @brief The class name, consumed by the GReflectiveInterfaceT-generated name_() and compare token. */
    static constexpr std::string_view class_name = "GTestIndividual2";
    /**
     * @brief Initialising constructor: builds a flat genome holding the requested number of double
     *  parameters of the requested representation type
     * @param n_objects The number of double parameters (or collection entries) to add to the genome
     * @param otype The representation type of the double parameters to be created (see PERFOBJECTTYPE)
     */
    GTestIndividual2(const std::size_t &n_objects, const PERFOBJECTTYPE &otype);
    /**
     * @brief The copy constructor
     * @param cp Another GTestIndividual2 object whose data is copied into this one
     */
    GTestIndividual2(const GTestIndividual2 &cp);

    /** @brief The standard destructor */
    ~GTestIndividual2() override;

    /**
     * @brief The OA-owned Gauss adaption config authoring every double group of this genome (used by the
     *  self-driven StandaloneAdapter benchmark / manual-test sites).
     * @return A shared pointer to the Gauss adaption config describing every double group of this genome
     */
    std::shared_ptr<OptimizationAlgorithms::GAdaptionConfigBase> getAdaptionConfig() const;

protected:
    /**
     * @brief The evaluation hook: computes this individual's fitness.
     * @return The fitness as a one-element vector (single criterion)
     */
    std::vector<double> evaluate() final;

    /**
     * @brief Applies modifications to this object.
     * @return A boolean indicating whether a modification was actually carried out
     */
    bool modify_GUnitTests_() override;
    /** @brief Performs self tests that are expected to succeed. */
    void specificTestsNoFailureExpected_GUnitTests_() override;
    /** @brief Performs self tests that are expected to fail. */
    void specificTestsFailuresExpected_GUnitTests_() override;

private:
    /** @brief The default constructor -- protected, as it is only needed for (de-)serialization purposes */
    GTestIndividual2();
};

/******************************************************************************/

} /* namespace Gem::Geneva::Individuals */

BOOST_CLASS_EXPORT_KEY(Gem::Geneva::Individuals::GTestIndividual2) // NOLINT
