/*
 * This file is part of the Geneva library collection.
 *
 * See the NOTICE file in the top-level directory of the Geneva library
 * collection for a list of contributors and copyright information.
 *
 * The following license applies to the code IN THIS FILE:
 *
 * ***************************************************************************
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * ***************************************************************************
 *
 * NOTE THAT THE BOOST-LICENSE DOES NOT APPLY TO ANY OTHER FILES OF THE
 * GENEVA LIBRARY, UNLESS THIS IS EXPLICITLY STATED IN THE CORRESPONDING FILE!
 */

#include "common/GLogger.hpp"
#include "common/GCommonEnums.hpp"
#include "common/GExceptions.hpp"
#include <filesystem>
#include <format>
#include <fstream>
#include <ios>
#include <iostream>
#include <ostream>
#include <sstream>
#include <string>
#include <string_view>
#include <utility>

namespace Gem::Common {

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * @brief Logs a message to the console.
 *
 * @param msg The log message to be written to the console
 */
void GConsoleLogger::log(std::string const &msg) const {
    // std::clog is fully buffered; flush so console diagnostics are not lost
    // if the process exits abnormally (signal / abort / _exit).
    std::clog << msg << std::flush;
}

/******************************************************************************/
/**
 * @brief Logs a message to the console, adding information about the source
 *
 * @param msg The log message to be written to the console
 * @param extension An identifier of the logging source, emitted as a textual prefix
 */
void GConsoleLogger::logWithSource(std::string const &msg, std::string const &extension) const {
    this->log(std::string("Message from source \"") + extension + "\":\n" + msg);
}

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/*******************************************************************************/
/**
 * @brief This constructor accepts a path to a log-file name as argument
 *
 * @param p The filesystem path of the log file to write to
 */
GFileLogger::GFileLogger(std::filesystem::path const &p)
  : fname_(p.string()) { /* nothing */
}

/******************************************************************************/
/**
 * @brief Logs a message to a file in append mode
 *
 * This function logs a message to a file, whose name it takes from the private
 * variable fname_. The file is reopened in append mode for every log message. On
 * a failure to open the file, the message is written to std::cerr instead.
 *
 * @param msg The log message to be appended to the file
 */
void GFileLogger::log(std::string const &msg) const {
    std::ofstream ofstr(
        std::filesystem::path(fname_),
        std::ios_base::app
    ); // NOLINT(cppcoreguidelines-init-variables)
    if(ofstr) {
        ofstr << msg;
        ofstr.close();
    }
    else {
        // A transient file-open failure (disk full, EACCES, ...) must never bring the
        // optimisation down: fall back to std::cerr so the message is at least visible,
        // with a one-line diagnostic that makes the lost log target visible to the
        // operator. Do NOT turn this back into a fatal path.
        std::cerr << "[GFileLogger::log] could not open \"" << fname_
                  << "\" for appending — falling back to stderr:" << '\n'
                  << msg;
    }
}

/******************************************************************************/
/**
 * @brief Logs a message to a source-specific file in append mode
 *
 * This function logs a message to a file, whose name it takes from the private
 * variable fname_. The file is reopened in append mode for every log message.
 * In addition to the standard log() function, this function appends the logging
 * source to the file name. On a failure to open the file, the message is written
 * to std::cerr instead.
 *
 * @param msg The log message to be appended to the file
 * @param extension An identifier of the logging source, appended (with an underscore) to the file name
 */
void GFileLogger::logWithSource(std::string const &msg, std::string const &extension) const {
    std::ofstream ofstr(
        std::filesystem::path(fname_ + "_" + extension),
        std::ios_base::app
    ); // NOLINT(cppcoreguidelines-init-variables)
    if(ofstr) {
        if(first_) {
            ofstr << "Logging data from source " + extension << '\n' << msg;
            ofstr.close();
            first_ = false;
        }
        else {
            ofstr << msg;
            ofstr.close();
        }
    }
    else {
        // Same fallback as GFileLogger::log(): a transient open failure
        // should not bring the optimisation down. Emit a one-line
        // diagnostic to stderr and let execution continue.
        std::cerr << "[GFileLogger::logWithSource] could not open \""
                  << (fname_ + "_" + extension) << "\" for appending — "
                  << "falling back to stderr:" << '\n'
                  << msg;
    }
}

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * @brief A constructor that stores both accompanying information and the desired log type
 *
 * Takes both accompanying information and the desired log type as an argument and
 * stores the information for later perusal.
 *
 * @param accomp_info Accompanying information (e.g. a call-site location string)
 * @param lt The type of logging event this manipulator triggers
 */
GManipulator::GManipulator(std::string const &accomp_info, logType lt)
  : accomp_info_(accomp_info)
  , log_type_(lt) { /* nothing */
}

/******************************************************************************/
/**
 * @brief A constructor that stores the logging type only
 *
 * @param lt The type of logging event this manipulator triggers
 */
GManipulator::GManipulator(logType lt)
  : log_type_(lt) { /* nothing */
}

/******************************************************************************/
/**
 * @brief A constructor that additionally stores a process return code (used by logType::EXIT)
 *
 * @param accomp_info Accompanying information (e.g. a call-site location string)
 * @param lt The type of logging event this manipulator triggers
 * @param return_code The process return code to be used by logType::EXIT
 */
GManipulator::GManipulator(std::string const &accomp_info, logType lt, int return_code)
  : accomp_info_(accomp_info)
  , log_type_(lt)
  , return_code_(return_code) { /* nothing */
}

/******************************************************************************/
/**
 * @brief Retrieves the stored logging type
 *
 * @return The logging type stored in this manipulator
 */
logType GManipulator::getLogType() const {
    return log_type_;
}

/******************************************************************************/
/**
 * @brief Retrieves the stored process return code (meaningful for logType::EXIT)
 *
 * @return The stored process return code
 */
int GManipulator::getReturnCode() const {
    return return_code_;
}

/******************************************************************************/
/**
 * @brief Retrieves stored accompanying information (if any)
 *
 * @return The accompanying information string (empty if none was stored)
 */
std::string GManipulator::getAccompInfo() const {
    return accomp_info_;
}

/******************************************************************************/
/**
 * @brief Checks whether any accompanying information is available
 *
 * @return true if accompanying information was stored, false otherwise
 */
bool GManipulator::hasAccompInfo() const {
    return not accomp_info_.empty();
}

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * @brief Initialization with a string source extension
 *
 * Initialization with an optional string source extension for log files
 * or as additional information in std-output logs
 *
 * @param extension A source-identifier string attached to the streamed output
 */
GLogStreamer::GLogStreamer(std::string const &extension)
  : extension_(extension) { /* nothing */
}

/******************************************************************************/
/**
 * @brief Initialization with the path of a one-time log file
 *
 * Initialization with the name and path of a file used for one-time logging
 *
 * @param log_file The path of the one-time log file this streamer writes to
 */
GLogStreamer::GLogStreamer(std::filesystem::path log_file)
  : log_file_(std::move(log_file)) { /* nothing */
}

/******************************************************************************/
/**
 * @brief Streams a std::ostream manipulator (e.g. std::endl) into the streamer
 *
 * Needed for ostringstream
 *
 * @param val A std::ostream manipulator function pointer
 * @return A reference to this streamer, to allow chaining
 */
GLogStreamer &GLogStreamer::operator<<(std::ostream &(*val)(std::ostream &)) {
    oss_ << val;
    return *this;
}

/******************************************************************************/
/**
 * @brief Streams a std::ios manipulator into the streamer
 *
 * Needed for ostringstream
 *
 * @param val A std::ios manipulator function pointer
 * @return A reference to this streamer, to allow chaining
 */
GLogStreamer &GLogStreamer::operator<<(std::ios &(*val)(std::ios &)) {
    oss_ << val;
    return *this;
}

/******************************************************************************/
/**
 * @brief Streams a std::ios_base manipulator into the streamer
 *
 *  Needed for ostringstream
 *
 * @param val A std::ios_base manipulator function pointer
 * @return A reference to this streamer, to allow chaining
 */
GLogStreamer &GLogStreamer::operator<<(std::ios_base &(*val)(std::ios_base &)) {
    oss_ << val;
    return *this;
}

namespace {

/******************************************************************************/
/**
 * @brief Assembles the boxed banner shared by the EXCEPTION, TERMINATION and WARNING log types.
 *
 * The three severities historically duplicated the same ostringstream layout, differing only in the
 * heading and the two-line advisory. This single builder reproduces that layout byte-for-byte.
 *
 * @param severity The banner heading ("ERROR" or "WARNING")
 * @param when The recording timestamp (GLogStreamer::currentTimeAsString())
 * @param accompInfo Accompanying context recorded by the manipulator
 * @param body The accumulated log message
 * @param advice The two-line "if you suspect ..." advisory (differs between errors and warnings)
 * @return The fully formatted banner string
 */
std::string assembleBanner(
    std::string_view severity,
    std::string_view when,
    std::string_view accompInfo,
    std::string_view body,
    std::string_view advice
) {
    return std::format(
        "\n"
        "================================================\n"
        "{} ( recorded on {} )\n"
        "{}\n"
        "\n"
        "{}\n"
        "{}\n"
        "\n"
        "We appreciate your help!\n"
        "The Geneva team\n"
        "================================================\n",
        severity, when, accompInfo, body, advice
    );
}

/// The advisory shown for hard errors (EXCEPTION / TERMINATION).
constexpr std::string_view ERROR_ADVICE =
    "If you suspect that this error is due to Geneva,\n"
    "then please consider filing a bug.";
/// The advisory shown for warnings.
constexpr std::string_view WARNING_ADVICE =
    "If you suspect that there is an underlying problem with Geneva,\n"
    "then please consider filing a bug.";

} // anonymous namespace

/******************************************************************************/
/**
 * @brief Interface to the actual logging mechanism
 *
 * Dispatches the accumulated stream content according to the manipulator's log
 * type (exception, termination, warning, logging, file, stdout, stderr or exit).
 * Note that this function does not return a reference to self, as it is meant to
 * be called as the last element of a streaming-chain.
 *
 * @param gm A GManipulator object (e.g. produced by the GEXCEPTION / GWARNING / GLOGGING macros) whose log type selects the action taken
 */
// NOLINTNEXTLINE(readability-function-size) -- one switch-driven dispatcher over logType (exception/termination/warning/logging/file/stdout/stderr/exit); each case is a short, self-contained action and splitting would only scatter the dispatch table
void GLogStreamer::operator<<(GManipulator const &gm) {
    switch(gm.getLogType()) {
    //------------------------------------------------------------------------
    case Gem::Common::logType::EXCEPTION: {
        const std::string error =
            assembleBanner("ERROR", GLogStreamer::currentTimeAsString(), gm.getAccompInfo(), oss_.str(), ERROR_ADVICE);

        // Do all necessary logging. We use a central exception file for this purpose.
        // The logger's routines will in addition try to print on the console. Note
        // that we ignore any "source" information, as this is already contained
        // in the logged message.
        GFileLogger const gfl("GENEVA-EXCEPTION.log");
        gfl.log(error);

        // Send the exception out. This done globally, so an exception
        // thrown from within a thread doesn't get lost.
        glogger_ptr->throwException(error);
    } break;

    //------------------------------------------------------------------------
    case Gem::Common::logType::TERMINATION: {
        const std::string error =
            assembleBanner("ERROR", GLogStreamer::currentTimeAsString(), gm.getAccompInfo(), oss_.str(), ERROR_ADVICE);

        // Do all necessary logging. We use a central exception file for this purpose.
        // The logger's routines will in addition try to print on the console. Note
        // that we ignore any "source" information, as this is already contained
        // in the logged message.
        GFileLogger const gfl("GENEVA-TERMINATION.log");
        gfl.log(error);

        // Initiate the termination sequence.
        glogger_ptr->terminateApplication(error);
    } break;

    //------------------------------------------------------------------------
    case Gem::Common::logType::WARNING: {
        const std::string warning =
            assembleBanner("WARNING", GLogStreamer::currentTimeAsString(), gm.getAccompInfo(), oss_.str(), WARNING_ADVICE);

        // Do all necessary logging.
        if(this->hasExtension()) {
            glogger_ptr->logWithSource(warning, this->getExtension());
        }
        else {
            glogger_ptr->log(warning);
        }
    } break;

    //------------------------------------------------------------------------
    case Gem::Common::logType::LOGGING: {
        // Do all necessary logging.
        if(this->hasExtension()) {
            glogger_ptr->logWithSource(oss_.str(), this->getExtension());
        }
        else {
            glogger_ptr->log(oss_.str());
        }
    } break;

    //------------------------------------------------------------------------
    case Gem::Common::logType::FILE: {
        if(this->hasOneTimeLogFile()) {
            GFileLogger const gfl(this->getOneTimeLogFile());
            gfl.log(oss_.str());
        }
        else {
            raiseException(
                "In GLogStreamer::operator<<(const GManipulator&): Error!"
                << '\n'
                << "Tried to log to one time log file without a file name specification"
                << '\n'
                << "You need to supply a file name like this:" << '\n'
                << "glogger(\"filename.txt\") << \"some log text\" << GFILE" << '\n'
            );
        }
    } break;

    //------------------------------------------------------------------------
    case Gem::Common::logType::STDOUT: {
        glogger_ptr->toStdOut(oss_.str());
    } break;

    //------------------------------------------------------------------------
    case Gem::Common::logType::STDERR: {
        glogger_ptr->toStdErr(oss_.str());
    } break;

    //------------------------------------------------------------------------
    case Gem::Common::logType::EXIT: {
        // A deliberate, clean exit with a chosen return code -- NOT a crash, so no "please file a
        // bug" framing. Record the message in the normal log, then print it and exit cleanly
        // (std::exit, no core dump).
        std::ostringstream msg; // NOLINT(cppcoreguidelines-init-variables)
        msg << oss_.str() << '\n';

        if(this->hasExtension()) {
            glogger_ptr->logWithSource(msg.str(), this->getExtension());
        }
        else {
            glogger_ptr->log(msg.str());
        }

        glogger_ptr->exitApplication(msg.str(), gm.getReturnCode());
    } break;

        //------------------------------------------------------------------------
    };
}

/******************************************************************************/
/**
 * Returns the content of the ostringstream object.
 *
 * @return The content of the ostringstream object
 */
std::string GLogStreamer::content() const {
    return oss_.str();
}

/******************************************************************************/
/**
 * @brief Resets the stream content, storing an empty string in the ostringstream object.
 */
void GLogStreamer::reset() {
    oss_.str("");
}

/******************************************************************************/
/**
 * @brief Checks whether an extension string has been registered
 *
 * @return true if a non-empty source-extension string was registered, false otherwise
 */
bool GLogStreamer::hasExtension() const {
    return not extension_.empty();
}

/******************************************************************************/
/**
 * The content of the extension_ string
 */
std::string GLogStreamer::getExtension() const {
    return extension_;
}

/******************************************************************************/
/**
 * Checks whether a log file name has been registered
 */
bool GLogStreamer::hasOneTimeLogFile() const {
    return not log_file_.empty();
}

/******************************************************************************/
/**
 * The name of the manually specified file
 */
std::filesystem::path GLogStreamer::getOneTimeLogFile() const {
    return log_file_;
}

/******************************************************************************/

} /* namespace Gem::Common */
