/********************************************************************************
 *
 * This file is part of the Geneva library collection. The following license
 * applies to this file:
 *
 * ------------------------------------------------------------------------------
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ------------------------------------------------------------------------------
 *
 * Note that other files in the Geneva library collection may use a different
 * license. Please see the licensing information in each file.
 *
 ********************************************************************************
 *
 * See the NOTICE file in the top-level directory of the Geneva library
 * collection for a list of contributors and copyright information.
 *
 ********************************************************************************/

#include "geneva/genome/GGenomeFixedSizePriorityQueue.hpp"
#include "weft/GArchivePolymorphic.hpp" // GEM_REGISTER_ARCHIVABLE (GArchive polymorphic-pointer dispatch)
#include "common/GCommonMathHelperFunctionsT.hpp"
#include "common/GFixedSizePriorityQueueT.hpp"
#include "geneva/GenevaHelperFunctions.hpp"
#include "geneva/genome/GGenome.hpp"
#include <cstddef>
#include <format>
#include <memory>
#include <ranges>
#include <string>

GEM_REGISTER_ARCHIVABLE(Gem::Geneva::Genome::GGenomeFixedSizePriorityQueue) // NOLINT

namespace Gem::Geneva::Genome {

/******************************************************************************/
/**
	 * @brief Initialization with the maximum size. The GGenomeFixedSizePriorityQueue is
	 * targetted at optimization algorithms, which only understand "minimization". Hence
	 * "lower is better" is the only allowed mode of operation of this priority queue.
	 *
	 * @param max_size The maximum number of items the priority queue may hold
	 */
GGenomeFixedSizePriorityQueue::GGenomeFixedSizePriorityQueue(
    const std::size_t &max_size
)
  : Gem::Common::GReflectiveInterfaceT<
        GGenomeFixedSizePriorityQueue,
        Gem::Common::GUniquePtrFixedSizePriorityQueueT<GGenome>>(
        max_size,
        Gem::Common::sortOrder::LOWERISBETTER
    ) { /* nothing */
}

// name_(), compare_(), load_() and clone_() are generated by the Gem::Common::GReflectiveInterfaceT
// base from class_name and the empty localMembers_().

/******************************************************************************/
/**
	 * @brief Checks whether no item has the dirty flag set
	 *
	 * @param pos An out-parameter set to the number of items that were checked (the count of clean items preceding any dirty item, or the total count when all are clean)
	 * @return true if all items are processed (clean), false as soon as a dirty item is found
	 */
bool GGenomeFixedSizePriorityQueue::allClean(std::size_t &pos) const {
    pos = 0;
    for(const auto &item_ptr : data_cnt_) {
        if(not item_ptr->is_processed()) {
            return false;
        }
        pos++;
    }

    return true;
}

/******************************************************************************/
/**
	 * @brief Emits information about the "dirty flag" of all items
	 *
	 * @return A string listing each item's position and clean/dirty status ("c" for clean, "d" for dirty)
	 */
std::string GGenomeFixedSizePriorityQueue::getCleanStatus() const {
    std::string result;
    for(auto const &[pos, item_ptr] : data_cnt_ | std::views::enumerate) {
        result += std::format("({}, {}) ", pos, item_ptr->is_processed() ? "c" : "d");
    }

    return result;
}

/******************************************************************************/
/**
	 * @brief Checks whether an item is admissible, i.e. holds a GGenome item that has
	 * already been evaluated. This is the base class's single admission gate, so every
	 * insertion path -- single or bulk, cloning or taking over -- goes through it.
	 *
	 * @param item_ptr A constant reference to the individual to be checked
	 * @return true if the pointer is non-empty and its item has been processed, false otherwise
	 */
bool GGenomeFixedSizePriorityQueue::isValid(
    const std::unique_ptr<GGenome> &item_ptr
) const {
    // The base implementation rejects an empty handle
    if(not Gem::Common::GUniquePtrFixedSizePriorityQueueT<GGenome>::isValid(item_ptr)) {
        return false;
    }

    // The item must have been worked on
    return item_ptr->is_processed();
}

/******************************************************************************/
/**
	 * @brief Evaluates a single work item, so that it can be sorted. Note that this function
	 * will throw in DEBUG mode, if the dirty flag of item is set. Note that the function
	 * uses the primary evaluation criterion only.
	 *
	 * @param item_ptr A constant reference to the individual to be evaluated
	 * @return The min-only transformed fitness of the item (its primary evaluation criterion)
	 */
double GGenomeFixedSizePriorityQueue::evaluation(
    const std::unique_ptr<GGenome> &item_ptr
) const {
    return minOnly_transformed_fitness(*item_ptr);
}

/******************************************************************************/

} /* namespace Gem::Geneva::Genome */
