/********************************************************************************
 *
 * This file is part of the Geneva library collection. The following license
 * applies to this file:
 *
 * ------------------------------------------------------------------------------
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ------------------------------------------------------------------------------
 *
 * Note that other files in the Geneva library collection may use a different
 * license. Please see the licensing information in each file.
 *
 ********************************************************************************
 *
 * See the NOTICE file in the top-level directory of the Geneva library
 * collection for a list of contributors and copyright information.
 *
 ********************************************************************************/

#include "geneva/genome/GOptimizableEntityFixedSizePriorityQueue.hpp"
#include "weft/GArchivePolymorphic.hpp" // GEM_REGISTER_ARCHIVABLE (GArchive polymorphic-pointer dispatch)
#include "common/GCommonMathHelperFunctionsT.hpp"
#include "common/GExceptions.hpp"
#include "common/GExpectationChecksT.hpp"
#include "common/GFixedSizePriorityQueueT.hpp"
#include "common/GLogger.hpp"
#include "geneva/GenevaHelperFunctions.hpp"
#include "geneva/genome/GGenome.hpp"
#include <algorithm>
#include <cstddef>
#include <format>
#include <iterator>
#include <memory>
#include <ranges>
#include <string>
#include <vector>

GEM_REGISTER_ARCHIVABLE(Gem::Geneva::Genome::GOptimizableEntityFixedSizePriorityQueue) // NOLINT

namespace Gem::Geneva::Genome {

/******************************************************************************/
/**
	 * @brief Initialization with the maximum size. The GOptimizableEntityFixedSizePriorityQueue is
	 * targetted at optimization algorithms, which only understand "minimization". Hence
	 * "lower is better" is the only allowed mode of operation of this priority queue.
	 *
	 * @param max_size The maximum number of items the priority queue may hold
	 */
GOptimizableEntityFixedSizePriorityQueue::GOptimizableEntityFixedSizePriorityQueue(
    const std::size_t &max_size
)
  : Gem::Common::GReflectiveInterfaceT<GOptimizableEntityFixedSizePriorityQueue, Gem::Common::GFixedSizePriorityQueueT<GGenome>>(
        max_size,
        Gem::Common::sortOrder::LOWERISBETTER
    ) { /* nothing */
}

// name_(), compare_(), load_() and clone_() are generated by the Gem::Common::GReflectiveInterfaceT
// base from class_name and the empty localMembers_().

/******************************************************************************/
/**
	 * @brief Checks whether no item has the dirty flag set
	 *
	 * @param pos An out-parameter set to the number of items that were checked (the count of clean items preceding any dirty item, or the total count when all are clean)
	 * @return true if all items are processed (clean), false as soon as a dirty item is found
	 */
bool GOptimizableEntityFixedSizePriorityQueue::allClean(std::size_t &pos) const {
    pos = 0;
    for(const auto &item_ptr : data_deq_) {
        if(not item_ptr->is_processed()) {
            return false;
        }
        pos++;
    }

    return true;
}

/******************************************************************************/
/**
	 * @brief Emits information about the "dirty flag" of all items
	 *
	 * @return A string listing each item's position and clean/dirty status ("c" for clean, "d" for dirty)
	 */
std::string GOptimizableEntityFixedSizePriorityQueue::getCleanStatus() const {
    std::string result;
    for(auto const &[pos, item_ptr] : data_deq_ | std::views::enumerate) {
        result += std::format("({}, {}) ", pos, item_ptr->is_processed() ? "c" : "d");
    }

    return result;
}

/******************************************************************************/
/**
	 * @brief Checks whether an Item is valid, i.e. holds a GGenome item and has
	 * already been evaluated.
	 *
	 * @param item_ptr A shared pointer to the item to be checked
	 * @return true if the pointer is non-empty and its item has been processed, false otherwise
	 */
bool GOptimizableEntityFixedSizePriorityQueue::isValid(
    const std::shared_ptr<GGenome> &item_ptr
) const {
    if(not item_ptr) {
        return false; // Empty
    }
    if(not item_ptr->is_processed()) {
        return false;
    } // The item has not been worked on

    // Everything ok
    return true;
}

/******************************************************************************/
/**
	 * @brief Evaluates a single work item, so that it can be sorted. Note that this function
	 * will throw in DEBUG mode, if the dirty flag of item is set. Note that the function
	 * uses the primary evaluation criterion only.
	 *
	 * @param item_ptr A shared pointer to the item to be evaluated
	 * @return The min-only transformed fitness of the item (its primary evaluation criterion)
	 */
double GOptimizableEntityFixedSizePriorityQueue::evaluation(
    const std::shared_ptr<GGenome> &item_ptr
) const {
    return minOnly_transformed_fitness(*item_ptr);
}

/******************************************************************************/
/**
	 * @brief Adds items in a range to the priority queue. Only processed ("clean") items are added.
	 *
	 * @param begin An iterator to the first item of the range to be added
	 * @param end An iterator one past the last item of the range to be added
	 * @param do_clone If true, each added item is deep-cloned into the queue rather than co-owned
	 * @param do_replace If true, the queue's existing content is replaced rather than merged
	 */
void GOptimizableEntityFixedSizePriorityQueue::add(
    std::vector<std::shared_ptr<GGenome>>::const_iterator begin,
    std::vector<std::shared_ptr<GGenome>>::const_iterator end,
    bool do_clone,
    bool do_replace
) {
    // Create a std::vector containing only processed items. We only want
    // to add "clean" (i.e. processed) individuals to the queue.
    std::vector<std::shared_ptr<GGenome>> processed_cnt(std::distance(begin, end));
    auto it = std::copy_if(
        begin,
        end,
        processed_cnt.begin(),
        [](const std::shared_ptr<GGenome> &item_ptr) { return item_ptr->is_processed(); }
    );
    processed_cnt.resize(std::distance(processed_cnt.begin(), it));

    // Some error checking -- it should not happen that no processed items are found
    if(processed_cnt.empty()) {
        throw geneva_exception(
            g_error_streamer(DO_LOG, Gem::Common::timeAndPlace())
            << "In GOptimizableEntityFixedSizePriorityQueue::add(range): Error!" << '\n'
            << "Container is empty when it should not be!" << '\n'
        );
    }

    Gem::Common::GFixedSizePriorityQueueT<GGenome>::add(
        processed_cnt.begin(),
        processed_cnt.end(),
        do_clone,
        do_replace
    );
}

/******************************************************************************/
/**
	 * @brief Adds the items in the items_cnt vector to the queue. This overload makes sure
	 * that only processed items (i.e. without errors and with the PROCESSED flag) are
	 * entered into the priority queue.
	 *
	 * @param items_cnt A vector of shared pointers to the items to be added
	 * @param do_clone If true, each added item is deep-cloned into the queue rather than co-owned
	 * @param do_replace If true, the queue's existing content is replaced rather than merged
	 */
void GOptimizableEntityFixedSizePriorityQueue::add(
    std::vector<std::shared_ptr<GGenome>> const &items_cnt,
    const bool do_clone,
    const bool do_replace
) {
    // Create a std::vector containing only processed items. We only want
    // to add "clean" (i.e. processed) individuals to the queue.
    std::vector<std::shared_ptr<GGenome>> processed_cnt(items_cnt.size());
    auto it = std::copy_if(
        items_cnt.begin(),
        items_cnt.end(),
        processed_cnt.begin(),
        [](const std::shared_ptr<GGenome> &item_ptr) { return item_ptr->is_processed(); }
    );
    processed_cnt.resize(std::distance(processed_cnt.begin(), it));

    // Some error checking -- it should not happen that no processed items are found
    if(processed_cnt.empty()) {
        throw geneva_exception(
            g_error_streamer(DO_LOG, Gem::Common::timeAndPlace())
            << "In GOptimizableEntityFixedSizePriorityQueue::add(vec): Error!" << '\n'
            << "Container is empty when it should not be!" << '\n'
        );
    }

    Gem::Common::GFixedSizePriorityQueueT<GGenome>::add(processed_cnt, do_clone, do_replace);
}

/******************************************************************************/
/**
	 * @brief Adds a single item to the queue. This overload makes sure
	 * that only processed items (i.e. without errors and with the PROCESSED flag) are
	 * entered into the priority queue.
	 *
	 * @param item_ptr A shared pointer to the item to be added (ignored if empty or not processed)
	 * @param do_clone If true, the item is deep-cloned into the queue rather than co-owned
	 */
void GOptimizableEntityFixedSizePriorityQueue::add(
    std::shared_ptr<GGenome> const &item_ptr,
    const bool do_clone
) {
    if(item_ptr && item_ptr->is_processed()) {
        Gem::Common::GFixedSizePriorityQueueT<GGenome>::add(item_ptr, do_clone);
    }
}

/******************************************************************************/
/**
	 * @brief Boundary overload: adds the individuals of a unique_ptr-owned population. The population owns its
	 * individuals by unique_ptr, while this archive keeps its own shared_ptr clones, so we clone each
	 * individual across the ownership boundary and hand the (already-cloned) shared_ptrs to the
	 * shared_ptr overload with do_clone == false -- the archive co-owns the clones directly, no second
	 * copy. (do_clone is intentionally ignored: cloning at the boundary is exactly what do_clone asks for.)
	 *
	 * @param items_cnt A vector of unique_ptr-owned individuals to be cloned into the queue
	 * @param do_replace If true, the queue's existing content is replaced rather than merged
	 */
void GOptimizableEntityFixedSizePriorityQueue::add(
    std::vector<std::unique_ptr<GGenome>> const &items_cnt,
    const bool /* do_clone */,
    const bool do_replace
) {
    std::vector<std::shared_ptr<GGenome>> bridge;
    bridge.reserve(items_cnt.size());
    for(auto const &item_ptr : items_cnt) {
        if(item_ptr) {
            bridge.push_back(item_ptr->clone<GGenome>());
        }
    }
    this->add(bridge, false, do_replace);
}

/******************************************************************************/
/**
	 * @brief Boundary overload: adds a unique_ptr population sub-range [begin, end). See the vector overload above.
	 *
	 * @param begin An iterator to the first individual of the range to be cloned into the queue
	 * @param end An iterator one past the last individual of the range
	 * @param do_replace If true, the queue's existing content is replaced rather than merged
	 */
void GOptimizableEntityFixedSizePriorityQueue::add(
    std::vector<std::unique_ptr<GGenome>>::const_iterator begin,
    std::vector<std::unique_ptr<GGenome>>::const_iterator end,
    const bool /* do_clone */,
    const bool do_replace
) {
    std::vector<std::shared_ptr<GGenome>> bridge;
    bridge.reserve(static_cast<std::size_t>(std::distance(begin, end)));
    for(auto it = begin; it != end; ++it) {
        if(*it) {
            bridge.push_back((*it)->clone<GGenome>());
        }
    }
    this->add(bridge, false, do_replace);
}

/******************************************************************************/
/**
	 * @brief Boundary overload: adds a single unique_ptr-owned individual. See the vector overload above.
	 *
	 * @param item_ptr A unique_ptr-owned individual that is cloned into the queue (ignored if empty or not processed)
	 */
void GOptimizableEntityFixedSizePriorityQueue::add(
    std::unique_ptr<GGenome> const &item_ptr,
    const bool /* do_clone */
) {
    if(item_ptr && item_ptr->is_processed()) {
        this->add(item_ptr->clone<GGenome>(), false);
    }
}

/******************************************************************************/
/**
 * @brief Applies modifications to this object. This is needed for testing purposes
 *
 * @return A boolean which indicates whether modifications were made
 */
bool GOptimizableEntityFixedSizePriorityQueue::modify_GUnitTests_() {
#ifdef GEM_TESTING

    bool result = false;

    // Call the parent classes' functions
    if(Gem::Common::GFixedSizePriorityQueueT<GGenome>::modify_GUnitTests_()) {
        result = true;
    }

    return result;

#else /* GEM_TESTING */ // If this function is called when GEM_TESTING isn't set, throw
    Gem::Common::condnotset(
        "GOptimizableEntityFixedSizePriorityQueue<GGenome>::modify_GUnitTests",
        "GEM_TESTING"
    );
    return false;
#endif                  /* GEM_TESTING */
}

/******************************************************************************/
/** @brief Performs self tests that are expected to succeed. This is needed for testing purposes */
void GOptimizableEntityFixedSizePriorityQueue::specificTestsNoFailureExpected_GUnitTests_() {
#ifdef GEM_TESTING

    // Call the parent classes' functions
    Gem::Common::GFixedSizePriorityQueueT<
        GGenome>::specificTestsNoFailureExpected_GUnitTests_();

    //------------------------------------------------------------------------------

#else /* GEM_TESTING */ // If this function is called when GEM_TESTING isn't set, throw
    Gem::Common::condnotset(
        "GOptimizableEntityFixedSizePriorityQueue<GGenome>::specificTestsNoFailureExpected_"
        "GUnitTests",
        "GEM_TESTING"
    );
#endif                  /* GEM_TESTING */
}

/******************************************************************************/
/** @brief Performs self tests that are expected to fail. This is needed for testing purposes */
void GOptimizableEntityFixedSizePriorityQueue::specificTestsFailuresExpected_GUnitTests_() {
#ifdef GEM_TESTING

    // Call the parent classes' functions
    Gem::Common::GFixedSizePriorityQueueT<
        GGenome>::specificTestsFailuresExpected_GUnitTests_();

    //------------------------------------------------------------------------------

#else /* GEM_TESTING */ // If this function is called when GEM_TESTING isn't set, throw
    Gem::Common::condnotset(
        "GOptimizableEntityFixedSizePriorityQueue<GGenome>::specificTestsFailuresExpected_"
        "GUnitTests_",
        "GEM_TESTING"
    );
#endif                  /* GEM_TESTING */
}

/******************************************************************************/

} /* namespace Gem::Geneva::Genome */
