###############################################################################
#
# This file is part of the Geneva library collection.
# 
# The purpose of this file is to remove temporary files generated by CMake 
# during the build process
#
# Use at your own risk
#
###############################################################################

SET(
	CMAKE_TEMPORARIES
	${CMAKE_BINARY_DIR}/CMakeCache.txt
	${CMAKE_BINARY_DIR}/cmake_install.cmake
	${CMAKE_BINARY_DIR}/CMakeFiles
)

MESSAGE ("Removing CMake-temporaries ${CMAKE_TEMPORARIES}")

IF( OLD_CMAKE )
	MESSAGE("Cannot remove CMake temporaries, as an old version of CMake is being used")
ELSE()
	FOREACH(
		TEMPORARY
		${CMAKE_TEMPORARIES}
	)
		IF(EXISTS ${TEMPORARY})
			FILE(REMOVE_RECURSE ${TEMPORARY})
		ENDIF()
	ENDFOREACH()
ENDIF()

MESSAGE ("done ...")
