/**
 * @file GMultiCriterionParabolaIndividual.hpp
 */

/********************************************************************************
 *
 * This file is part of the Geneva library collection. The following license
 * applies to this file:
 *
 * ------------------------------------------------------------------------------
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ------------------------------------------------------------------------------
 *
 * Note that other files in the Geneva library collection may use a different
 * license. Please see the licensing information in each file.
 *
 ********************************************************************************
 *
 * See the NOTICE file in the top-level directory of the Geneva library
 * collection for a list of contributors and copyright information.
 *
 ********************************************************************************/

#pragma once

// Global checks, defines and includes needed for all of Geneva
#include "common/GGlobalDefines.hpp"

// Standard header files go here
#include <iostream>

// Boost header files go here

// Geneva header files go here
#include <common/GCommonHelperFunctions.hpp>
#include <common/GParserBuilder.hpp>
#include <filesystem>
#include <memory>
#include <string>
#include <vector>

#include <geneva/genome/GGenome.hpp>
#include <geneva/genome/GGenomeT.hpp>
#include <geneva/genome/GIndividualFactory.hpp>
#include <geneva/genome/GGenomeBuilder.hpp>

namespace Gem::Geneva {

namespace OptimizationAlgorithms {
class GAdaptionConfigBase;
} // namespace OptimizationAlgorithms

// The number of parameters
constexpr std::size_t NPAR_MC = 3;

/******************************************************************************/
/**
 * This individual implements several, possibly conflicting evaluation
 * criteria, each implemented as a parabola with its own minimum
 */
class GMultiCriterionParabolaIndividual : public gen::GGenomeT<GMultiCriterionParabolaIndividual> {
    /***************************************************************************/
    /** @brief serialize()/load_()/compare_()/clone_()/name_() are generated by the GReflectiveInterfaceT base
     *  (via GGenomeT): a genome-only leaf (the per-criterion minima live in the module's load-once store,
     *  not on the individual). The archive still default-constructs the concrete type on load, so it keeps this
     *  friendship. */
    /***************************************************************************/

public:
    /** @brief Opt into GGenomeT's generated empty member list (genome-only leaf, no own state). */
    using gemfony_flat_individual = void;
    /** @brief The class name, consumed by the GReflectiveInterfaceT-generated name_() and compare token. */
    static constexpr std::string_view class_name = "GMultiCriterionParabolaIndividual";

    /** @brief The default constructor -- the genome is installed by the factory */
    GMultiCriterionParabolaIndividual() = default;
    /** @brief A standard copy constructor */
    GMultiCriterionParabolaIndividual(const GMultiCriterionParabolaIndividual &) = default;
    /** @brief The destructor */
    ~GMultiCriterionParabolaIndividual() override = default;

    //---------------------------------------------------------------------------
    // GIndividualFactory<GMultiCriterionParabolaIndividual> hooks. The individual supplies the static
    // hooks the generic factory needs: describeConfig (the configurable
    // values), buildGenome (one constrained-double Gauss group per minimum), applyConfig (the number of
    // evaluation criteria and the per-criterion minima) and buildAdaptionConfig (the OA-owned Gauss
    // adaption config -- authored from the genome layout, NOT stored on the individual).

    /** @brief The configurable values parsed from the config file. */
    struct Config {
        double par_min = -10.;              ///< The lower boundary of the parabola
        double par_max = 10.;               ///< The upper boundary of the parabola
        std::string minima = "-1., 0., 1."; ///< A list of optima, encoded as a string
    };

    /** @brief Registers the config-file options, binding them to the passed Config */
    static void describeConfig(Gem::Common::GParserBuilder &gpb, Config &c);
    /** @brief Builds the flat genome's structure: one constrained double per minimum, in [par_min, par_max] */
    static gen::GenomeData buildGenome(const Config &c);
    /** @brief Per-object post-config hook: sets the number of evaluation criteria and loads the minima once
     *  into the module's load-once store (from which the free evaluator reads them) */
    static void applyConfig(GMultiCriterionParabolaIndividual &ind, const Config &c);
    /** @brief The OA-owned Gauss adaption config: every parameter group gets the configured adaptor.
     *  Authored from the genome layout -- no adaptor data resides on the individual. */
    static std::shared_ptr<OptimizationAlgorithms::GAdaptionConfigBase>
    buildAdaptionConfig(const gen::GGenome &sample, const Config &c);

protected:
    /** @brief The evaluation hook: one parabola per criterion, each around its own minimum (read from the
     *  module's load-once store). @return The per-criterion raw results (size == the number of minima) */
    std::vector<double> evaluate() final;
};

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * A factory for GMultiCriterionParabolaIndividual objects: an alias for the generic, config-driven
 * GIndividualFactory, for which GMultiCriterionParabolaIndividual supplies the static
 * describeConfig / buildGenome / applyConfig hooks. Call sites use ctor(path), get() and
 * registerContentCreator().
 */
using GMultiCriterionParabolaIndividualFactory =
    Gem::Geneva::Genome::GIndividualFactory<GMultiCriterionParabolaIndividual>;

/******************************************************************************/
/**
 * Provide an easy way to print the individual's content
 */
std::ostream &operator<<(std::ostream &, const Gem::Geneva::GMultiCriterionParabolaIndividual &);
std::ostream &
operator<<(std::ostream &, const std::shared_ptr<Gem::Geneva::GMultiCriterionParabolaIndividual> &);

/******************************************************************************/

}

