/********************************************************************************
 *
 * This file is part of the Geneva library collection. The following license
 * applies to this file:
 *
 * ------------------------------------------------------------------------------
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ------------------------------------------------------------------------------
 *
 * Note that other files in the Geneva library collection may use a different
 * license. Please see the licensing information in each file.
 *
 ********************************************************************************
 *
 * See the NOTICE file in the top-level directory of the Geneva library
 * collection for a list of contributors and copyright information.
 *
 ********************************************************************************/

#pragma once

// Global checks, defines and includes needed for all of Geneva
#include "common/GGlobalDefines.hpp"

// Standard headers go here
#include <filesystem>
#include <memory>

// Geneva headers go here
#include "common/GFactoryT.hpp"
#include "geneva/genome/GOptimizableEntity.hpp"
#include "geneva/oa/GOptimizationAlgorithmFactoryT.hpp"

#include "GRandomSearch.hpp"
#include "GRandomSearch_PersonalityTraits.hpp"

namespace Gem::Geneva::OptimizationAlgorithms {

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * @brief A factory that builds GRandomSearch optimization algorithms from a configuration file.
 *
 * A thin specialization of the GOptimizationAlgorithmFactoryT<> scaffold: the config path
 * ("./config/GRandomSearch.json"), getMnemonic() ("rsearch", from the personality traits), getAlgorithmName()
 * and getObject_() are all generated by the scaffold, so the factory needs nothing but its constructors.
 */
class GRandomSearchFactory // NOLINT(cppcoreguidelines-special-member-functions)
  : public GOptimizationAlgorithmFactoryT<GRandomSearch, GRandomSearch_PersonalityTraits> {
    using Base = GOptimizationAlgorithmFactoryT<GRandomSearch, GRandomSearch_PersonalityTraits>;

public:
    /** @brief The default constructor (uses the scaffold's default config-file path). */
    GRandomSearchFactory() = default;
    /** @brief Initialization with the name of the config file.
     *  @param config_file Path to the JSON configuration file from which the algorithm's options are read. */
    explicit GRandomSearchFactory(std::filesystem::path const &config_file)
      : Base(config_file) { /* nothing */ }
    /** @brief Initialization with the name of the config file and a content creator.
     *  @param config_file Path to the JSON configuration file from which the algorithm's options are read.
     *  @param content_creator_ptr Factory used to populate the algorithm's population with individuals. */
    GRandomSearchFactory(
        std::filesystem::path const &config_file,
        std::shared_ptr<Gem::Common::GFactoryT<gen::GOptimizableEntity>> content_creator_ptr
    )
      : Base(config_file, content_creator_ptr) { /* nothing */ }
    /** @brief The copy constructor
     *  @param cp The factory to be copied (default member-wise copy). */
    GRandomSearchFactory(const GRandomSearchFactory &cp) = default;
    /** @brief The destructor */
    ~GRandomSearchFactory() override = default;

    // The constructors' config path, getMnemonic(), getAlgorithmName() and getObject_() are all generated
    // by the GOptimizationAlgorithmFactoryT scaffold; random search adds no extra command-line options.
};

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/

} /* namespace Gem::Geneva::OptimizationAlgorithms */
