/********************************************************************************
 *
 * This file is part of the Geneva library collection. The following license
 * applies to this file:
 *
 * ------------------------------------------------------------------------------
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ------------------------------------------------------------------------------
 *
 * Note that other files in the Geneva library collection may use a different
 * license. Please see the licensing information in each file.
 *
 ********************************************************************************
 *
 * See the NOTICE file in the top-level directory of the Geneva library
 * collection for a list of contributors and copyright information.
 *
 ********************************************************************************/

#include "geneva/oa/GSepCmaEvolutionStrategy_PersonalityTraits.hpp"

#include <string>

#ifdef GEM_TESTING
#include <catch2/catch_test_macros.hpp>
#endif /* GEM_TESTING */

BOOST_CLASS_EXPORT_IMPLEMENT(Gem::Geneva::OptimizationAlgorithms::GSepCmaEvolutionStrategy_PersonalityTraits) // NOLINT

namespace Gem::Geneva::OptimizationAlgorithms {

/******************************************************************************/
/** A short identifier suitable for storage in a std::map -- the command-line mnemonic. */
const std::string GSepCmaEvolutionStrategy_PersonalityTraits::nickname = "sepcma"; // NOLINT

/******************************************************************************/
/**
 * @brief Sets the offspring's selection rank in the current generation (0 == best)
 *
 * @param rank The selection rank to store
 */
void GSepCmaEvolutionStrategy_PersonalityTraits::setRank(std::size_t rank) {
    rank_ = rank;
}

/******************************************************************************/
/**
 * @brief Retrieves the offspring's selection rank in the current generation
 *
 * @return The stored selection rank (0 == best)
 */
std::size_t GSepCmaEvolutionStrategy_PersonalityTraits::getRank() const {
    return rank_;
}

/******************************************************************************/
/**
 * @brief Retrieves the mnemonic of the optimization algorithm
 *
 * @return The mnemonic ("sepcma") associated with this personality
 */
std::string GSepCmaEvolutionStrategy_PersonalityTraits::getMnemonic() const {
    return GSepCmaEvolutionStrategy_PersonalityTraits::nickname;
}

/******************************************************************************/
/**
 * compare_(), name_(), clone_() and load_() are generated by the
 * Gem::Common::GBoilerplateT base from class_name and localMembers_().
 */

/******************************************************************************/
/**
 * @brief Applies modifications to this object. This is needed for testing purposes
 *
 * @return A boolean which indicates whether modifications were made
 */
bool GSepCmaEvolutionStrategy_PersonalityTraits::modify_GUnitTests_() {
#ifdef GEM_TESTING
    bool result = false;

    if(GPersonalityTraits::modify_GUnitTests_()) {
        result = true;
    }

    this->setRank(this->getRank() + 1);
    result = true;

    return result;
#else /* GEM_TESTING */
    Gem::Common::condnotset(
        "GSepCmaEvolutionStrategy_PersonalityTraits::modify_GUnitTests",
        "GEM_TESTING"
    );
    return false;
#endif /* GEM_TESTING */
}

/******************************************************************************/
/**
 * @brief Performs self tests that are expected to succeed. This is needed for testing purposes
 */
void GSepCmaEvolutionStrategy_PersonalityTraits::specificTestsNoFailureExpected_GUnitTests_() {
#ifdef GEM_TESTING
    GPersonalityTraits::specificTestsNoFailureExpected_GUnitTests_();

    {
        std::shared_ptr<GSepCmaEvolutionStrategy_PersonalityTraits> const p_test =
            this->clone<GSepCmaEvolutionStrategy_PersonalityTraits>();

        CHECK_NOTHROW(p_test->setRank(42));
        CHECK(p_test->getRank() == 42);

        p_test->resetParetoTag();
        CHECK(p_test->isOnParetoFront());
        p_test->setIsNotOnParetoFront();
        CHECK(not p_test->isOnParetoFront());
    }
#else /* GEM_TESTING */
    Gem::Common::condnotset(
        "GSepCmaEvolutionStrategy_PersonalityTraits::specificTestsNoFailureExpected_GUnitTests",
        "GEM_TESTING"
    );
#endif /* GEM_TESTING */
}

/******************************************************************************/
/**
 * @brief Performs self tests that are expected to fail. This is needed for testing purposes
 */
void GSepCmaEvolutionStrategy_PersonalityTraits::specificTestsFailuresExpected_GUnitTests_() {
#ifdef GEM_TESTING
    GPersonalityTraits::specificTestsFailuresExpected_GUnitTests_();
#else /* GEM_TESTING */
    Gem::Common::condnotset(
        "GSepCmaEvolutionStrategy_PersonalityTraits::specificTestsFailuresExpected_GUnitTests",
        "GEM_TESTING"
    );
#endif /* GEM_TESTING */
}

/******************************************************************************/

} /* namespace Gem::Geneva::OptimizationAlgorithms */
