/********************************************************************************
 *
 * This file is part of the Geneva library collection. The following license
 * applies to this file:
 *
 * ------------------------------------------------------------------------------
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ------------------------------------------------------------------------------
 *
 * Note that other files in the Geneva library collection may use a different
 * license. Please see the licensing information in each file.
 *
 ********************************************************************************
 *
 * See the NOTICE file in the top-level directory of the Geneva library
 * collection for a list of contributors and copyright information.
 *
 ********************************************************************************/

#pragma once

// Global checks, defines and includes needed for all of Geneva
#include "common/GGlobalDefines.hpp"

// Standard headers go here

// Boost headers go here

// Geneva headers go here
#include "geneva/oa/GBaseParChildPersonalityTraits.hpp"

namespace Gem::Geneva::OptimizationAlgorithms {

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * This class allows to add variables and functions to GPersonalityTraits that
 * are specific to simulated annealing. Note that at the current time this class
 * adds no additional data. Since each optimization algorithm needs its own
 * personality type, though, we provide this default implementation. The base
 * class is the same as for evolutionary algorithms, as in Geneva Simulated Annealing
 * uses the same framework.
 */
class GSimulatedAnnealing_PersonalityTraits // NOLINT(cppcoreguidelines-special-member-functions)
  : public Gem::Common::GReflectiveInterfaceT<GSimulatedAnnealing_PersonalityTraits, GBaseParChildPersonalityTraits> {
    ///////////////////////////////////////////////////////////////////////
    // boost::serialization::access default-constructs this concrete type on load;
    // GReflectiveInterfaceAccess lets the GReflectiveInterfaceT base reach the (empty) localMembers_().
    friend class boost::serialization::access;
    friend struct Gem::Common::GReflectiveInterfaceAccess;

    /** @brief This traits class adds no own state (only its identity). @return An empty member tuple */
    template <typename Self>
    auto localMembers_(this Self &) {
        return std::make_tuple();
    }
    ///////////////////////////////////////////////////////////////////////

public:
    /** @brief The class name, consumed by the GReflectiveInterfaceT-generated name_() / compare token. */
    static constexpr std::string_view class_name = "GSimulatedAnnealing_PersonalityTraits";

    /** @brief An easy identifier for the class */
    static const std::string nickname; // Initialized in the .cpp definition file

    /** @brief The default constructor */
    GSimulatedAnnealing_PersonalityTraits() = default;
    /** @brief The copy contructor */
    
    GSimulatedAnnealing_PersonalityTraits(const GSimulatedAnnealing_PersonalityTraits &) = default;

    /** @brief The standard destructor */
    ~GSimulatedAnnealing_PersonalityTraits() override = default;

    /**
     * @brief Retrieves the mnemonic of the optimization algorithm.
     * @return The short mnemonic string identifying the simulated annealing algorithm
     */
    [[nodiscard]] std::string getMnemonic() const override;

protected:
    /***************************************************************************/
    // load_(), compare_(), name_() and clone_() are generated by the
    // Gem::Common::GReflectiveInterfaceT base from class_name and the empty localMembers_().

    /**
     * @brief Applies modifications to this object. This is needed for testing purposes.
     * @return A boolean indicating whether modifications were actually carried out
     */
    bool modify_GUnitTests_() override;
    /** @brief Performs self tests that are expected to succeed. This is needed for testing purposes */
    void specificTestsNoFailureExpected_GUnitTests_() override;
    /** @brief Performs self tests that are expected to fail. This is needed for testing purposes */
    void specificTestsFailuresExpected_GUnitTests_() override;

    /***************************************************************************/
};

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/

} /* namespace Gem::Geneva::OptimizationAlgorithms */


