/*
 * This file is part of the Geneva library collection.
 *
 * See the NOTICE file in the top-level directory of the Geneva library
 * collection for a list of contributors and copyright information.
 *
 * The following license applies to the code IN THIS FILE:
 *
 * ***************************************************************************
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * ***************************************************************************
 *
 * NOTE THAT THE BOOST-LICENSE DOES NOT APPLY TO ANY OTHER FILES OF THE
 * GENEVA LIBRARY, UNLESS THIS IS EXPLICITLY STATED IN THE CORRESPONDING FILE!
 */

#pragma once

#include "common/GGlobalDefines.hpp"

// Standard headers go here
#include <csignal>
#include <cstdint>
#include <istream>
#include <ostream>
#include <string>
#include <type_traits>
#include <utility>

// Boost headers go here

// Geneva headers go here

/******************************************************************************/
/**
 * We need local signals, so we can act both on Windows and POSIX-OSs
 */
#if defined(_MSC_VER) && (_MSC_VER >= 1020)
#define G_SIGHUP CTRL_CLOSE_EVENT
#else
#define G_SIGHUP SIGHUP
#endif
/******************************************************************************/

namespace Gem::Common {

/******************************************************************************/
/**
 * By default GBlockingMPMCQueueT will have this size. As the buffer
 * dynamically grows and shrinks, we choose a very high value. This
 * is a safeguard against errors like endless loops that might keep
 * filling the buffer until memory is exhausted. In normal work
 * conditions, however, the buffer should never reach its upper
 * limit.
 */
#ifdef GENEVA_COMMON_DEFAULT_BUFFER_SIZE
constexpr std::size_t DEFAULTBUFFERSIZE = GENEVA_COMMON_DEFAULT_BUFFER_SIZE;
#else
constexpr std::size_t DEFAULTBUFFERSIZE = 5000;
#endif

/******************************************************************************/
// A basetype used for all enums in Geneva
using ENUMBASETYPE = std::uint16_t;

/******************************************************************************/
/**
 * Opt-in numeric stream insertion/extraction for Geneva's enum classes (needed
 * for streaming / Gem::Common::fromString<>).
 *
 * Nearly every Geneva enum streams as its underlying numeric value; the
 * operator bodies used to be copy-pasted per enum across all libraries. An enum
 * now opts in by specializing the marker variable template below (in namespace
 * Gem::Common, right next to the enum's definition), and the two constrained
 * operator templates that follow supply the one shared implementation. A
 * namespace other than Gem::Common additionally re-exports the operators once
 * via using-declarations so that ADL finds them for its own enums (see e.g.
 * GPlotEnums.hpp).
 *
 * Enums with textual (non-numeric) streaming -- Gem::Common::tribool,
 * Gem::Courtier::processingStatus -- simply do not opt in and keep their
 * hand-written operators.
 */
template <typename enum_type>
inline constexpr bool numeric_enum_io_v = false;

/** @brief Satisfied by enum types that opted into numeric streaming via numeric_enum_io_v */
template <typename enum_type>
concept numeric_io_enum = std::is_enum_v<enum_type> && numeric_enum_io_v<enum_type>;

/**
 * @brief Writes an opted-in enum to a stream as its underlying numeric value
 * @param o The output stream to write to
 * @param x The enum value to be streamed out
 * @return A reference to the output stream
 */
template <numeric_io_enum enum_type>
std::ostream &operator<<(std::ostream &o, enum_type const &x) {
    // The wide intermediate keeps a std::uint8_t-based enum printing as a
    // number rather than as a single character
    o << static_cast<std::int64_t>(std::to_underlying(x));
    return o;
}

/**
 * @brief Reads an opted-in enum from a stream as its underlying numeric value
 * @param i The input stream to read from
 * @param x The enum value to be filled from the stream
 * @return A reference to the input stream
 */
template <numeric_io_enum enum_type>
std::istream &operator>>(std::istream &i, enum_type &x) {
    // Wide intermediate for the same reason as in operator<< (a std::uint8_t
    // would otherwise be read as a single character)
    std::int64_t tmp = 0;
    i >> tmp;
    x = static_cast<enum_type>(tmp);
    return i;
}

/******************************************************************************/
/**
 * This enum denotes different dimensions (used particularly by GDecoratorCollection
 */
enum class dimensions : Gem::Common::ENUMBASETYPE {
    Dim1 = 1,
    Dim2 = 2,
    Dim3 = 3,
    Dim4 = 4
};

/** @brief dimensions streams as its underlying numeric value (see numeric_enum_io_v) */
template <> inline constexpr bool numeric_enum_io_v<dimensions> = true;

/******************************************************************************/
/**
 * The limit for similarity checks of floating point numbers
 */
constexpr double CE_DEF_SIMILARITY_DIFFERENCE = 1e-5;

/******************************************************************************/
/**
 * Indicates whether higher or lower values are considered better. Needed e.g.
 * in conjunction with the sorting in priority queues.
 */
enum class sortOrder : Gem::Common::ENUMBASETYPE {
    LOWERISBETTER = 0,
    HIGHERISBETTER = 1
};

/** @brief sortOrder streams as its underlying numeric value (see numeric_enum_io_v) */
template <> inline constexpr bool numeric_enum_io_v<sortOrder> = true;

/******************************************************************************/
/**
 * Different log and exception types
 */
enum class logType : Gem::Common::ENUMBASETYPE {
    EXCEPTION = 0,
    TERMINATION = 1,
    WARNING = 2,
    LOGGING = 3,
    FILE = 4,
    STDOUT = 5,
    STDERR = 6,
    EXIT = 7 ///< A deliberate, clean program exit with a chosen return code (see LOGEXIT)
};

/** @brief logType streams as its underlying numeric value (see numeric_enum_io_v) */
template <> inline constexpr bool numeric_enum_io_v<logType> = true;

/******************************************************************************/
/**
 * The default number of bins in histograms, used in GPlotDesigner
 */
constexpr std::size_t DEFAULTNBINSGPD = 100;

/******************************************************************************/
/**
 * Used in parameter definitions (GParserBuilder)
 */
constexpr bool VAR_IS_ESSENTIAL = true;
constexpr bool VAR_IS_SECONDARY = false;

/******************************************************************************/
/** @brief Three-valued logic type */
enum class tribool : Gem::Common::ENUMBASETYPE {
    False = 0,
    Indeterminate = 1,
    True = 2
};

/**
 * @brief Tests whether a tribool is in the Indeterminate state.
 *
 * @param t The tribool value to be tested
 * @return true if @p t equals tribool::Indeterminate, false otherwise
 */
inline bool indeterminate(tribool t) noexcept { return t == tribool::Indeterminate; }

/**
 * @brief Puts a Gem::Common::tribool into a stream.
 * @param o The output stream to write to
 * @param x The tribool value to be streamed out
 * @return A reference to the output stream
 */
std::ostream &operator<<(std::ostream &o, Gem::Common::tribool const &x);

/******************************************************************************/
/**
 * The serialization modes that are currently allowed. The two GArchive (Weft) codecs are the only
 * modes; the numeric values 3/4 are retained (rather than renumbered to 0/1) so configuration files
 * carry stable mode values -- values 0-2 belonged to the removed Boost.Serialization text/XML/binary
 * archives and are simply no longer valid.
 */
enum class serializationMode : Gem::Common::ENUMBASETYPE {
    GEM_BINARY = 3, ///< GArchive flat little-endian binary codec (the networked-wire default)
    GEM_JSON = 4    ///< GArchive self-describing JSON codec (the checkpoint default)
};

/** @brief serializationMode streams as its underlying numeric value (see numeric_enum_io_v) */
template <> inline constexpr bool numeric_enum_io_v<serializationMode> = true;

/**
 * @brief Converts a serializationMode to a string representation for debugging purposes.
 * @param s The serializationMode value to be converted
 * @return A human-readable string representation of @p s
 */
[[nodiscard]] std::string serModeToString(Gem::Common::serializationMode ser_mod);

/******************************************************************************/
/**
 * Specification of whether checkExpectation should emit messages
 */
constexpr bool CE_SILENT = false;
constexpr bool CE_WITH_MESSAGES = true;

/******************************************************************************/
/**
 * Needed to express expectations in testing framework.
 */
enum class expectation : Gem::Common::ENUMBASETYPE {
    EQUALITY = 0 // bitwise equality of all checked components
        ,
    FP_SIMILARITY = 1 // equality for non-floating point components, similarity for floating point
        ,
    INEQUALITY = 2 // at least one checked component differs
};

/** @brief expectation streams as its underlying numeric value (see numeric_enum_io_v) */
template <> inline constexpr bool numeric_enum_io_v<expectation> = true;

/******************************************************************************/
/**
 * Specification of the default number of threads, when no information about hardware
 * concurrency can be determined.
 */
constexpr unsigned int DEFAULTNHARDWARETHREADS = 2;
/**
 * Specification of the default maximum number of threads
 */
constexpr unsigned int DEFAULTMAXNHARDWARETHREADS = 4;

/******************************************************************************/

} /* namespace Gem::Common */
