/********************************************************************************
 *
 * This file is part of the Geneva library collection. The following license
 * applies to this file:
 *
 * ------------------------------------------------------------------------------
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ------------------------------------------------------------------------------
 *
 * Note that other files in the Geneva library collection may use a different
 * license. Please see the licensing information in each file.
 *
 ********************************************************************************
 *
 * See the NOTICE file in the top-level directory of the Geneva library
 * collection for a list of contributors and copyright information.
 *
 ********************************************************************************/

#pragma once

// Global checks, defines and includes needed for all of Geneva
#include "common/GGlobalDefines.hpp"

// Standard headers go here

// Boost headers go here

// Geneva headers go here
#include "common/GReflectiveInterfaceT.hpp"
#include "common/GCommonInterfaceT.hpp"
#include "common/GExceptions.hpp"

namespace Gem::Geneva {

/******************************************************************************/
/**
 * This is the base class -- and the CRTP category root -- for a small hierarchy
 * that encapsulates information relevant to particular optimization algorithms.
 * The information is stored in individuals (i.e. the parameter sets which are
 * subject to a given optimization problem). In this sense, individuals can take
 * on more than one role or personality. Note that this class is purely virtual.
 * It can only be used in conjunction with a derived personality.
 *
 * As part of the GObject-decomposition effort, the personality-traits hierarchy
 * is its own category root: it derives directly from
 * Gem::Common::GCommonInterfaceT<GPersonalityTraits> instead of from GObject, so
 * a GPersonalityTraits pointer is an unrelated type to a GObject pointer. The
 * common infrastructure (clone/load/compare/name/IO/serialize) is supplied by
 * the CRTP base, instantiated for this root.
 */
class GPersonalityTraits // NOLINT(cppcoreguidelines-special-member-functions)
  : public Gem::Common::GReflectiveInterfaceBaseT<GPersonalityTraits, Gem::Common::GCommonInterfaceT<GPersonalityTraits>> {
    ///////////////////////////////////////////////////////////////////////
    // GReflectiveInterfaceAccess lets the GReflectiveInterfaceBaseT base reach this class's
    // (empty) localMembers_(); this abstract category root is never Boost-constructed.
    friend struct Gem::Common::GReflectiveInterfaceAccess;

    /**
     * @brief This category root carries no own state; the *explicit* empty member
     * list is required (a missing one is rejected at compile time by GReflectiveInterfaceBaseT).
     * @return An empty member tuple
     */
    template <typename Self>
    auto localMembers_(this Self &) {
        return std::make_tuple();
    }
    ///////////////////////////////////////////////////////////////////////

public:
    /** @brief The class name, consumed by the GReflectiveInterfaceBaseT-generated name_() / compare token. */
    static constexpr std::string_view class_name = "GPersonalityTraits";

    /** @brief The default constructor */
    GPersonalityTraits() = default;
    /** @brief The copy constructor */
    GPersonalityTraits(const GPersonalityTraits &) = default;
    /** @brief The standard destructor */
    ~GPersonalityTraits() override = default;

    /**
     * @brief Retrieves the mnemonic of the optimization algorithm
     * @return The short mnemonic string identifying the algorithm this personality belongs to
     */
    [[nodiscard]] virtual std::string getMnemonic() const = 0;

protected:
    // load_(), compare_(), name_() and clone_() are generated by the
    // Gem::Common::GReflectiveInterfaceBaseT base (clone_ stays pure -- this is the abstract
    // category root) from class_name and the empty localMembers_() declaration above.

    /**
     * @brief Applies modifications to this object. This is needed for testing purposes
     * @return true if a modification was actually performed, false otherwise
     */
    bool modify_GUnitTests_() override;
    /** @brief Performs self tests that are expected to succeed. This is needed for testing purposes */
    void specificTestsNoFailureExpected_GUnitTests_() override;
    /** @brief Performs self tests that are expected to fail. This is needed for testing purposes */
    void specificTestsFailuresExpected_GUnitTests_() override;
};

/******************************************************************************/

} /* namespace Gem::Geneva */

/******************************************************************************/
/**
 * @brief Needed for Boost.Serialization
 */
BOOST_SERIALIZATION_ASSUME_ABSTRACT(
    Gem::Geneva::GPersonalityTraits
) // NOLINT/******************************************************************************/
