/********************************************************************************
 *
 * This file is part of the Geneva library collection. The following license
 * applies to this file:
 *
 * ------------------------------------------------------------------------------
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ------------------------------------------------------------------------------
 *
 * Note that other files in the Geneva library collection may use a different
 * license. Please see the licensing information in each file.
 *
 ********************************************************************************
 *
 * See the NOTICE file in the top-level directory of the Geneva library
 * collection for a list of contributors and copyright information.
 *
 ********************************************************************************/

#pragma once

// Global checks, defines and includes needed for all of Geneva
#include "common/GGlobalDefines.hpp"

// Standard header files go here
#include <array>
#include <algorithm>
#include <chrono>
#include <filesystem>
#include <any>
#include <format>
#include <fstream>
#include <ranges>
#include <string>
#include <type_traits>
#include <utility>

// Boost header files go here

// Geneva headers go here
#include "common/GReflectiveInterfaceT.hpp"
#include "common/GCommonEnums.hpp"
#include "common/GCommonHelperFunctions.hpp"
#include "common/GLogger.hpp"
#include "dietrich/GPlotDesigner.hpp"
#include "geneva/ind/GParameterPropertyParser.hpp"
#include "geneva/ind/GOptimizableEntity.hpp"
#include "geneva/oa/GOptimizationAlgorithmBase.hpp"
#include "geneva/oa/GAdaption.hpp"
#include "geneva/oa/GAdaptionConfig.hpp"

namespace Gem::Geneva {

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * This class implements the standard output common to all optimization algorithms.
 * It will usually already be registered as a pluggable optimization monitor, when
 * you instantiate a new optimization algorithm.
 */
class GStandardMonitor // NOLINT(cppcoreguidelines-special-member-functions)
  : public Gem::Common::GReflectiveInterfaceT<GStandardMonitor, oa::GBasePluggableOM> {
    ///////////////////////////////////////////////////////////////////////
    // boost::serialization::access default-constructs this concrete type on load;
    // GReflectiveInterfaceAccess lets the GReflectiveInterfaceT base reach this class's (empty) localMembers_().
    friend class boost::serialization::access;
    friend struct Gem::Common::GReflectiveInterfaceAccess;

    /**
     * @brief This monitor adds no own members; the *explicit* empty declaration is
     * required (a missing one would inherit the parent's and is rejected at compile
     * time by GReflectiveInterfaceT).
     * @return An empty member tuple
     */
    template <typename Self>
    auto localMembers_(this Self &) {
        return std::make_tuple();
    }
    ///////////////////////////////////////////////////////////////////////

public:
    /** @brief The class name, consumed by the GReflectiveInterfaceT-generated name_() / compare token. */
    static constexpr std::string_view class_name = "GStandardMonitor";

    /***************************************************************************/

    /** @brief The default constructor */
    GStandardMonitor() = default;
    /**
     * @brief The copy constructor
     * @param cp A constant reference to another GStandardMonitor object whose data is deep-copied
     */
    GStandardMonitor(const GStandardMonitor &cp) = default;
    /** @brief The destructor */
    ~GStandardMonitor() override = default;

protected:
    // load_(), compare_(), name_() and clone_() are generated by the
    // Gem::Common::GReflectiveInterfaceT base from class_name and the empty localMembers_() above.

    /** @brief Applies modifications to this object. */
    bool modify_GUnitTests_() override;
    /** @brief Performs self tests that are expected to succeed. */
    void specificTestsNoFailureExpected_GUnitTests_() override;
    /** @brief Performs self tests that are expected to fail. */
    void specificTestsFailuresExpected_GUnitTests_() override;

private:
    /**
     * @brief Aggregates the work of all registered pluggable monitors
     *
     * The first (unnamed) argument is the information mode (init, processing or finalization).
     * @param goa A constant pointer to the optimization algorithm whose state is being monitored
     */
    void
    informationFunction_(infoMode im, oa::GOptimizationAlgorithmBase const *const goa) override;
};

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * This class allows to output fitness information for a given optimization run.
 * It takes care of successive runs and marks them in the output. Information
 * will be output in the same histogram both for the best individual(s) found so far
 * and for the best individual(s) of each iteration.
 */
class GFitnessMonitor // NOLINT(cppcoreguidelines-special-member-functions)
  : public Gem::Common::GReflectiveInterfaceT<GFitnessMonitor, oa::GBasePluggableOM> {
    ///////////////////////////////////////////////////////////////////////
    friend class boost::serialization::access;
    friend struct Gem::Common::GReflectiveInterfaceAccess;

    /***************************************************************************/
    /**
     * Single declaration of this class'es local data members, driving the
     * GReflectiveInterfaceT-generated serialize(), load_() and compare_() from one place. All members are
     * plain CONFIG (make_member); the accumulated fitness curves live in a
     * transient GDataLog (data_log_), built lazily on the first processing
     * call and NOT serialized -- so the monitor no longer carries plotter
     * objects in its state. No manual tail is needed.
     */
    template <typename Self>
    auto localMembers_(this Self &self) {
        return std::make_tuple(
            Gem::Common::make_member("x_dim_", self.x_dim_),
            Gem::Common::make_member("y_dim_", self.y_dim_),
            Gem::Common::make_member("n_monitor_inds_", self.n_monitor_inds_),
            Gem::Common::make_member("result_file_", self.result_file_)
        );
    }

    ///////////////////////////////////////////////////////////////////////

public:
    /** @brief The class name, consumed by the GReflectiveInterfaceT-generated name_() / compare token. */
    static constexpr std::string_view class_name = "GFitnessMonitor";

    /************************************************************************/

    /** @brief The default constructor */
    GFitnessMonitor() = default;
    /**
     * @brief The copy constructor
     * @param cp A constant reference to another GFitnessMonitor object whose data is deep-copied
     */
    GFitnessMonitor(const GFitnessMonitor &cp);
    /** @brief The destructor */
    ~GFitnessMonitor() override = default;

    /**
     * @brief Allows to specify a different name for the result file
     * @param result_file The new name of the result file
     */
    void setResultFileName(const std::string &result_file);
    /**
     * @brief Allows to retrieve the current value of the result file name
     * @return The current name of the result file
     */
    [[nodiscard]] std::string getResultFileName() const;

    /**
     * @brief Allows to set the dimensions of the canvas
     * @param x_dim The canvas dimension in x-direction
     * @param y_dim The canvas dimension in y-direction
     */
    void setDims(const std::uint32_t &x_dim, const std::uint32_t &y_dim);
    /**
     * @brief Retrieve the dimensions as a tuple
     * @return A tuple holding the canvas dimensions in x- and y-direction
     */
    [[nodiscard]] std::tuple<std::uint32_t, std::uint32_t> getDims() const;
    /**
     * @brief Retrieves the dimension of the canvas in x-direction
     * @return The canvas dimension in x-direction
     */
    [[nodiscard]] std::uint32_t getXDim() const;
    /**
     * @brief Retrieves the dimension of the canvas in y-direction
     * @return The canvas dimension in y-direction
     */
    [[nodiscard]] std::uint32_t getYDim() const;

    /**
     * @brief Sets the number of individuals in the population that should be monitored
     * @param n_monitor_inds The number of individuals that should be monitored
     */
    void setNMonitorIndividuals(const std::size_t &n_monitor_inds);
    /**
     * @brief Retrieves the number of individuals that are being monitored
     * @return The number of individuals that are being monitored
     */
    [[nodiscard]] std::size_t getNMonitorIndividuals() const;

protected:
    // load_(), compare_(), name_() and clone_() are generated by the
    // Gem::Common::GReflectiveInterfaceT base from class_name and localMembers_().

    /** @brief Applies modifications to this object. This is needed for testing purposes */
    bool modify_GUnitTests_() override;
    /** @brief Performs self tests that are expected to succeed. This is needed for testing purposes */
    void specificTestsNoFailureExpected_GUnitTests_() override;
    /** @brief Performs self tests that are expected to fail. This is needed for testing purposes */
    void specificTestsFailuresExpected_GUnitTests_() override;

private:
    /************************************************************************/
    /**
     * @brief Aggregates the work of all registered pluggable monitors
     *
     * The first (unnamed) argument is the information mode (init, processing or finalization).
     * @param goa A constant pointer to the optimization algorithm whose state is being monitored
     */
    void
    informationFunction_(infoMode im, oa::GOptimizationAlgorithmBase const *const goa) override;

    /************************************************************************/

    std::uint32_t x_dim_ = DEFAULTXDIMOM; ///< The dimension of the canvas in x-direction
    std::uint32_t y_dim_ = DEFAULTYDIMOM; ///< The dimension of the canvas in y-direction
    std::size_t n_monitor_inds_ =
        DEFNMONITORINDS; ///< The number of individuals that should be monitored
    std::string result_file_ =
        DEFAULTROOTRESULTFILEOM; ///< The name of the file to which data is emitted

    // Transient run state: the data log accumulates the per-individual fitness curves (one
    // "global best" series per monitored individual, each with an overlaid "iteration best"
    // series). It is built lazily on the first processing call -- its presence replaces the
    // former info_init_run_ flag -- and is NOT part of the monitor's serialized config.
    std::optional<Gem::Dietrich::GDataLog> data_log_;
    std::vector<Gem::Dietrich::GDataLog::SeriesId>
        global_series_ids_; ///< ids of the "global best" series (one per monitored individual)
    std::vector<Gem::Dietrich::GDataLog::SeriesId>
        iteration_series_ids_; ///< ids of the overlaid "iteration best" series
};

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * This class accepts a number of other pluggable monitors and executes them
 * in sequence.
 */
class GCollectiveMonitor // NOLINT(cppcoreguidelines-special-member-functions)
  : public Gem::Common::GReflectiveInterfaceT<GCollectiveMonitor, oa::GBasePluggableOM> {
    ///////////////////////////////////////////////////////////////////////
    // boost::serialization::access default-constructs this concrete type on load;
    // GReflectiveInterfaceAccess lets the GReflectiveInterfaceT base reach localMembers_() for the
    // generated serialize()/load_()/compare_()/name_()/clone_().
    friend class boost::serialization::access;
    friend struct Gem::Common::GReflectiveInterfaceAccess;

    /***************************************************************************/
    /**
     * Single declaration of this class'es only local data member,
     * pluggable_monitors_ (a container of cloneable monitor pointers). It drives
     * the GReflectiveInterfaceT-generated serialize()/load_()/compare_() from one place
     * via make_cloneable_container_member -- the same shape GBasePlotter uses for
     * its secondary_plotter_. (The former bespoke serialize() with a load-time
     * pluggable_monitors_.clear() was a Boost 1.58 relic; Boost's vector-of-
     * shared_ptr load resizes the target correctly, so no pre-clear is needed and
     * the member folds like any other.)
     */
    template <typename Self>
    auto localMembers_(this Self &self) {
        return std::make_tuple(
            Gem::Common::make_cloneable_container_member("pluggable_monitors_", self.pluggable_monitors_)
        );
    }
    ///////////////////////////////////////////////////////////////////////

public:
    /** @brief The class name, consumed by the GReflectiveInterfaceT-generated name_() / compare token. */
    static constexpr std::string_view class_name = "GCollectiveMonitor";

    /***************************************************************************/
    /** @brief The default constructor */
    GCollectiveMonitor() = default;
    /**
     * @brief The copy constructor
     * @param cp A constant reference to another GCollectiveMonitor object whose data is deep-copied
     */
    GCollectiveMonitor(const GCollectiveMonitor &cp);
    /** @brief The destructor */
    ~GCollectiveMonitor() override = default;

    /**
     * @brief Allows to register a new pluggable monitor
     * @param om_ptr A shared pointer to the pluggable optimization monitor to add to this collection
     */
    void registerPluggableOM(const std::shared_ptr<oa::GBasePluggableOM>& om_ptr);
    /**
     * @brief Checks if pluggable monitors have been registered in the collective monitor
     * @return true if at least one pluggable monitor has been registered, false otherwise
     */
    [[nodiscard]] bool hasOptimizationMonitors() const;
    /** @brief Allows to clear all registered monitors */
    void resetPluggbleOM();

protected:
    // serialize(), load_(), compare_(), name_() and clone_() are generated by the
    // Gem::Common::GReflectiveInterfaceT base from class_name and localMembers_().

    /** @brief Applies modifications to this object */
    bool modify_GUnitTests_() override;
    /** @brief Performs self tests that are expected to succeed */
    void specificTestsNoFailureExpected_GUnitTests_() override;
    /** @brief Performs self tests that are expected to fail */
    void specificTestsFailuresExpected_GUnitTests_() override;

private:
    /**
     * @brief Aggregates the work of all registered pluggable monitors
     *
     * The first (unnamed) argument is the information mode (init, processing or finalization).
     * @param goa A constant pointer to the optimization algorithm whose state is being monitored
     */
    void
    informationFunction_(infoMode im, oa::GOptimizationAlgorithmBase const *const goa) override;

    std::vector<std::shared_ptr<oa::GBasePluggableOM>>
        pluggable_monitors_; ///< The collection of monitors
};

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * This class allows to monitor a given set of variables inside of all or of the
 * best individuals of a population, creating a graphical output using ROOT. It
 * supports floating point types only. double and float values may not be mixed.
 *
 * @tparam fp_type The floating point type of the monitored variables (e.g. double or float)
 */
template <typename fp_type>
class GProgressPlotterT // NOLINT(cppcoreguidelines-special-member-functions)
  : public Gem::Common::GReflectiveInterfaceT<GProgressPlotterT<fp_type>, oa::GBasePluggableOM> {
    ///////////////////////////////////////////////////////////////////////
    // boost::serialization::access default-constructs this concrete type on load;
    // GReflectiveInterfaceAccess lets the GReflectiveInterfaceT base reach localMembers_().
    friend class boost::serialization::access;
    friend struct Gem::Common::GReflectiveInterfaceAccess;

    /***************************************************************************/
    /**
     * Single declaration of this class'es local data members, driving the
     * GReflectiveInterfaceT-generated serialize(), load_() and compare_() from one place. These are
     * all plain CONFIG members (make_member) plus fp_prof_var_vec_ (a
     * std::vector<parPropSpec<fp_type>> of by-value Gemfony objects, handled uniformly
     * through make_member); the accumulated plot data lives in a transient GDataLog
     * (data_log_), built per run and NOT serialized.
     */
    template <typename Self>
    auto localMembers_(this Self &self) {
        return std::make_tuple(
            Gem::Common::make_member("fp_prof_var_vec_", self.fp_prof_var_vec_),
            Gem::Common::make_member("canvas_label_", self.canvas_label_),
            Gem::Common::make_member("file_name_", self.file_name_),
            Gem::Common::make_member("canvas_dimensions_", self.canvas_dimensions_),
            Gem::Common::make_member("monitor_best_only_", self.monitor_best_only_),
            Gem::Common::make_member("monitor_valid_only_", self.monitor_valid_only_),
            Gem::Common::make_member("observe_boundaries_", self.observe_boundaries_),
            Gem::Common::make_member("add_print_command_", self.add_print_command_)
        );
    }
    ///////////////////////////////////////////////////////////////////////

    // Make sure this class can only be instantiated if fp_type really is a floating point type
    static_assert(
        std::is_floating_point_v<fp_type>,
        "fp_type should be a floating point type"
    );

public:
    /***************************************************************************/
    /**
	  * The default constructor
	  */
    GProgressPlotterT() = default;

    /** @brief The class name, consumed by the GReflectiveInterfaceT-generated name_() / compare token. */
    static constexpr std::string_view class_name = "GProgressPlotterT<fp_type>";

    /***************************************************************************/
    /**
	  * @brief Construction with the information whether only the best individuals
	  * should be monitored and whether only valid items should be recorded.
	  * Some member variables may be initialized in the class body.
	  *
	  * @param monitor_best_only If true, only the best individual(s) of the population are monitored
	  * @param monitor_valid_only If true, only individuals with a valid parameter set are recorded
	  */
    GProgressPlotterT(bool monitor_best_only, bool monitor_valid_only)
      : canvas_dimensions_(std::tuple<std::uint32_t, std::uint32_t>(1024, 768))
      , monitor_best_only_(monitor_best_only)
      , monitor_valid_only_(monitor_valid_only) { /* nothing */
    }

    /***************************************************************************/
    /**
	  * @brief The copy constructor
	  *
	  * @param cp A constant reference to another GProgressPlotterT object whose data is deep-copied
	  */
    GProgressPlotterT(const GProgressPlotterT<fp_type> &cp)
      : Gem::Common::GReflectiveInterfaceT<GProgressPlotterT<fp_type>, oa::GBasePluggableOM>(cp)
      , canvas_label_(cp.canvas_label_)
      , file_name_(cp.file_name_)
      , canvas_dimensions_(cp.canvas_dimensions_)
      , monitor_best_only_(cp.monitor_best_only_)
      , monitor_valid_only_(cp.monitor_valid_only_)
      , observe_boundaries_(cp.observe_boundaries_)
      , add_print_command_(cp.add_print_command_) {
        // data_log_ is transient run state (rebuilt in INFOINIT) and is not copied.
        Gem::Common::copyCloneableObjectsContainer(cp.fp_prof_var_vec_, fp_prof_var_vec_);
    }

    /***************************************************************************/
    /**
	  * The destuctor
	  */
    ~GProgressPlotterT() override = default;

    /**************************************************************************/
    /**
	  * @brief Sets the specifications of the variables to be profiled. Note that
	  * boolean and integer variables specified in the argument will simply
	  * be ignored.
	  *
	  * @param par_str A non-empty parameter-property specification string describing which floating-point variables to profile
	  */
    void setProfileSpec(std::string const &par_str) {
        // Check that the parameter string isn't empty
        if(par_str.empty()) {
            throw geneva_exception(
                g_error_streamer(DO_LOG, Gem::Common::timeAndPlace())
                << "In GPluggableOptimizationMonitors<>::setProfileSpec(std::string): Error!"
                << '\n'
                << "Parameter string " << par_str << " is empty" << '\n'
            );
        }

        //---------------------------------------------------------------------------
        // Clear the parameter vectors
        fp_prof_var_vec_.clear();

        // Parse the parameter string
        gen::GParameterPropertyParser const ppp(par_str);

        //---------------------------------------------------------------------------
        // Retrieve the parameters

        // fp_cit is already set to the begin of the double parameter arrays; append that half-open range.
        auto [fp_cit, d_end] = ppp.getIterators<fp_type>();
        fp_prof_var_vec_.append_range(std::ranges::subrange(fp_cit, d_end));

        //---------------------------------------------------------------------------
    }

    /***************************************************************************/
    /**
	  * @brief Allows to specify whether only the best individuals should be monitored.
	  *
	  * @param monitor_best_only If true, only the best individual(s) of the population are monitored
	  */
    void setMonitorBestOnly(bool monitor_best_only = true) {
        monitor_best_only_ = monitor_best_only;
    }

    /***************************************************************************/
    /**
	  * @brief Allows to check whether only the best individuals should be monitored.
	  *
	  * @return true if only the best individual(s) are monitored, false otherwise
	  */
    [[nodiscard]] bool getMonitorBestOnly() const {
        return monitor_best_only_;
    }

    /***************************************************************************/
    /**
	  * @brief Allows to specify whether only valid individuals should be monitored.
	  *
	  * @param monitor_valid_only If true, only individuals with a valid parameter set are recorded
	  */
    void setMonitorValidOnly(bool monitor_valid_only = true) {
        monitor_valid_only_ = monitor_valid_only;
    }

    /***************************************************************************/
    /**
	  * @brief Allows to check whether only valid individuals should be monitored.
	  *
	  * @return true if only valid individuals are monitored, false otherwise
	  */
    [[nodiscard]] bool getMonitorValidOnly() const {
        return monitor_valid_only_;
    }

    /***************************************************************************/
    /**
	  * @brief Allows to specify whether scan boundaries should be observed
	  *
	  * @param observe_boundaries If true, values outside a scan boundary are ignored when plotting
	  */
    void setObserveBoundaries(bool observe_boundaries) {
        observe_boundaries_ = observe_boundaries;
    }

    /***************************************************************************/
    /**
	  * @brief Allows to check whether boundaries should be observed
	  *
	  * @return true if scan boundaries are observed, false otherwise
	  */
    [[nodiscard]] bool getObserveBoundaries() const {
        return observe_boundaries_;
    }

    /***************************************************************************/
    /**
	  * @brief Allows to check whether parameters should be profiled
	  *
	  * @return true if at least one variable has been registered for profiling, false otherwise
	  */
    [[nodiscard]] bool parameterProfileCreationRequested() const {
        return not fp_prof_var_vec_.empty();
    }

    /***************************************************************************/
    /**
	  * @brief Retrieves the number of variables that will be profiled
	  *
	  * @return The number of registered profiling variables
	  */
    [[nodiscard]] std::size_t nProfileVars() const {
        return fp_prof_var_vec_.size();
    }

    /***************************************************************************/
    /**
	  * @brief Allows to set the canvas dimensions
	  *
	  * @param canvas_dimensions A tuple holding the canvas dimensions in x- and y-direction
	  */
    void setCanvasDimensions(std::tuple<std::uint32_t, std::uint32_t> canvas_dimensions) {
        canvas_dimensions_ = canvas_dimensions;
    }

    /***************************************************************************/
    /**
	  * @brief Allows to set the canvas dimensions using separate x and y values
	  *
	  * @param x The canvas dimension in x-direction
	  * @param y The canvas dimension in y-direction
	  */
    void setCanvasDimensions(std::uint32_t x, std::uint32_t y) {
        canvas_dimensions_ = std::tuple<std::uint32_t, std::uint32_t>(x, y);
    }

    /***************************************************************************/
    /**
	  * @brief Gives access to the canvas dimensions
	  *
	  * @return A tuple holding the canvas dimensions in x- and y-direction
	  */
    [[nodiscard]] std::tuple<std::uint32_t, std::uint32_t> getCanvasDimensions() const {
        return canvas_dimensions_;
    }

    /******************************************************************************/
    /**
	  * @brief Allows to add a "Print" command to the end of the script so that picture files are created
	  *
	  * @param add_print_command If true, a print command is appended so that picture files are created
	  */
    void setAddPrintCommand(bool add_print_command) {
        add_print_command_ = add_print_command;
    }

    /******************************************************************************/
    /**
	  * @brief Allows to retrieve the current value of the add_print_command_ variable
	  *
	  * @return true if a print command will be appended to the script, false otherwise
	  */
    [[nodiscard]] bool getAddPrintCommand() const {
        return add_print_command_;
    }

    /***************************************************************************/
    /**
	  * @brief Allows to set the filename
	  *
	  * @param file_name The name of the file to which information will be emitted
	  */
    void setFileName(const std::string &file_name) {
        file_name_ = file_name;
    }

    /***************************************************************************/
    /**
	  * @brief Retrieves the current filename to which information will be emitted
	  *
	  * @return The name of the file to which information will be emitted
	  */
    [[nodiscard]] std::string getFileName() const {
        return file_name_;
    }

    /***************************************************************************/
    /**
	  * @brief Allows to set the canvas label
	  *
	  * @param canvas_label The label to assign to the canvas
	  */
    void setCanvasLabel(const std::string &canvas_label) {
        canvas_label_ = canvas_label;
    }

    /***************************************************************************/
    /**
	  * @brief Allows to retrieve the canvas label
	  *
	  * @return The current canvas label
	  */
    [[nodiscard]] std::string getCanvasLabel() const {
        return canvas_label_;
    }

    /***************************************************************************/
    /**
	  * @brief Determines a suitable label for a given parPropSpec value
	  *
	  * @param s A parameter-property specification whose variable descriptor is turned into a label
	  * @return A human-readable label string for the given variable
	  */
    [[nodiscard]] std::string getLabel(const gen::parPropSpec<fp_type> &s) const {
        // All monitored parameters are addressed positionally (the former by-name addressing
        // modes have been removed).
        const std::size_t var_pos = std::get<2>(s.var);
        return std::string("variable id ") + Gem::Common::to_string(var_pos);
    }

protected:
    /************************************************************************/
    // load_(), compare_(), name_() and clone_() are generated by the
    // Gem::Common::GReflectiveInterfaceT base from class_name and localMembers_()
    // (fp_prof_var_vec_ is now folded into localMembers_(), so no manual tail remains).

    /***************************************************************************/
    /**
     * Applies modifications to this object. This is needed for testing purposes
     *
     * @return A boolean which indicates whether modifications were made
     */
    bool modify_GUnitTests_() override {
#ifdef GEM_TESTING

        bool result = false;

        // Call the parent classes' functions
        if(oa::GBasePluggableOM::modify_GUnitTests_()) {
            result = true;
        }

        // no local data -- nothing to change

        return result;

#else /* GEM_TESTING */ // If this function is called when GEM_TESTING isn't set, throw
        Gem::Common::condnotset("GProgressPlotterT<fp_type>::modify_GUnitTests", "GEM_TESTING");
        return false;
#endif                  /* GEM_TESTING */
    }

    /***************************************************************************/
    /**
     * Performs self tests that are expected to succeed. This is needed for testing purposes
     */
    void specificTestsNoFailureExpected_GUnitTests_() override {
#ifdef GEM_TESTING

        // Call the parent classes' functions
        oa::GBasePluggableOM::specificTestsNoFailureExpected_GUnitTests_();
#else /* GEM_TESTING */ // If this function is called when GEM_TESTING isn't set, throw
        Gem::Common::condnotset(
            "GProgressPlotterT<fp_type>::specificTestsNoFailureExpected_GUnitTests",
            "GEM_TESTING"
        );
#endif                  /* GEM_TESTING */
    }

    /***************************************************************************/
    /**
     * Performs self tests that are expected to fail. This is needed for testing purposes
     */
    void specificTestsFailuresExpected_GUnitTests_() override {
#ifdef GEM_TESTING

        // Call the parent classes' functions
        oa::GBasePluggableOM::specificTestsFailuresExpected_GUnitTests_();

#else /* GEM_TESTING */ // If this function is called when GEM_TESTING isn't set, throw
        Gem::Common::condnotset(
            "GProgressPlotterT<fp_type>::specificTestsFailuresExpected_GUnitTests",
            "GEM_TESTING"
        );
#endif                  /* GEM_TESTING */
    }
    /***************************************************************************/

private:
    /***************************************************************************/
    /**
     * @brief Allows to emit information in different stages of the information cycle
     * (initialization, during each cycle and during finalization)
     *
     * @param im The information mode (initialization, processing or finalization) for this call
     * @param goa A constant pointer to the optimization algorithm whose state is being monitored
     */
    // NOLINTNEXTLINE(readability-function-size) -- switch-driven dispatcher over infoMode (INFOINIT/INFOPROCESSING/INFOEND) for GProgressPlotterT; each case is a self-contained stage of the same plot lifecycle
    void informationFunction_(infoMode im, oa::GOptimizationAlgorithmBase const *const goa) override {
        switch(im) {
        case Gem::Geneva::infoMode::INFOINIT: {
            // Build a fresh data log for this run and DECLARE the series (its plot choice)
            // -- no plotter objects are created here; the data is pushed in INFOPROCESSING
            // and the plotters are materialized only at INFOEND via GDataLog.
            data_log_.emplace(canvas_label_, 1, 1);
            have_series_ = true;
            switch(this->nProfileVars()) {
            case 1: {
                Gem::Dietrich::GPlotSpec spec(Gem::Dietrich::plotKind::graph_2d);
                spec.plot_mode = Gem::Dietrich::graphPlotMode::CURVE;
                spec.name = "Fitness as a function of a parameter value";
                spec.x_label = this->getLabel(fp_prof_var_vec_[0]);
                spec.y_label = "Fitness";
                spec.columns = {"x", "y"};
                active_series_ = data_log_->declareSeries(spec);
            } break;
            case 2: {
                Gem::Dietrich::GPlotSpec spec(Gem::Dietrich::plotKind::graph_3d);
                spec.name = "Fitness as a function of parameter values";
                spec.x_label = this->getLabel(fp_prof_var_vec_[0]);
                spec.y_label = this->getLabel(fp_prof_var_vec_[1]);
                spec.z_label = "Fitness";
                spec.columns = {"x", "y", "z"};
                active_series_ = data_log_->declareSeries(spec);
            } break;

            case 3: {
                Gem::Dietrich::GPlotSpec spec(Gem::Dietrich::plotKind::graph_4d);
                spec.name = "Fitness (color-coded) as a function of parameter values";
                spec.x_label = this->getLabel(fp_prof_var_vec_[0]);
                spec.y_label = this->getLabel(fp_prof_var_vec_[1]);
                spec.z_label = this->getLabel(fp_prof_var_vec_[2]);
                spec.columns = {"x", "y", "z", "w"};
                active_series_ = data_log_->declareSeries(spec);
            } break;

            default: {
                // Too many profiling dimensions to display: no series is declared (an
                // empty canvas is still written at INFOEND, as before).
                have_series_ = false;
                glogger << "NOTE: In "
                           "GProgressPlotterT<fp_type>::informationFunction_(infoMode::INFOINIT):"
                        << '\n'
                        << "Number of profiling dimensions " << this->nProfileVars()
                        << " can not be displayed." << '\n'
                        << "No graphical output will be created." << '\n'
                        << GLOGGING;
            } break;
            }

            data_log_->setCanvasDimensions(
                std::get<0>(canvas_dimensions_),
                std::get<1>(canvas_dimensions_)
            );
        } break;

        case Gem::Geneva::infoMode::INFOPROCESSING: {
            if(monitor_best_only_) { // Monitor the best individual only
                std::shared_ptr<gen::GOptimizableEntity> const p =
                    goa->Interface::GOptimizerIT<oa::GOptimizationAlgorithmBase>::getBestGlobalIndividual<gen::GOptimizableEntity>();
                this->logIndividual_(*p);
            }
            else { // Monitor all individuals
                for(const auto &ind_ptr : *goa) {
                    this->logIndividual_(*ind_ptr);
                }
            }
        } break;

        case Gem::Geneva::infoMode::INFOEND: {
            if(data_log_.has_value()) {
                // Make sure 1-D data is sorted (the GGraph2D::sortX() equivalent).
                if(have_series_ && 1 == this->nProfileVars()) {
                    data_log_->sortByFirstColumn(active_series_);
                }

                // Inform the plot designer whether it should print png files, then write.
                data_log_->setAddPrintCommand(add_print_command_);
                data_log_->writeToFile(file_name_);
            }

            // Drop the transient run state.
            data_log_.reset();
        } break;
        };
    }

    /************************************************************************/
    /**
     * @brief Logs one individual's profiled variables (plus its primary fitness) into the active
     * series, applying the validity and boundary filters. Shared by the best-only and
     * all-individuals monitoring paths (formerly two copies of a per-dimension switch, each
     * duplicated for the boundary filter).
     *
     * @param ind The individual whose profiled variables are logged
     */
    void logIndividual_(gen::GOptimizableEntity &ind) {
        const double primary_fitness = oa::GBasePluggableOM::use_raw_evaluation_
            ? ind.raw_fitness(0)
            : ind.transformed_fitness(0);

        if(monitor_valid_only_ && not ind.isValid()) {
            return;
        }

        const std::size_t n_vars = this->nProfileVars();
        if(n_vars < 1 || n_vars > 3) {
            return; // too many profiling dimensions: nothing is logged (no series was declared)
        }

        // Read the profiled values; with the boundary filter on, an individual outside any
        // observed window is not logged at all.
        std::array<double, 3> vals{};
        for(std::size_t i = 0; i < n_vars; ++i) {
            const auto v = ind.GOptimizableEntity::template getVarVal<fp_type>(fp_prof_var_vec_[i].var);
            if(observe_boundaries_ &&
               (v < fp_prof_var_vec_[i].lowerBoundary || v > fp_prof_var_vec_[i].upperBoundary)) {
                return;
            }
            vals[i] = double(v);
        }

        // The data log is created in INFOINIT, which the monitor contract runs before any
        // per-iteration call arrives here.
        // NOLINTNEXTLINE(bugprone-unchecked-optional-access)
        auto &data_log = *data_log_;

        switch(n_vars) {
        case 1:
            data_log.append(active_series_, vals[0], primary_fitness);
            break;
        case 2:
            data_log.append(
                active_series_,
                std::tuple<double, double, double>(vals[0], vals[1], primary_fitness)
            );
            break;
        case 3:
            data_log.append(
                active_series_,
                std::tuple<double, double, double, double>(vals[0], vals[1], vals[2], primary_fitness)
            );
            break;
        default:
            break;
        }
    }

    /************************************************************************/

    std::vector<gen::parPropSpec<fp_type>>
        fp_prof_var_vec_; ///< Holds information about variables to be profiled

    std::string canvas_label_ = std::string(
        "Progress information"
    ); ///< The canvas title (was held by the former GPlotDesigner member)

    // Transient run state: the data log is built in INFOINIT, filled in INFOPROCESSING and
    // realized + written in INFOEND. It is NOT part of the monitor's serialized config.
    std::optional<Gem::Dietrich::GDataLog> data_log_;
    Gem::Dietrich::GDataLog::SeriesId active_series_ = 0; ///< the series declared for this run
    bool have_series_ = false; ///< whether a renderable series was declared (nProfileVars 1..3)

    std::string file_name_ = std::string(
        "progressScan.C"
    ); ///< The name of the file the output should be written to.
    std::tuple<std::uint32_t, std::uint32_t> canvas_dimensions_ =
        std::tuple<std::uint32_t, std::uint32_t>(1024, 768); ///< The dimensions of the canvas

    bool monitor_best_only_ =
        false; ///< Indicates whether only the best individuals should be monitored
    bool monitor_valid_only_ = false; ///< Indicates whether only valid individuals should be plotted
    bool observe_boundaries_ =
        false; ///< When set to true, the plotter will ignore values outside of a scan boundary

    bool add_print_command_ =
        false; ///< Asks the GPlotDesigner to add a print command to result files
};

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * This class allows to log all candidate solutions found to a file, including the parameetr
 * values. NOTE that the file may become very large! Results are output in the following format:
 * param1 param2 ... param_m eval1 eval2 ... eval_n . By default, no commas and
 * explanations are printed. If with_name_and_type is set to true, the values are
 * prepended by a line with variable names and types. If with_commas is set to true,
 * commas will be printed in-between values. It is possible to filter the results by
 * asking the class to only log solutions better than a given set of values. What
 * is considered better depends on whether evaluation criteria are maximized or minimized
 * and is determined from the individual. Note that this class operates on the
 * GOptimizableEntity hierarchy (the flat-genome GGenome / its GenomeData), i.e. on
 * the optimizable entities managed by the algorithm.
 */
class GAllSolutionFileLogger // NOLINT(cppcoreguidelines-special-member-functions)
  : public Gem::Common::GReflectiveInterfaceT<GAllSolutionFileLogger, oa::GBasePluggableOM> {
    ///////////////////////////////////////////////////////////////////////
    friend class boost::serialization::access;
    friend struct Gem::Common::GReflectiveInterfaceAccess;

    /***************************************************************************/
    /**
     * Single declaration of this class'es local data members, driving the
     * GReflectiveInterfaceT-generated serialize(), load_() and compare_() from one place. All members are plain
     * config values (make_member); no manual tail is needed.
     */
    template <typename Self>
    auto localMembers_(this Self &self) {
        return std::make_tuple(
            Gem::Common::make_member("file_name_", self.file_name_),
            Gem::Common::make_member("boundaries_", self.boundaries_),
            Gem::Common::make_member("boundaries_active_", self.boundaries_active_),
            Gem::Common::make_member("with_name_and_type_", self.with_name_and_type_),
            Gem::Common::make_member("with_commas_", self.with_commas_),
            Gem::Common::make_member("use_raw_fitness_", self.use_raw_fitness_),
            Gem::Common::make_member("show_validity_", self.show_validity_),
            Gem::Common::make_member("print_initial_", self.print_initial_),
            Gem::Common::make_member("show_iteration_boundaries_", self.show_iteration_boundaries_)
        );
    }

    ///////////////////////////////////////////////////////////////////////

public:
    /** @brief The class name, consumed by the GReflectiveInterfaceT-generated name_() / compare token. */
    static constexpr std::string_view class_name = "GAllSolutionFileLogger";

    /***************************************************************************/

    /** @brief The default constructor */
    GAllSolutionFileLogger() = default;
    /**
     * @brief Initialization with a file name
     * @param file_name The name of the file to which solutions should be logged
     */
    explicit GAllSolutionFileLogger(const std::string &file_name);
    /**
     * @brief Initialization with a file name and boundaries
     * @param file_name The name of the file to which solutions should be logged
     * @param boundaries Value boundaries used to filter which solutions are logged
     */
    GAllSolutionFileLogger(const std::string &file_name, const std::vector<double> &boundaries);
    /** @brief The copy constructor */
    GAllSolutionFileLogger(const GAllSolutionFileLogger &cp) = default;
    /** @brief The destructor */
    ~GAllSolutionFileLogger() override = default;

    /**
     * @brief Sets the file name
     * @param file_name The name of the file to which solutions should be logged
     */
    void setFileName(const std::string &file_name);
    /**
     * @brief Retrieves the current file name
     * @return The name of the file to which solutions are logged
     */
    [[nodiscard]] std::string getFileName() const;

    /**
     * @brief Sets the boundaries
     * @param boundaries Value boundaries used to filter which solutions are logged
     */
    void setBoundaries(const std::vector<double> &boundaries);
    /**
     * @brief Allows to retrieve the boundaries
     * @return The value boundaries used to filter which solutions are logged
     */
    [[nodiscard]] std::vector<double> getBoundaries() const;
    /**
     * @brief Allows to check whether boundaries are active
     * @return true if boundaries have been set and are active, false otherwise
     */
    [[nodiscard]] bool boundariesActive() const;
    /** @brief Allows to inactivate boundaries */
    void setBoundariesInactive();

    /**
     * @brief Allows to specify whether explanations should be printed for parameter- and fitness values.
     * @param with_name_and_type If true, a header line with variable names and types is prepended
     */
    void setPrintWithNameAndType(bool with_name_and_type = true);
    /**
     * @brief Allows to check whether explanations should be printed for parameter-and fitness values
     * @return true if a header line with variable names and types is prepended, false otherwise
     */
    [[nodiscard]] bool getPrintWithNameAndType() const;

    /**
     * @brief Allows to specify whether commas should be printed in-between values
     * @param with_commas If true, commas are printed in-between values
     */
    void setPrintWithCommas(bool with_commas = true);
    /**
     * @brief Allows to check whether commas should be printed in-between values
     * @return true if commas are printed in-between values, false otherwise
     */
    [[nodiscard]] bool getPrintWithCommas() const;

    /**
     * @brief Allows to specify whether the true (instead of the transformed) fitness should be shown
     * @param use_raw_fitness If true, the raw (true) fitness is shown instead of the transformed fitness
     */
    void setUseTrueFitness(bool use_raw_fitness = true);
    /**
     * @brief Allows to retrieve whether the true (instead of the transformed) fitness should be shown
     * @return true if the raw (true) fitness is shown, false if the transformed fitness is shown
     */
    [[nodiscard]] bool getUseTrueFitness() const;

    /**
     * @brief Allows to specify whether the validity of a solution should be shown
     * @param show_validity If true, the validity of each solution is shown
     */
    void setShowValidity(bool show_validity = true);
    /**
     * @brief Allows to check whether the validity of a solution will be shown
     * @return true if the validity of each solution is shown, false otherwise
     */
    [[nodiscard]] bool getShowValidity() const;

    /**
     * @brief Allows to specify whether the initial population should be printed.
     * @param print_initial If true, the initial population is also printed
     */
    void setPrintInitial(bool print_initial = true);
    /**
     * @brief Allows to check whether the initial population should be printed.
     * @return true if the initial population is printed, false otherwise
     */
    [[nodiscard]] bool getPrintInitial() const;

    /**
     * @brief Allows to specify whether a comment line should be inserted between iterations
     * @param show_iteration_boundaries If true, a comment line is inserted between iterations
     */
    void setShowIterationBoundaries(bool show_iteration_boundaries = true);
    /**
     * @brief Allows to check whether a comment line should be inserted between iterations
     * @return true if a comment line is inserted between iterations, false otherwise
     */
    [[nodiscard]] bool getShowIterationBoundaries() const;

protected:
    /************************************************************************/

    // load_(), compare_(), name_() and clone_() are generated by the
    // Gem::Common::GReflectiveInterfaceT base from class_name and localMembers_().

    /** @brief Applies modifications to this object */
    bool modify_GUnitTests_() override;
    /** @brief Performs self tests that are expected to succeed */
    void specificTestsNoFailureExpected_GUnitTests_() override;
    /** @brief Performs self tests that are expected to fail */
    void specificTestsFailuresExpected_GUnitTests_() override;

private:
    /**
     * @brief Allows to emit information in different stages of the information cycle
     *
     * The first (unnamed) argument is the information mode (init, processing or finalization).
     * @param goa A constant pointer to the optimization algorithm whose state is being monitored
     */
    void
    informationFunction_(infoMode im, oa::GOptimizationAlgorithmBase const *const goa) override;

    /**
     * @brief Does the actual printing of the population to the log file
     * @param iteration_description A textual description of the current iteration, used in the output
     * @param goa A constant pointer to the optimization algorithm whose population is printed
     */
    void printPopulation(
        const std::string &iteration_description,
        oa::GOptimizationAlgorithmBase const *const goa
    );

    /***************************************************************************/
    // Data

    std::string file_name_ =
        "CompleteSolutionLog.txt";    ///< The name of the file to which solutions should be stored
    std::vector<double> boundaries_; ///< Value boundaries used to filter logged solutions
    bool boundaries_active_ = false;  ///< Set to true if boundaries have been set
    bool with_name_and_type_ = false;   ///< When set to true, explanations for values are printed
    bool with_commas_ = false; ///< When set to true, commas will be printed in-between values
    bool use_raw_fitness_ =
        true;                   ///< Indicates whether true- or transformed fitness should be output
    bool show_validity_ = true; ///< Indicates whether the validity of a solution should be shown
    bool print_initial_ = false; ///< Indicates whether the initial population should be printed
    bool show_iteration_boundaries_ =
        false; ///< Indicates whether a comment indicating the end of an iteration should be printed
};

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * This class prints out all evaluations of each iteration. The format is
 * eval0_0, eval0_1, ... ,eval0_n, ..., evalm_0, evalm_1, ... ,evalm_n
 */
class GIterationResultsFileLogger // NOLINT(cppcoreguidelines-special-member-functions)
  : public Gem::Common::GReflectiveInterfaceT<GIterationResultsFileLogger, oa::GBasePluggableOM> {
    ///////////////////////////////////////////////////////////////////////
    friend class boost::serialization::access;
    friend struct Gem::Common::GReflectiveInterfaceAccess;

    /***************************************************************************/
    /**
     * Single declaration of this class'es local data members, driving
     * serialize(), load_() and compare_() from one place. All members are plain
     * config values (make_member); no manual tail is needed.
     */
    template <typename Self>
    auto localMembers_(this Self &self) {
        return std::make_tuple(
            Gem::Common::make_member("file_name_", self.file_name_),
            Gem::Common::make_member("with_commas_", self.with_commas_),
            Gem::Common::make_member("use_raw_fitness_", self.use_raw_fitness_)
        );
    }

    ///////////////////////////////////////////////////////////////////////

public:
    /** @brief The class name, consumed by the GReflectiveInterfaceT-generated name_() / compare token. */
    static constexpr std::string_view class_name = "GIterationResultsFileLogger";

    /***************************************************************************/

    /** @brief The default constructor */
    GIterationResultsFileLogger() = default;
    /**
     * @brief Initialization with a file name
     * @param file_name The name of the file to which iteration results should be logged
     */
    explicit GIterationResultsFileLogger(const std::string &file_name);
    /** @brief The copy constructor */
    GIterationResultsFileLogger(const GIterationResultsFileLogger &cp) = default;
    /** @brief The destructor */
    ~GIterationResultsFileLogger() override = default;

    /**
     * @brief Sets the file name
     * @param file_name The name of the file to which iteration results should be logged
     */
    void setFileName(const std::string &file_name);
    /**
     * @brief Retrieves the current file name
     * @return The name of the file to which iteration results are logged
     */
    [[nodiscard]] std::string getFileName() const;

    /**
     * @brief Allows to specify whether commas should be printed in-between values
     * @param with_commas If true, commas are printed in-between values
     */
    void setPrintWithCommas(bool with_commas);
    /**
     * @brief Allows to check whether commas should be printed in-between values
     * @return true if commas are printed in-between values, false otherwise
     */
    [[nodiscard]] bool getPrintWithCommas() const;

    /**
     * @brief Allows to specify whether the true (instead of the transformed) fitness should be shown
     * @param use_raw_fitness If true, the raw (true) fitness is shown instead of the transformed fitness
     */
    void setUseTrueFitness(bool use_raw_fitness);
    /**
     * @brief Allows to retrieve whether the true (instead of the transformed) fitness should be shown
     * @return true if the raw (true) fitness is shown, false if the transformed fitness is shown
     */
    [[nodiscard]] bool getUseTrueFitness() const;

protected:
    /************************************************************************/
    /**
     * @brief Loads the data of another object into this one
     * @param cp A pointer to another object of this type, camouflaged as a GBasePluggableOM, whose data is copied
     */
    // load_(), compare_(), name_() and clone_() are generated by the
    // Gem::Common::GReflectiveInterfaceT base from class_name and localMembers_().

    /** @brief Applies modifications to this object */
    bool modify_GUnitTests_() override;
    /** @brief Performs self tests that are expected to succeed */
    void specificTestsNoFailureExpected_GUnitTests_() override;
    /** @brief Performs self tests that are expected to fail. This is needed for testing purposes */
    void specificTestsFailuresExpected_GUnitTests_() override;

private:

    /**
     * @brief Allows to emit information in different stages of the information cycle
     *
     * The first (unnamed) argument is the information mode (init, processing or finalization).
     * @param goa A constant pointer to the optimization algorithm whose state is being monitored
     */
    void
    informationFunction_(infoMode im, oa::GOptimizationAlgorithmBase const *const goa) override;

    std::string file_name_ =
        "IterationResultsLog.txt"; ///< The name of the file to which solutions should be stored
    bool with_commas_ = true;      ///< When set to true, commas will be printed in-between values
    bool use_raw_fitness_ =
        false; ///< Indicates whether true- or transformed fitness should be output
};

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * This class allows to log the number of adaptions made inside of adaptors
 * to a file. This is mostly needed for debugging and profiling purposes. The
 * number of adaptions made is a good measure for the adaption probability.
 */
class GNAdpationsLogger // NOLINT(cppcoreguidelines-special-member-functions)
  : public Gem::Common::GReflectiveInterfaceT<GNAdpationsLogger, oa::GBasePluggableOM> {
    ///////////////////////////////////////////////////////////////////////
    friend class boost::serialization::access;
    friend struct Gem::Common::GReflectiveInterfaceAccess;

    /***************************************************************************/
    /**
     * Single declaration of this class'es local data members, driving
     * serialize(), load_() and compare_() from one place. All members are
     * plain CONFIG/DATA (make_member); the plotters are no longer state -- they
     * are materialized into a local GDataLog at INFOEND from the accumulated
     * n_adaptions_store_ / fitness_store_ vectors. No manual tail is needed.
     */
    template <typename Self>
    auto localMembers_(this Self &self) {
        return std::make_tuple(
            Gem::Common::make_member("file_name_", self.file_name_),
            Gem::Common::make_member("canvas_dimensions_", self.canvas_dimensions_),
            Gem::Common::make_member("monitor_best_only_", self.monitor_best_only_),
            Gem::Common::make_member("add_print_command_", self.add_print_command_),
            Gem::Common::make_member("max_iteration_", self.max_iteration_),
            Gem::Common::make_member("n_iterations_recorded_", self.n_iterations_recorded_),
            Gem::Common::make_member("n_adaptions_store_", self.n_adaptions_store_),
            Gem::Common::make_member("fitness_store_", self.fitness_store_)
        );
    }

    ///////////////////////////////////////////////////////////////////////

public:
    /** @brief The class name, consumed by the GReflectiveInterfaceT-generated name_() / compare token. */
    static constexpr std::string_view class_name = "GNAdpationsLogger";

    /***************************************************************************/

    /** @brief The default constructor */
    GNAdpationsLogger() = default;
    /**
     * @brief Initialization with a file name
     * @param file_name The name of the file to which the number of adaptions should be logged
     */
    explicit GNAdpationsLogger(const std::string &file_name);
    /**
     * @brief The copy constructor
     * @param cp A constant reference to another GNAdpationsLogger object whose data is deep-copied
     */
    GNAdpationsLogger(const GNAdpationsLogger &cp);
    /** @brief The destructor */
    ~GNAdpationsLogger() override = default;

    /**
     * @brief Sets the file name
     * @param file_name The name of the file to which the number of adaptions should be logged
     */
    void setFileName(const std::string &file_name);
    /**
     * @brief Retrieves the current file name
     * @return The name of the file to which the number of adaptions is logged
     */
    [[nodiscard]] std::string getFileName() const;

    /**
     * @brief Allows to specify whether only the best individuals should be monitored
     * @param monitor_best_only If true, only the best individual(s) of the population are monitored
     */
    void setMonitorBestOnly(bool monitor_best_only = true);
    /**
     * @brief Allows to check whether only the best individuals should be monitored
     * @return true if only the best individual(s) are monitored, false otherwise
     */
    [[nodiscard]] bool getMonitorBestOnly() const;

    /**
     * @brief Allows to set the canvas dimensions
     * @param canvas_dimensions A tuple holding the canvas dimensions in x- and y-direction
     */
    void setCanvasDimensions(std::tuple<std::uint32_t, std::uint32_t> canvas_dimensions);
    /**
     * @brief Allows to set the canvas dimensions using separate x and y values
     * @param x The canvas dimension in x-direction
     * @param y The canvas dimension in y-direction
     */
    void setCanvasDimensions(std::uint32_t x, std::uint32_t y);
    /**
     * @brief Gives access to the canvas dimensions
     * @return A tuple holding the canvas dimensions in x- and y-direction
     */
    [[nodiscard]] std::tuple<std::uint32_t, std::uint32_t> getCanvasDimensions() const;

    /**
     * @brief Allows to add a "Print" command to the end of the script so that picture files are created
     * @param add_print_command If true, a print command is appended so that picture files are created
     */
    void setAddPrintCommand(bool add_print_command);
    /**
     * @brief Allows to retrieve the current value of the add_print_command_ variable
     * @return true if a print command will be appended to the script, false otherwise
     */
    [[nodiscard]] bool getAddPrintCommand() const;

protected:
    /************************************************************************/

    /**
     * @brief Loads the data of another object into this one
     * @param cp A pointer to another object of this type, camouflaged as a GBasePluggableOM, whose data is copied
     */
    // load_(), compare_(), name_() and clone_() are generated by the
    // Gem::Common::GReflectiveInterfaceT base from class_name and localMembers_().

    /** @brief Applies modifications to this object */
    bool modify_GUnitTests_() override;
    /** @brief Performs self tests that are expected to succeed */
    void specificTestsNoFailureExpected_GUnitTests_() override;
    /** @brief Performs self tests that are expected to fail. This is needed for testing purposes */
    void specificTestsFailuresExpected_GUnitTests_() override;

private:

    /**
     * @brief Allows to emit information in different stages of the information cycle
     *
     * The first (unnamed) argument is the information mode (init, processing or finalization).
     * @param goa A constant pointer to the optimization algorithm whose state is being monitored
     */
    void
    informationFunction_(infoMode im, oa::GOptimizationAlgorithmBase const *const goa) override;

    std::string file_name_ =
        "NAdaptions.C"; ///< The name of the file to which solutions should be stored

    std::tuple<std::uint32_t, std::uint32_t> canvas_dimensions_ =
        std::tuple<std::uint32_t, std::uint32_t>(1200, 1600); ///< The dimensions of the canvas

    bool monitor_best_only_ =
        false; ///< Indicates whether only the best individuals should be monitored
    bool add_print_command_ =
        false; ///< Asks the GPlotDesigner to add a print command to result files

    std::size_t max_iteration_ = 0; ///< Holds the largest iteration recorded for the algorithm
    std::size_t n_iterations_recorded_ =
        0; ///< Holds the number of iterations that were recorded (not necessarily == max_iteration_

    std::vector<std::tuple<double, double>>
        n_adaptions_store_; ///< Holds all (iteration, n-adaptions) data points
    std::vector<std::tuple<double, double>>
        fitness_store_; ///< Holds all (iteration, best-fitness) data points for the current run
};

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * This class allows to log chosen properties of adaptors. Such properties
 * are limited to numeric entities, that may be converted to double
 *
 * @tparam num_type The arithmetic type of the logged adaptor property (convertible to double)
 */
template <typename num_type>
class GAdaptorPropertyLoggerT // NOLINT(cppcoreguidelines-special-member-functions)
  : public Gem::Common::GReflectiveInterfaceT<GAdaptorPropertyLoggerT<num_type>, oa::GBasePluggableOM> {
    ///////////////////////////////////////////////////////////////////////
    friend class boost::serialization::access;
    friend struct Gem::Common::GReflectiveInterfaceAccess;

    /***************************************************************************/
    /**
     * Single declaration of this class'es local data members, driving
     * serialize(), load_() and compare_() from one place. All members are
     * plain CONFIG/DATA (make_member); the plotters are no longer state -- they
     * are materialized into a local GDataLog at INFOEND from the accumulated
     * adaptor_property_store_ / fitness_store_ vectors. No manual tail is needed.
     */
    template <typename Self>
    auto localMembers_(this Self &self) {
        return std::make_tuple(
            Gem::Common::make_member("file_name_", self.file_name_),
            Gem::Common::make_member("adaptor_name_", self.adaptor_name_),
            Gem::Common::make_member("property_", self.property_),
            Gem::Common::make_member("canvas_dimensions_", self.canvas_dimensions_),
            Gem::Common::make_member("monitor_best_only_", self.monitor_best_only_),
            Gem::Common::make_member("add_print_command_", self.add_print_command_),
            Gem::Common::make_member("max_iteration_", self.max_iteration_),
            Gem::Common::make_member("n_iterations_recorded_", self.n_iterations_recorded_),
            Gem::Common::make_member("adaptor_property_store_", self.adaptor_property_store_),
            Gem::Common::make_member("fitness_store_", self.fitness_store_)
        );
    }

    ///////////////////////////////////////////////////////////////////////

    static_assert(std::is_arithmetic_v<num_type>, "num_type should be an arithmetic type");

public:
    /** @brief The class name, consumed by the GReflectiveInterfaceT-generated name_() / compare token. */
    static constexpr std::string_view class_name = "GAdaptorPropertyLoggerT";

    /***************************************************************************/
    /**
	  * The default constructor. Note that some parmeters may be initialized in
	  * the class body.
	  */
    GAdaptorPropertyLoggerT() = default;

    /***************************************************************************/
    /**
	  * @brief Initialization with a file name, adaptor name and property name
	  *
	  * @param file_name The name of the file the logged property should be written to
	  * @param adaptor_name The name of the adaptor whose property should be logged
	  * @param property The name of the property to be logged (e.g. "sigma")
	  */
    GAdaptorPropertyLoggerT(std::string file_name, std::string adaptor_name, std::string property)
      : file_name_(std::move(file_name))
      , adaptor_name_(std::move(adaptor_name))
      , property_(std::move(property))
      , canvas_dimensions_(std::tuple<std::uint32_t, std::uint32_t>(1200, 1600)) { /* nothing */
    }

    /***************************************************************************/
    /**
	  * @brief The copy constructor
	  *
	  * @param cp A constant reference to another GAdaptorPropertyLoggerT object whose data is deep-copied
	  */
    GAdaptorPropertyLoggerT(const GAdaptorPropertyLoggerT<num_type> &cp)
      : Gem::Common::GReflectiveInterfaceT<GAdaptorPropertyLoggerT<num_type>, oa::GBasePluggableOM>(cp)
      , file_name_(cp.file_name_)
      , adaptor_name_(cp.adaptor_name_)
      , property_(cp.property_)
      , canvas_dimensions_(cp.canvas_dimensions_)
      , monitor_best_only_(cp.monitor_best_only_)
      , add_print_command_(cp.add_print_command_)
      , max_iteration_(cp.max_iteration_)
      , n_iterations_recorded_(cp.n_iterations_recorded_)
      , adaptor_property_store_(cp.adaptor_property_store_)
      , fitness_store_(cp.fitness_store_) { /* nothing -- the plotters are no longer state */
    }

    /***************************************************************************/
    /**
	  * The destructor
	  */
    ~GAdaptorPropertyLoggerT() override = default;

    /***************************************************************************/
    /**
	  * @brief Sets the file name
	  *
	  * @param file_name The name of the file the logged property should be written to
	  */
    void setFileName(const std::string &file_name) {
        file_name_ = file_name;
    }

    /***************************************************************************/
    /**
	  * @brief Retrieves the current file name
	  *
	  * @return The name of the file the logged property is written to
	  */
    [[nodiscard]] std::string getFileName() const {
        return file_name_;
    }

    /***************************************************************************/
    /**
	  * @brief Sets the name of the adaptor
	  *
	  * @param adaptor_name The name of the adaptor whose property should be logged
	  */
    void setAdaptorName(std::string adaptor_name) {
        adaptor_name_ = std::move(adaptor_name);
    }

    /***************************************************************************/
    /**
	  * @brief Retrieves the name of the adaptor
	  *
	  * @return The name of the adaptor whose property is logged
	  */
    [[nodiscard]] std::string getAdaptorName() const {
        return adaptor_name_;
    }

    /***************************************************************************/
    /**
	  * @brief Sets the name of the property
	  *
	  * @param property The name of the property to be logged (e.g. "sigma")
	  */
    void setPropertyName(std::string property) {
        property_ = std::move(property);
    }

    /***************************************************************************/
    /**
	  * @brief Retrieves the name of the property
	  *
	  * @return The name of the property being logged
	  */
    [[nodiscard]] std::string getPropertyName() const {
        return property_;
    }

    /***************************************************************************/
    /**
	  * @brief Allows to specify whether only the best individuals should be monitored.
	  *
	  * @param monitor_best_only If true, only the best individual(s) of the population are monitored
	  */
    void setMonitorBestOnly(bool monitor_best_only = true) {
        monitor_best_only_ = monitor_best_only;
    }

    /***************************************************************************/
    /**
	  * @brief Allows to check whether only the best individuals should be monitored.
	  *
	  * @return true if only the best individual(s) are monitored, false otherwise
	  */
    [[nodiscard]] bool getMonitorBestOnly() const {
        return monitor_best_only_;
    }

    /***************************************************************************/
    /**
	  * @brief Allows to set the canvas dimensions
	  *
	  * @param canvas_dimensions A tuple holding the canvas dimensions in x- and y-direction
	  */
    void setCanvasDimensions(std::tuple<std::uint32_t, std::uint32_t> canvas_dimensions) {
        canvas_dimensions_ = canvas_dimensions;
    }

    /***************************************************************************/
    /**
	  * @brief Allows to set the canvas dimensions using separate x and y values
	  *
	  * @param x The canvas dimension in x-direction
	  * @param y The canvas dimension in y-direction
	  */
    void setCanvasDimensions(std::uint32_t x, std::uint32_t y) {
        canvas_dimensions_ = std::tuple<std::uint32_t, std::uint32_t>(x, y);
    }

    /***************************************************************************/
    /**
	  * @brief Gives access to the canvas dimensions
	  *
	  * @return A tuple holding the canvas dimensions in x- and y-direction
	  */
    [[nodiscard]] std::tuple<std::uint32_t, std::uint32_t> getCanvasDimensions() const {
        return canvas_dimensions_;
    }

    /******************************************************************************/
    /**
	  * @brief Allows to add a "Print" command to the end of the script so that picture files are created
	  *
	  * @param add_print_command If true, a print command is appended so that picture files are created
	  */
    void setAddPrintCommand(bool add_print_command) {
        add_print_command_ = add_print_command;
    }

    /******************************************************************************/
    /**
	  * @brief Allows to retrieve the current value of the add_print_command_ variable
	  *
	  * @return true if a print command will be appended to the script, false otherwise
	  */
    [[nodiscard]] bool getAddPrintCommand() const {
        return add_print_command_;
    }

protected:
    // load_(), compare_(), name_() and clone_() are generated by the
    // Gem::Common::GReflectiveInterfaceT base from class_name and localMembers_().

    /***************************************************************************/
    /**
     * Applies modifications to this object. This is needed for testing purposes
     *
     * @return A boolean which indicates whether modifications were made
     */
    bool modify_GUnitTests_() override {
#ifdef GEM_TESTING

        bool result = false;

        // Call the parent classes' functions
        if(oa::GBasePluggableOM::modify_GUnitTests_()) {
            result = true;
        }

        // no local data -- nothing to change

        return result;

#else /* GEM_TESTING */ // If this function is called when GEM_TESTING isn't set, throw
        Gem::Common::condnotset(
            "GAdaptorPropertyLoggerT<num_type>::modify_GUnitTests",
            "GEM_TESTING"
        );
        return false;
#endif                  /* GEM_TESTING */
    }

    /***************************************************************************/
    /**
     * Performs self tests that are expected to succeed. This is needed for testing purposes
     */
    void specificTestsNoFailureExpected_GUnitTests_() override {
#ifdef GEM_TESTING

        // Call the parent classes' functions
        oa::GBasePluggableOM::specificTestsNoFailureExpected_GUnitTests_();
#else /* GEM_TESTING */ // If this function is called when GEM_TESTING isn't set, throw
        Gem::Common::condnotset(
            "GAdaptorPropertyLoggerT<num_type>::specificTestsNoFailureExpected_GUnitTests",
            "GEM_TESTING"
        );
#endif                  /* GEM_TESTING */
    }

    /***************************************************************************/
    /**
     * Performs self tests that are expected to fail. This is needed for testing purposes
     */
    void specificTestsFailuresExpected_GUnitTests_() override {
#ifdef GEM_TESTING

        // Call the parent classes' functions
        oa::GBasePluggableOM::specificTestsFailuresExpected_GUnitTests_();

#else /* GEM_TESTING */ // If this function is called when GEM_TESTING isn't set, throw
        Gem::Common::condnotset(
            "GAdaptorPropertyLoggerT<num_type>::specificTestsFailuresExpected_GUnitTests",
            "GEM_TESTING"
        );
#endif                  /* GEM_TESTING */
    }

private:
    /***************************************************************************/
    /**
     * @brief Allows to emit information in different stages of the information cycle
     * (initialization, during each cycle and during finalization)
     *
     * @param im The information mode (initialization, processing or finalization) for this call
     * @param goa A constant pointer to the optimization algorithm whose state is being monitored
     */
    // NOLINTNEXTLINE(readability-function-size) -- switch-driven dispatcher over infoMode (INFOINIT/INFOPROCESSING/INFOEND) for GAdaptorPropertyLoggerT; each case is a self-contained stage of the same log lifecycle
    void informationFunction_(infoMode im, oa::GOptimizationAlgorithmBase const *const goa) override {
        using namespace Gem::Common;
        using namespace Gem::Dietrich; // GDataLog / GPlotSpec / plotKind / graphPlotMode

        switch(im) {
        case Gem::Geneva::infoMode::INFOINIT: {
            // If the file pointed to by file_name_ already exists, make a back-up
            Gem::Common::backupExistingFile(
                file_name_, "GAdaptorPropertyLoggerT::informationFunction_(): Error!"
            );

            // The fitness curve is recorded per-run, so start it fresh (the property store
            // deliberately accumulates across chained algorithms and is not cleared here).
            fitness_store_.clear();
        } break;

        case Gem::Geneva::infoMode::INFOPROCESSING: {
            std::uint32_t const iteration = goa->getIteration();

            // Record the current fitness
            std::shared_ptr<gen::GOptimizableEntity> const p =
                goa->Interface::GOptimizerIT<oa::GOptimizationAlgorithmBase>::getBestGlobalIndividual<gen::GOptimizableEntity>();
            fitness_store_.emplace_back(static_cast<double>(iteration), p->raw_fitness(0));

            // Update the largest known iteration and the number of recorded iterations
            max_iteration_ = iteration;
            n_iterations_recorded_++;

            // Do the actual logging. The per-group adaption state (sigma, …) is OA-owned
            // scratch carried on the individual itself. The live evolving sigma
            // is therefore read from each population slot's scratch via readAdaptionSigmas(). Only the
            // "sigma" property is exposed by the flat genome.
            //
            // NOTE: the "best only" path reads the globally best individual from the OA's archive, which
            // holds pure individual clones detached from any slot, so the live sigma is not available
            // there; it falls back to the configured SEED sigma (a freshly seeded scratch). The "all
            // individuals" path (the data-oriented monitor demo, e.g. example 13) reads the live evolved
            // sigma straight from the population slots.
            // The adaptor settings live on the OA-owned config now (the genome is structure-only), so read
            // it from the algorithm. A non-adapting algorithm returns null and no sigma is logged.
            std::shared_ptr<const oa::GAdaptionConfigBase> const cfg_ptr = goa->getAdaptionConfig();

            if(monitor_best_only_) {
                if(property_ == "sigma" && cfg_ptr) {
                    // The best individual is an off-slot archive clone with no live scratch, so report the
                    // configured SEED sigma read from a freshly seeded scratch.
                    gen::GAuxiliaryStore seed_scratch;
                    cfg_ptr->installInto(seed_scratch);
                    for(double const sigma : oa::readAdaptionSigmas(seed_scratch, *cfg_ptr, adaptor_name_)) {
                        adaptor_property_store_.emplace_back(static_cast<double>(iteration), sigma);
                    }
                }
            }
            else { // Monitor all individuals
                // Loop over all individuals of the algorithm, reading the live adaption state off each
                // slot's OA-owned scratch.
                for(const auto & slot : *goa) {
                    if(property_ == "sigma" && cfg_ptr) {
                        for(double const sigma : oa::readAdaptionSigmas(slot->scratch(), *cfg_ptr, adaptor_name_)) {
                            adaptor_property_store_.emplace_back(static_cast<double>(iteration), sigma);
                        }
                    }
                }
            }
        } break;

        case Gem::Geneva::infoMode::INFOEND: {
            // Within adaptor_property_store_, find the largest property value recorded
            double max_property = 0.;
            for(const auto &property_entry : adaptor_property_store_) {
                max_property = std::max(std::get<1>(property_entry), max_property);
            }

            // Materialize the accumulated data into a fresh data log (no plotter objects are kept
            // as state). The property histogram is declared first and the fitness curve second,
            // matching the former pad order on the 1x2 canvas.
            GDataLog log("Adaptor properties", 1, 2);
            log.setCanvasDimensions(std::get<0>(canvas_dimensions_), std::get<1>(canvas_dimensions_));

            // A fixed-range 2-d histogram (iteration vs. property value). The explicit ranges make
            // makePlotter() rebuild exactly the GHistogram2D the legacy path constructed.
            GPlotSpec spec(plotKind::hist_2d);
            spec.x_label = "Iteration";
            spec.y_label = std::format("Adaptor-Name: {}, Property: {}", adaptor_name_, property_);
            spec.drawing_args = "BOX";
            spec.columns = {"x", "y"};
            spec.n_bins_x = n_iterations_recorded_;
            spec.n_bins_y = 100;
            spec.range_x = std::make_tuple(0., static_cast<double>(max_iteration_));
            spec.range_y = std::make_tuple(0., max_property);
            const auto id = log.declareSeries(spec);
            for(const auto &property_entry : adaptor_property_store_) {
                log.append(id, std::get<0>(property_entry), std::get<1>(property_entry));
            }

            // The best-fitness curve.
            GPlotSpec fitness_spec(plotKind::graph_2d);
            fitness_spec.plot_mode = graphPlotMode::CURVE;
            fitness_spec.x_label = "Iteration";
            fitness_spec.y_label = "Fitness";
            fitness_spec.columns = {"x", "y"};
            const auto fitness_id = log.declareSeries(fitness_spec);
            for(const auto &fitness : fitness_store_) {
                log.append(fitness_id, std::get<0>(fitness), std::get<1>(fitness));
            }

            // Inform the plot designer whether it should print png files, then write the result.
            log.setAddPrintCommand(add_print_command_);
            log.writeToFile(file_name_);
        } break;

        default: {
            throw geneva_exception(
                g_error_streamer(DO_LOG, Gem::Common::timeAndPlace())
                << "In GAdaptorPropertyLoggerT: Received invalid infoMode " << im << '\n'
            );
        }
        };
    }

    /************************************************************************/

    std::string file_name_ =
        "NAdaptions.C"; ///< The name of the file to which solutions should be stored

    std::string adaptor_name_ =
        "GDoubleGaussAdaptor"; ///< The  name of the adaptor for which properties should be logged
    std::string property_ = "sigma"; ///< The name of the property to be logged

    std::tuple<std::uint32_t, std::uint32_t> canvas_dimensions_ =
        std::tuple<std::uint32_t, std::uint32_t>(1200, 1600); ///< The dimensions of the canvas

    bool monitor_best_only_ =
        false; ///< Indicates whether only the best individuals should be monitored
    bool add_print_command_ =
        false; ///< Asks the GPlotDesigner to add a print command to result files

    std::size_t max_iteration_ = 0; ///< Holds the largest iteration recorded for the algorithm
    std::size_t n_iterations_recorded_ =
        0; ///< Holds the number of iterations that were recorded (not necessarily == max_iteration_

    std::vector<std::tuple<double, double>>
        adaptor_property_store_; ///< Holds all (iteration, property-value) data points
    std::vector<std::tuple<double, double>>
        fitness_store_; ///< Holds all (iteration, best-fitness) data points for the current run
};

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * This class allows to log the time needed for the processing step of each
 * individual. The output happens in the form of two root files, one holding histograms
 * for the processing times, the other showing the distribution of processing times for
 * each iteration in a 2D histogram
 */
class GProcessingTimesLogger // NOLINT(cppcoreguidelines-special-member-functions)
  : public Gem::Common::GReflectiveInterfaceT<GProcessingTimesLogger, oa::GBasePluggableOM> {
    ///////////////////////////////////////////////////////////////////////

    friend class boost::serialization::access;
    friend struct Gem::Common::GReflectiveInterfaceAccess;

    /***************************************************************************/
    /**
     * Single declaration of this class'es local data members, driving
     * serialize(), load_() and compare_() from one place. All members are plain
     * CONFIG (make_member); the histograms are no longer state -- they are
     * declared into two transient GDataLogs at INFOINIT, filled during
     * INFOPROCESSING and written at INFOEND. No manual tail is needed.
     */
    template <typename Self>
    auto localMembers_(this Self &self) {
        return std::make_tuple(
            Gem::Common::make_member("file_name_pth_", self.file_name_pth_),
            Gem::Common::make_member("canvas_dimensions_pth_", self.canvas_dimensions_pth_),
            Gem::Common::make_member("file_name_pth2_", self.file_name_pth2_),
            Gem::Common::make_member("canvas_dimensions_pth2_", self.canvas_dimensions_pth2_),
            Gem::Common::make_member("file_name_txt_", self.file_name_txt_),
            Gem::Common::make_member("n_bins_x_", self.n_bins_x_),
            Gem::Common::make_member("n_bins_y_", self.n_bins_y_)
        );
    }

    ///////////////////////////////////////////////////////////////////////

public:
    /** @brief The class name, consumed by the GReflectiveInterfaceT-generated name_() / compare token. */
    static constexpr std::string_view class_name = "GProcessingTimesLogger";

    /***************************************************************************/

    /** @brief The default constructor */
    GProcessingTimesLogger();
    /**
     * @brief Initialization with file names and histogram bin counts
     * @param file_name_pth The file name for the 1D processing-times histograms (ROOT format)
     * @param file_name_pth2 The file name for the 2D processing-times-versus-iteration histograms (ROOT format)
     * @param file_name_txt The file name for the plain-text processing-times output
     * @param n_bins_x The number of histogram bins in x-direction
     * @param n_bins_y The number of histogram bins in y-direction
     */
    GProcessingTimesLogger(
        const std::string &file_name_pth,
        const std::string &file_name_pth2,
        const std::string &file_name_txt,
        std::size_t n_bins_x,
        std::size_t n_bins_y
    );
    /** @brief The copy constructor */
    GProcessingTimesLogger(const GProcessingTimesLogger &cp) = default;
    /** @brief  The destructor */
    ~GProcessingTimesLogger() override = default;

    /**
     * @brief Sets the file name for the processing times histogram
     * @param file_name The file name for the 1D processing-times histograms
     */
    void setFileName_pth(const std::string &file_name);
    /**
     * @brief Retrieves the current file name for the processing times histogram
     * @return The file name for the 1D processing-times histograms
     */
    [[nodiscard]] std::string getFileName_pth() const;
    /**
     * @brief Sets the file name for the processing times histograms (2D)
     * @param file_name The file name for the 2D processing-times histograms
     */
    void setFileName_pth2(const std::string &file_name);
    /**
     * @brief Retrieves the current file name for the processing times histograms (2D)
     * @return The file name for the 2D processing-times histograms
     */
    [[nodiscard]] std::string getFileName_pth2() const;

    /**
     * @brief Sets the file name for the text output
     * @param file_name The file name for the plain-text processing-times output
     */
    void setFileName_txt(const std::string &file_name);
    /**
     * @brief Retrieves the current file name for the text output
     * @return The file name for the plain-text processing-times output
     */
    [[nodiscard]] std::string getFileName_txt() const;

    /**
     * @brief Allows to set the canvas dimensions for the processing times histograms
     * @param canvas_dimensions A tuple holding the canvas dimensions in x- and y-direction
     */
    void setCanvasDimensions_pth(std::tuple<std::uint32_t, std::uint32_t> canvas_dimensions);
    /**
     * @brief Allows to set the canvas dimensions using separate x and y values for the processing times histograms
     * @param x The canvas dimension in x-direction
     * @param y The canvas dimension in y-direction
     */
    void setCanvasDimensions_pth(std::uint32_t x, std::uint32_t y);

    /**
     * @brief Gives access to the canvas dimensions of the processing times histograms
     * @return A tuple holding the canvas dimensions in x- and y-direction
     */
    [[nodiscard]] std::tuple<std::uint32_t, std::uint32_t> getCanvasDimensions_pth() const;
    /**
     * @brief Allows to set the canvas dimensions for the processing times histograms (2D)
     * @param canvas_dimensions A tuple holding the canvas dimensions in x- and y-direction
     */
    void setCanvasDimensions_pth2(std::tuple<std::uint32_t, std::uint32_t> canvas_dimensions);

    /**
     * @brief Allows to set the canvas dimensions using separate x and y values for the processing times histograms (2D)
     * @param x The canvas dimension in x-direction
     * @param y The canvas dimension in y-direction
     */
    void setCanvasDimensions_pth2(std::uint32_t x, std::uint32_t y);
    /**
     * @brief Gives access to the canvas dimensions of the processing times histograms (2D)
     * @return A tuple holding the canvas dimensions in x- and y-direction
     */
    [[nodiscard]] std::tuple<std::uint32_t, std::uint32_t> getCanvasDimensions_pth2() const;

    /**
     * @brief Sets the number of bins for the processing times histograms in x-direction
     * @param n_bins_x The number of histogram bins in x-direction
     */
    void setNBinsX(std::size_t n_bins_x);
    /**
     * @brief Retrieves the current number of bins for the processing times histograms in x-direction
     * @return The number of histogram bins in x-direction
     */
    [[nodiscard]] std::size_t getNBinsX() const;

    /**
     * @brief Sets the number of bins for the processing times histograms in y-direction
     * @param n_bins_y The number of histogram bins in y-direction
     */
    void setNBinsY(std::size_t n_bins_y);
    /**
     * @brief Retrieves the current number of bins for the processing times histograms in y-direction
     * @return The number of histogram bins in y-direction
     */
    [[nodiscard]] std::size_t getNBinsY() const;

protected:
    /************************************************************************/

    /**
     * @brief Loads the data of another object into this one
     * @param cp A pointer to another object of this type, camouflaged as a GBasePluggableOM, whose data is copied
     */
    // load_(), compare_(), name_() and clone_() are generated by the
    // Gem::Common::GReflectiveInterfaceT base from class_name and localMembers_().

    /** @brief Applies modifications to this object */
    bool modify_GUnitTests_() override;
    /** @brief Performs self tests that are expected to succeed */
    void specificTestsNoFailureExpected_GUnitTests_() override;
    /** @brief Performs self tests that are expected to fail. This is needed for testing purposes */
    void specificTestsFailuresExpected_GUnitTests_() override;

private:

    /**
     * @brief Allows to emit information in different stages of the information cycle
     *
     * The first (unnamed) argument is the information mode (init, processing or finalization).
     * @param goa A constant pointer to the optimization algorithm whose state is being monitored
     */
    void
    informationFunction_(infoMode im, oa::GOptimizationAlgorithmBase const *const goa) override;

    /************************************************************************/

    std::string file_name_pth_ =
        "processingTimingsHist.C"; ///< The name of the file to which timings should be written in ROOT format
    std::tuple<std::uint32_t, std::uint32_t> canvas_dimensions_pth_ =
        std::tuple<std::uint32_t, std::uint32_t>(1600, 1200); ///< The dimensions of the canvas

    std::string file_name_pth2_ =
        "processingTimingsVsIteration.C"; ///< The name of the file to which timings should be written in ROOT format
    std::tuple<std::uint32_t, std::uint32_t> canvas_dimensions_pth2_ =
        std::tuple<std::uint32_t, std::uint32_t>(1600, 1200); ///< The dimensions of the canvas

    std::string file_name_txt_ =
        "processingTimings.txt"; ///< The name of the file to which timings should be written in text format

    std::size_t n_bins_x_ =
        Gem::Common::DEFAULTNBINSGPD; ///< The number of bins in the histograms in x-direction
    std::size_t n_bins_y_ =
        Gem::Common::DEFAULTNBINSGPD; ///< The number of bins in the histograms in y-direction

    // Transient run state: two data logs (1-d timing histograms / 2-d timing-vs-iteration
    // histograms), built at INFOINIT, filled in INFOPROCESSING and written at INFOEND. They
    // are NOT part of the monitor's serialized config. The id vectors hold the four series of
    // each log in the fixed order { pre, main, post, all }.
    std::optional<Gem::Dietrich::GDataLog> log_pth_;
    std::optional<Gem::Dietrich::GDataLog> log_pth2_;
    std::vector<Gem::Dietrich::GDataLog::SeriesId> pth_ids_;  ///< 1-d histogram series ids
    std::vector<Gem::Dietrich::GDataLog::SeriesId> pth2_ids_; ///< 2-d histogram series ids
};

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/

using GProgressPlotter = GProgressPlotterT<double>;
template <typename num_type>
using GAdaptorPropertyLogger = GAdaptorPropertyLoggerT<num_type>;

/******************************************************************************/

} /* namespace Gem::Geneva */

/******************************************************************************/
// Exports of classes

BOOST_CLASS_EXPORT_KEY(Gem::Geneva::GStandardMonitor)                     // NOLINT
BOOST_CLASS_EXPORT_KEY(Gem::Geneva::GFitnessMonitor)                      // NOLINT
BOOST_CLASS_EXPORT_KEY(Gem::Geneva::GCollectiveMonitor)                   // NOLINT
BOOST_CLASS_EXPORT_KEY(Gem::Geneva::GProgressPlotter)                     // NOLINT
BOOST_CLASS_EXPORT_KEY(Gem::Geneva::GAllSolutionFileLogger)               // NOLINT
BOOST_CLASS_EXPORT_KEY(Gem::Geneva::GIterationResultsFileLogger)          // NOLINT
BOOST_CLASS_EXPORT_KEY(Gem::Geneva::GNAdpationsLogger)                    // NOLINT
BOOST_CLASS_EXPORT_KEY(Gem::Geneva::GAdaptorPropertyLogger<double>)       // NOLINT
BOOST_CLASS_EXPORT_KEY(Gem::Geneva::GAdaptorPropertyLogger<std::int32_t>) // NOLINT
BOOST_CLASS_EXPORT_KEY(Gem::Geneva::GAdaptorPropertyLogger<bool>)         // NOLINT
BOOST_CLASS_EXPORT_KEY(Gem::Geneva::GProcessingTimesLogger)               // NOLINT
/******************************************************************************/
