/********************************************************************************
 *
 * This file is part of the Geneva library collection. The following license
 * applies to this file:
 *
 * ------------------------------------------------------------------------------
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ------------------------------------------------------------------------------
 *
 * Note that other files in the Geneva library collection may use a different
 * license. Please see the licensing information in each file.
 *
 ********************************************************************************
 *
 * See the NOTICE file in the top-level directory of the Geneva library
 * collection for a list of contributors and copyright information.
 *
 ********************************************************************************/

#pragma once

// Global checks, defines and includes needed for all of Geneva
#include "common/GGlobalDefines.hpp"

// Standard header files go here
#include <tuple>

// Boost header files go here

// Geneva header files go here
#include "common/GReflectiveInterfaceT.hpp"
#include "common/GCommonHelperFunctionsT.hpp"
#include "geneva/genome/GIndividualMultiConstraint.hpp"
#include "geneva/genome/GMultiConstraintT.hpp"
#include "geneva/genome/GOptimizableEntity.hpp"

namespace Gem::Geneva::Genome {

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * This class implements constraint definitions based on GOptimizableEntity-derivatives.
 * It is meant to be added to a constraint collection. The main purpose of this
 * class is to "translate" GOptimizableEntity-based constraints into constraints
 * based on GOptimizableEntity
 */
class GOptimizableEntityConstraint // NOLINT(cppcoreguidelines-special-member-functions)
  : public Gem::Common::GReflectiveInterfaceBaseT<GOptimizableEntityConstraint, GPreEvaluationValidityCheckT<GOptimizableEntity>> {
    ///////////////////////////////////////////////////////////////////////
    // GReflectiveInterfaceAccess lets the mixin reach localMembers_(); this abstract class is
    // never Boost-constructed.
    friend struct Gem::Common::GReflectiveInterfaceAccess;

    /** @brief This class adds no own members; the explicit empty declaration is required
     *  (the mixin's deleted fallback rejects a missing one). */
    template <typename Self>
    auto localMembers_(this Self &) {
        return std::make_tuple();
    }
    ///////////////////////////////////////////////////////////////////////
public:
    /** @brief The class name, consumed by the GReflectiveInterfaceBaseT-generated name_() / compare token. */
    static constexpr std::string_view class_name = "GOptimizableEntityConstraint";

    /** @brief The default constructor */
    GOptimizableEntityConstraint() = default;
    /**
     * @brief The copy constructor
     *
     * @param cp A constant reference to another GOptimizableEntityConstraint object to be copied
     */
    GOptimizableEntityConstraint(const GOptimizableEntityConstraint & cp) = default;
    /** @brief The destructor */
    ~GOptimizableEntityConstraint() override = default;

protected:
    /**
     * @brief Checks whether a given individual is valid
     *
     * @param individual A pointer to the GOptimizableEntity to be checked for constraint compliance
     * @return A measure of the constraint violation (pure virtual; defined by derived classes)
     */
    double check_(const GOptimizableEntity * individual) const override = 0;

    /**
     * @brief Adds local configuration options to a GParserBuilder object
     *
     * @param gpb A reference to the GParserBuilder to which this object's configuration options are added
     */
    void addConfigurationOptions_(Gem::Common::GParserBuilder & gpb) override;

    // load_(), compare_(), name_() and clone_() are generated by the
    // Gem::Common::GReflectiveInterfaceBaseT base (clone_ stays pure -- this is abstract)
    // from class_name and the empty localMembers_() declaration above.
};

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/

} /* namespace Gem::Geneva::Genome */

