/********************************************************************************
 *
 * This file is part of the Geneva library collection. The following license
 * applies to this file:
 *
 * ------------------------------------------------------------------------------
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ------------------------------------------------------------------------------
 *
 * Note that other files in the Geneva library collection may use a different
 * license. Please see the licensing information in each file.
 *
 ********************************************************************************
 *
 * See the NOTICE file in the top-level directory of the Geneva library
 * collection for a list of contributors and copyright information.
 *
 ********************************************************************************/

#include "dietrich/GPlotDesigner.hpp"
#include "common/GCommonEnums.hpp"
#include "common/GCommonHelperFunctions.hpp"
#include "common/GCommonHelperFunctionsT.hpp"
#include "common/GCommonInterfaceT.hpp"
#include "common/GCommonMathHelperFunctionsT.hpp"
#include "common/GErrorStreamer.hpp"
#include "common/GExceptions.hpp"
#include "common/GExpectationChecksT.hpp"
#include "common/GLogger.hpp"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <ios>
#include <istream>
#include <limits>
#include <locale>
#include <memory>
#include <optional>
#include <ostream>
#include <ranges>
#include <sstream>
#include <tuple>
#include <utility>
#include <vector>
#include "dietrich/plotting/detail/GPlotDetail.hpp"


namespace Gem::Dietrich {

// The plotting library builds on common's facilities (logging, serialization helpers,
// exception types, make_member, EmitStream, ...); make them visible here without
// per-name qualification. This affects lookup only within Gem::Dietrich.
using namespace Gem::Common;
// Dietrich declares its own to_string(plotKind), which would otherwise shadow common's
// numeric to_string(...) for unqualified calls; merge common's overloads back in.
using Gem::Common::to_string;

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * Adds arrows to the plots between consecutive points. Note that setting this
 * value to true will force "SCATTER" mode
 *
 * @param d_a The desired value of the draw_arrows_ variable
 */
void GGraph2D::setDrawArrows(bool d_a) {
    draw_arrows_ = d_a;
}

/******************************************************************************/
/**
 * Retrieves the value of the draw_arrows_ variable
 *
 * @return The value of the draw_arrows_ variable
 */
bool GGraph2D::getDrawArrows() const {
    return draw_arrows_;
}

/******************************************************************************/
/**
 * Determines whether a scatter plot or a curve is created
 *
 * @param p_m The desired plot mode
 */
void GGraph2D::setPlotMode(graphPlotMode p_m) {
    p_m_ = p_m;
}

/******************************************************************************/
/**
 * Allows to retrieve the current plotting mode
 *
 * @return The current plot mode
 */
graphPlotMode GGraph2D::getPlotMode() const {
    return p_m_;
}

/******************************************************************************/
/**
 * Retrieves a unique name for this plotter
 *
 * @return A unique name identifying this plotter type
 */
std::string GGraph2D::getPlotterName() const {
    return "GGraph2D";
}

/******************************************************************************/
/**
 * Reports this plotter's choice as a GPlotSpec (a 2-d xy graph).
 *
 * @return A GPlotSpec describing this GGraph2D
 */
GPlotSpec GGraph2D::plotSpec() const {
    GPlotSpec spec = GBasePlotter::plotSpec();
    spec.kind = plotKind::graph_2d;
    spec.role = defaultRole(spec.kind);
    spec.columns = {"x", "y"};
    spec.plot_mode = getPlotMode();
    return spec;
}

// name_() and compare_() for GGraph2D are generated by Gem::Common::GReflectiveInterfaceT
// from class_name and localMembers_().

/******************************************************************************/
/**
 * Retrieve specific header settings for this plot
 *
 * @param is_secondary Whether this plotter is a secondary plotter (true) or a primary one (false)
 * @param p_id The id of the parent plotter, used to build array names for secondary plotters
 * @param own_id This plotter's own emit index, threaded in by the caller (replaces the former mutated id_)
 * @param indent The indentation string prepended to every emitted line
 * @return The header code declaring the x/y data arrays for this graph
 */
std::string
GGraph2D::headerData_(bool is_secondary, std::size_t p_id, std::size_t own_id, const std::string &indent) const {
    EmitStream header_data; // NOLINT(cppcoreguidelines-init-variables)

    // Set up suitable arrays for the header
    std::string const base_name = suffix(is_secondary, p_id, own_id);
    std::string const array_base_name = "array_" + base_name;

    std::string const x_array_name = "x_" + array_base_name;
    std::string const y_array_name = "y_" + array_base_name;

    const std::string comment = dsMarkerComment(ds_marker_);

    header_data << indent << "double " << x_array_name << "[" << to_string(this->currentSize()) << "];"
                << comment << '\n'
                << indent << "double " << y_array_name << "[" << to_string(this->currentSize()) << "];"
                << '\n'
                << '\n';

    return header_data.str();
}

/******************************************************************************/
/**
 * Retrieves the actual data sets
 *
 * @param is_secondary Whether this plotter is a secondary plotter (true) or a primary one (false)
 * @param p_id The id of the parent plotter, used to build array names for secondary plotters
 * @param own_id This plotter's own emit index, threaded in by the caller (replaces the former mutated id_)
 * @param indent The indentation string prepended to every emitted line
 * @return The body code filling the x/y data arrays with this graph's tuple values
 */
std::string
GGraph2D::bodyData_(bool is_secondary, std::size_t p_id, std::size_t own_id, const std::string &indent) const {
    EmitStream body_data; // NOLINT(cppcoreguidelines-init-variables)

    // Set up suitable arrays for the header
    std::string const base_name = suffix(is_secondary, p_id, own_id);
    std::string const array_base_name = "array_" + base_name;

    std::string const x_array_name = "x_" + array_base_name;
    std::string const y_array_name = "y_" + array_base_name;

    std::string const comment; // NOLINT(cppcoreguidelines-init-variables)
    if(!ds_marker_.empty()) {
        body_data << "// " + rootEscape(ds_marker_) << '\n';
    }

    // Fill data from the columns into the arrays
    const auto &x_col = this->column<0>();
    const auto &y_col = this->column<1>();
    const std::size_t n = this->currentSize();

    for(std::size_t pos_counter = 0; pos_counter < n; ++pos_counter) {
        body_data << indent << x_array_name << "[" << pos_counter << "] = " << x_col[pos_counter]
                  << ";"
                  << "\t" << y_array_name << "[" << pos_counter << "] = " << y_col[pos_counter] << ";"
                  << '\n';
    }
    body_data << '\n';

    return body_data.str();
}

/******************************************************************************/
/**
 * Retrieves specific draw commands for this plot
 *
 * @param is_secondary Whether this plotter is a secondary plotter (true) or a primary one (false)
 * @param p_id The id of the parent plotter, used to build array/object names for secondary plotters
 * @param own_id This plotter's own emit index, threaded in by the caller (replaces the former mutated id_)
 * @param indent The indentation string prepended to every emitted line
 * @return The footer code creating and drawing the ROOT TGraph (and optional arrows) for this graph
 */
std::string
GGraph2D::footerData_(bool is_secondary, std::size_t p_id, std::size_t own_id, const std::string &indent) const {
    EmitStream footer_data; // NOLINT(cppcoreguidelines-init-variables)

    // Set up suitable arrays for the header
    std::string const base_name = suffix(is_secondary, p_id, own_id);
    std::string const array_base_name = "array_" + base_name;

    std::string const x_array_name = "x_" + array_base_name;
    std::string const y_array_name = "y_" + array_base_name;

    std::string const graph_name = std::string("graph") + base_name;

    std::string const comment; // NOLINT(cppcoreguidelines-init-variables)
    if(!ds_marker_.empty()) {
        footer_data << "// " + rootEscape(ds_marker_) << '\n';
    }

    // Retrieve the current drawing arguments
    std::string const d_a = this->drawingArguments(is_secondary);

    // Fill the data in our columns into a ROOT TGraph object
    footer_data << indent << "TGraph *" << graph_name << " = new TGraph(" << this->currentSize() << ", "
                << x_array_name << ", " << y_array_name << ");" << '\n'
                << indent << graph_name << "->GetXaxis()->SetTitle(\"" << rootEscape(xAxisLabel()) << "\");"
                << '\n'
                << indent << graph_name << "->GetYaxis()->SetTitle(\"" << rootEscape(yAxisLabel()) << "\");"
                << '\n';

    emitRootTitle(footer_data, indent, graph_name, plot_label_);

    footer_data << indent << graph_name << "->Draw(\"" << d_a << "\");" << '\n' << '\n';

    if(draw_arrows_ && this->currentSize() >= 2) {
        const auto &x_col = this->column<0>();
        const auto &y_col = this->column<1>();

        // Draw one arrow per adjacent pair of points; the pair index names the arrow.
        for(const auto &[idx, segment] :
            std::views::zip(x_col, y_col) | std::views::adjacent<2> | std::views::enumerate) {
            const auto pos_counter = static_cast<std::size_t>(idx);
            const auto &[p1, p2] = segment;
            const auto &[x1, y1] = p1;
            const auto &[x2, y2] = p2;

            footer_data << indent << "TArrow * ta_" << graph_name << "_" << pos_counter
                        << " = new TArrow(" << x1 << ", " << y1 << "," << x2 << ", " << y2 << ", "
                        << 0.05 << ", \"|>\");" << '\n'
                        << indent << "ta_" << graph_name << "_" << pos_counter
                        << "->SetArrowSize(0.01);" << '\n'
                        << indent << "ta_" << graph_name << "_" << pos_counter << "->Draw();"
                        << '\n';
        }
        footer_data << '\n';
    }
    footer_data << '\n';

    return footer_data.str();
}

/******************************************************************************/
/**
 * Retrieve the current drawing arguments
 *
 * @param is_secondary Whether this plotter is a secondary plotter (true) or a primary one (false)
 * @return The ROOT draw-option string, derived from custom arguments or the plot mode / arrow setting
 */
std::string GGraph2D::drawingArguments(bool is_secondary) const {
    std::string d_a;

    if(!this->drawing_arguments_.empty()) {
        d_a = this->drawing_arguments_;
    }
    else {
        if(graphPlotMode::SCATTER == p_m_ || draw_arrows_) {
            d_a = "P";
        }
        else {
            d_a = "PL";
        }

        if(is_secondary) {
            d_a = d_a + ",same";
        }
        else {
            d_a = "A" + d_a;
        }
    }

    return d_a;
}

// clone_() and load_() for GGraph2D are generated by Gem::Common::GReflectiveInterfaceT
// from class_name and localMembers_().

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * Determines whether a scatter plot or a curve is created
 *
 * @param p_m The desired plot mode
 */
void GGraph2ED::setPlotMode(graphPlotMode p_m) {
    p_m_ = p_m;
}

/******************************************************************************/
/**
 * Allows to retrieve the current plotting mode
 *
 * @return The current plot mode
 */
graphPlotMode GGraph2ED::getPlotMode() const {
    return p_m_;
}

/******************************************************************************/
/**
 * Retrieves a unique name for this plotter
 *
 * @return A unique name identifying this plotter type
 */
std::string GGraph2ED::getPlotterName() const {
    return "GGraph2ED";
}

/******************************************************************************/
/**
 * Reports this plotter's choice as a GPlotSpec (a 2-d xy graph with x/y errors).
 *
 * @return A GPlotSpec describing this GGraph2ED
 */
GPlotSpec GGraph2ED::plotSpec() const {
    GPlotSpec spec = GBasePlotter::plotSpec();
    spec.kind = plotKind::graph_2d_err;
    spec.role = defaultRole(spec.kind);
    spec.columns = {"x", "ex", "y", "ey"};
    spec.plot_mode = getPlotMode();
    return spec;
}

// name_() and compare_() for GGraph2ED are generated by Gem::Common::GReflectiveInterfaceT
// from class_name and localMembers_().

/******************************************************************************/
/**
 * Retrieve specific header settings for this plot
 *
 * @param is_secondary Whether this plotter is a secondary plotter (true) or a primary one (false)
 * @param p_id The id of the parent plotter, used to build array names for secondary plotters
 * @param own_id This plotter's own emit index, threaded in by the caller (replaces the former mutated id_)
 * @param indent The indentation string prepended to every emitted line
 * @return The header code declaring the x/ex/y/ey data arrays for this error graph
 */
std::string
GGraph2ED::headerData_(bool is_secondary, std::size_t p_id, std::size_t own_id, const std::string &indent) const {
    EmitStream header_data; // NOLINT(cppcoreguidelines-init-variables)

    // Set up suitable arrays for the header
    std::string const base_name = suffix(is_secondary, p_id, own_id);
    std::string const array_base_name = "array_" + base_name;

    std::string const x_array_name = "x_" + array_base_name;
    std::string const ex_array_name = "ex_" + array_base_name;
    std::string const y_array_name = "y_" + array_base_name;
    std::string const ey_array_name = "ey_" + array_base_name;

    const std::string comment = dsMarkerComment(ds_marker_);

    header_data << indent << "double " << x_array_name << "[" << to_string(this->currentSize()) << "];"
                << comment << '\n'
                << indent << "double " << ex_array_name << "[" << to_string(this->currentSize()) << "];"
                << '\n'
                << indent << "double " << y_array_name << "[" << to_string(this->currentSize()) << "];"
                << '\n'
                << indent << "double " << ey_array_name << "[" << to_string(this->currentSize()) << "];"
                << '\n'
                << '\n';

    return header_data.str();
}

/******************************************************************************/
/**
 * Retrieves the actual data sets
 *
 * @param is_secondary Whether this plotter is a secondary plotter (true) or a primary one (false)
 * @param p_id The id of the parent plotter, used to build array names for secondary plotters
 * @param own_id This plotter's own emit index, threaded in by the caller (replaces the former mutated id_)
 * @param indent The indentation string prepended to every emitted line
 * @return The body code filling the x/ex/y/ey data arrays with this graph's tuple values
 */
std::string
GGraph2ED::bodyData_(bool is_secondary, std::size_t p_id, std::size_t own_id, const std::string &indent) const {
    EmitStream body_data; // NOLINT(cppcoreguidelines-init-variables)

    // Set up suitable arrays for the header
    std::string const base_name = suffix(is_secondary, p_id, own_id);
    std::string const array_base_name = "array_" + base_name;

    std::string const x_array_name = "x_" + array_base_name;
    std::string const ex_array_name = "ex_" + array_base_name;
    std::string const y_array_name = "y_" + array_base_name;
    std::string const ey_array_name = "ey_" + array_base_name;

    std::string const comment; // NOLINT(cppcoreguidelines-init-variables)
    if(!ds_marker_.empty()) {
        body_data << "// " + rootEscape(ds_marker_) << '\n';
    }

    // Fill data from the columns into the arrays
    const auto &x_col = this->column<0>();
    const auto &ex_col = this->column<1>();
    const auto &y_col = this->column<2>();
    const auto &ey_col = this->column<3>();
    const std::size_t n = this->currentSize();

    for(std::size_t pos_counter = 0; pos_counter < n; ++pos_counter) {
        body_data << indent << x_array_name << "[" << pos_counter << "] = " << x_col[pos_counter]
                  << ";" << '\n'
                  << indent << ex_array_name << "[" << pos_counter << "] = " << ex_col[pos_counter]
                  << ";" << '\n'
                  << indent << y_array_name << "[" << pos_counter << "] = " << y_col[pos_counter]
                  << ";" << '\n'
                  << indent << ey_array_name << "[" << pos_counter << "] = " << ey_col[pos_counter]
                  << ";" << '\n';
    }
    body_data << '\n';

    return body_data.str();
}

/******************************************************************************/
/**
 * Retrieves specific draw commands for this plot
 *
 * @param is_secondary Whether this plotter is a secondary plotter (true) or a primary one (false)
 * @param p_id The id of the parent plotter, used to build array/object names for secondary plotters
 * @param own_id This plotter's own emit index, threaded in by the caller (replaces the former mutated id_)
 * @param indent The indentation string prepended to every emitted line
 * @return The footer code creating and drawing the ROOT TGraphErrors object for this graph
 */
std::string
GGraph2ED::footerData_(bool is_secondary, std::size_t p_id, std::size_t own_id, const std::string &indent) const {
    EmitStream footer_data; // NOLINT(cppcoreguidelines-init-variables)

    // Set up suitable arrays for the header
    std::string const base_name = suffix(is_secondary, p_id, own_id);
    std::string const array_base_name = "array_" + base_name;

    std::string const x_array_name = "x_" + array_base_name;
    std::string const ex_array_name = "ex_" + array_base_name;
    std::string const y_array_name = "y_" + array_base_name;
    std::string const ey_array_name = "ey_" + array_base_name;

    std::string const graph_name = std::string("graph_") + base_name;

    std::string const comment; // NOLINT(cppcoreguidelines-init-variables)
    if(!ds_marker_.empty()) {
        footer_data << "// " + rootEscape(ds_marker_) << '\n';
    }

    // Check whether custom drawing arguments have been set or whether one
    // of our generic choices has been selected
    std::string const d_a = this->drawingArguments(is_secondary);

    // Fill the data in our tuple-vector into a ROOT TGraphErrors object
    footer_data << indent << "TGraphErrors *" << graph_name << " = new TGraphErrors("
                << this->currentSize() << ", " << x_array_name << ", " << y_array_name << ", "
                << ex_array_name << " ," << ey_array_name << ");" << '\n'
                << indent << graph_name << "->GetXaxis()->SetTitle(\"" << rootEscape(xAxisLabel()) << "\");"
                << '\n'
                << indent << graph_name << "->GetYaxis()->SetTitle(\"" << rootEscape(yAxisLabel()) << "\");"
                << '\n';

    emitRootTitle(footer_data, indent, graph_name, plot_label_);

    footer_data << indent << graph_name << "->Draw(\"" << d_a << "\");" << '\n' << '\n';

    return footer_data.str();
}

/******************************************************************************/
/**
 * Retrieve the current drawing arguments
 *
 * @param is_secondary Whether this plotter is a secondary plotter (true) or a primary one (false)
 * @return The ROOT draw-option string, derived from custom arguments or the current plot mode
 */
std::string GGraph2ED::drawingArguments(bool is_secondary) const {
    std::string d_a;

    if(!this->drawing_arguments_.empty()) {
        d_a = this->drawing_arguments_;
    }
    else {
        if(graphPlotMode::SCATTER == p_m_) {
            d_a = "P";
        }
        else {
            d_a = "PL";
        }

        if(is_secondary) {
            d_a = d_a + ",same";
        }
        else {
            d_a = "A" + d_a;
        }
    }

    return d_a;
}

// clone_() and load_() for GGraph2ED are generated by Gem::Common::GReflectiveInterfaceT
// from class_name and localMembers_().

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * Adds lines to the plots between consecutive points.
 *
 * @param d_l The desired value of the draw_lines_ variable
 */
void GGraph3D::setDrawLines(bool d_l) {
    draw_lines_ = d_l;
}

/******************************************************************************/
/**
 * Retrieves the value of the draw_lines_ variable
 *
 * @return The value of the draw_lines_ variable
 */
bool GGraph3D::getDrawLines() const {
    return draw_lines_;
}

/******************************************************************************/
/**
 * Retrieves a unique name for this plotter
 *
 * @return A unique name identifying this plotter type
 */
std::string GGraph3D::getPlotterName() const {
    return "GGraph3D";
}

/******************************************************************************/
/**
 * Reports this plotter's choice as a GPlotSpec (a 3-d xyz graph).
 *
 * @return A GPlotSpec describing this GGraph3D
 */
GPlotSpec GGraph3D::plotSpec() const {
    GPlotSpec spec = GBasePlotter::plotSpec();
    spec.kind = plotKind::graph_3d;
    spec.role = defaultRole(spec.kind);
    spec.columns = {"x", "y", "z"};
    return spec;
}

// name_() and compare_() for GGraph3D are generated by Gem::Common::GReflectiveInterfaceT
// from class_name and localMembers_().

/******************************************************************************/
/**
 * Retrieve specific header settings for this plot
 *
 * @param is_secondary Whether this plotter is a secondary plotter (true) or a primary one (false)
 * @param p_id The id of the parent plotter, used to build array names for secondary plotters
 * @param own_id This plotter's own emit index, threaded in by the caller (replaces the former mutated id_)
 * @param indent The indentation string prepended to every emitted line
 * @return The header code declaring the x/y/z data arrays for this 3D graph
 */
std::string
GGraph3D::headerData_(bool is_secondary, std::size_t p_id, std::size_t own_id, const std::string &indent) const {
    EmitStream header_data; // NOLINT(cppcoreguidelines-init-variables)

    // Set up suitable arrays for the header
    std::string const base_name = suffix(is_secondary, p_id, own_id);
    std::string const array_base_name = "array_" + base_name;

    std::string const x_array_name = "x_" + array_base_name;
    std::string const y_array_name = "y_" + array_base_name;
    std::string const z_array_name = "z_" + array_base_name;

    const std::string comment = dsMarkerComment(ds_marker_);

    header_data << indent << "double " << x_array_name << "[" << to_string(this->currentSize()) << "];"
                << comment << '\n'
                << indent << "double " << y_array_name << "[" << to_string(this->currentSize()) << "];"
                << '\n'
                << indent << "double " << z_array_name << "[" << to_string(this->currentSize()) << "];"
                << '\n'
                << '\n';

    return header_data.str();
}

/******************************************************************************/
/**
 * Retrieves the actual data sets
 *
 * @param is_secondary Whether this plotter is a secondary plotter (true) or a primary one (false)
 * @param p_id The id of the parent plotter, used to build array names for secondary plotters
 * @param own_id This plotter's own emit index, threaded in by the caller (replaces the former mutated id_)
 * @param indent The indentation string prepended to every emitted line
 * @return The body code filling the x/y/z data arrays with this graph's tuple values
 */
std::string
GGraph3D::bodyData_(bool is_secondary, std::size_t p_id, std::size_t own_id, const std::string &indent) const {
    EmitStream body_data; // NOLINT(cppcoreguidelines-init-variables)

    // Set up suitable arrays for the header
    std::string const base_name = suffix(is_secondary, p_id, own_id);
    std::string const array_base_name = "array_" + base_name;

    std::string const x_array_name = "x_" + array_base_name;
    std::string const y_array_name = "y_" + array_base_name;
    std::string const z_array_name = "z_" + array_base_name;

    std::string const comment; // NOLINT(cppcoreguidelines-init-variables)
    if(!ds_marker_.empty()) {
        body_data << "// " + rootEscape(ds_marker_) << '\n';
    }

    // Fill data from the columns into the arrays
    const auto &x_col = this->column<0>();
    const auto &y_col = this->column<1>();
    const auto &z_col = this->column<2>();
    const std::size_t n = this->currentSize();

    for(std::size_t pos_counter = 0; pos_counter < n; ++pos_counter) {
        body_data << indent << x_array_name << "[" << pos_counter << "] = " << x_col[pos_counter]
                  << ";"
                  << "\t" << y_array_name << "[" << pos_counter << "] = " << y_col[pos_counter] << ";"
                  << "\t" << z_array_name << "[" << pos_counter << "] = " << z_col[pos_counter] << ";"
                  << '\n';
    }
    body_data << '\n';

    return body_data.str();
}

/******************************************************************************/
/**
 * Retrieves specific draw commands for this plot
 *
 * @param is_secondary Whether this plotter is a secondary plotter (true) or a primary one (false)
 * @param p_id The id of the parent plotter, used to build array/object names for secondary plotters
 * @param own_id This plotter's own emit index, threaded in by the caller (replaces the former mutated id_)
 * @param indent The indentation string prepended to every emitted line
 * @return The footer code creating and drawing the ROOT TGraph2D (and optional poly-line) for this graph
 */
std::string
GGraph3D::footerData_(bool is_secondary, std::size_t p_id, std::size_t own_id, const std::string &indent) const {
    EmitStream footer_data; // NOLINT(cppcoreguidelines-init-variables)

    // Set up suitable arrays for the header
    std::string const base_name = suffix(is_secondary, p_id, own_id);
    std::string const array_base_name = "array_" + base_name;

    std::string const x_array_name = "x_" + array_base_name;
    std::string const y_array_name = "y_" + array_base_name;
    std::string const z_array_name = "z_" + array_base_name;

    std::string const graph_name = std::string("graph_") + base_name;

    std::string const comment; // NOLINT(cppcoreguidelines-init-variables)
    if(!ds_marker_.empty()) {
        footer_data << "// " + rootEscape(ds_marker_) << '\n';
    }

    // Check whether custom drawing arguments have been set or whether one
    // of our generic choices has been selected
    std::string const d_a = this->drawingArguments(is_secondary);

    // Fill the data in our columns into a ROOT TGraph object
    footer_data << indent << "TGraph2D *" << graph_name << " = new TGraph2D(" << this->currentSize()
                << ", " << x_array_name << ", " << y_array_name << ", " << z_array_name << ");"
                << '\n'
                << indent << graph_name << "->GetXaxis()->SetTitle(\"" << rootEscape(xAxisLabel()) << "\");"
                << '\n'
                << indent << graph_name << "->GetXaxis()->SetTitleOffset(1.5);" << '\n'
                << indent << graph_name << "->GetYaxis()->SetTitle(\"" << rootEscape(yAxisLabel()) << "\");"
                << '\n'
                << indent << graph_name << "->GetYaxis()->SetTitleOffset(1.5);" << '\n'
                << indent << graph_name << "->GetZaxis()->SetTitle(\"" << rootEscape(zAxisLabel()) << "\");"
                << '\n'
                << indent << graph_name << "->GetZaxis()->SetTitleOffset(1.5);" << '\n'
                << indent << graph_name << "->SetMarkerStyle(20);" << '\n'
                << indent << graph_name << "->SetMarkerSize(1);" << '\n'
                << indent << graph_name << "->SetMarkerColor(2);" << '\n';

    emitRootTitle(footer_data, indent, graph_name, plot_label_);

    footer_data << indent << graph_name << "->Draw(\"" << d_a << "\");" << '\n' << '\n';

    if(draw_lines_ && this->currentSize() >= 2) {
        const auto &x_col = this->column<0>();
        const auto &y_col = this->column<1>();
        const auto &z_col = this->column<2>();
        const std::size_t n = this->currentSize();

        double x = 0.0;
        double y = 0.0;
        double z = 0.0;

        footer_data << indent << "TPolyLine3D *lines_" << graph_name << " = new TPolyLine3D("
                    << this->currentSize() << ");" << '\n'
                    << '\n';

        for(std::size_t pos_counter = 0; pos_counter < n; ++pos_counter) {
            x = x_col[pos_counter];
            y = y_col[pos_counter];
            z = z_col[pos_counter];

            footer_data << indent << "lines_" << graph_name << "->SetPoint(" << pos_counter << ", "
                        << x << ", " << y << ", " << z << ");";
        }
        footer_data << '\n'
                    << indent << "lines_" << graph_name << "->SetLineWidth(3);" << '\n'
                    << indent << "lines_" << graph_name << "->Draw();" << '\n'
                    << '\n';
    }

    return footer_data.str();
}

/******************************************************************************/
/**
 * Retrieve the current drawing arguments
 *
 * @param is_secondary Whether this plotter is a secondary plotter (true) or a primary one (false)
 * @return The ROOT draw-option string, derived from custom arguments or the default point-draw option
 */
std::string GGraph3D::drawingArguments(bool is_secondary) const {
    std::string d_a;

    if(!this->drawing_arguments_.empty()) {
        d_a = this->drawing_arguments_;
    }
    else {
        d_a = "P";

        if(is_secondary) {
            d_a = d_a + ",same";
        }
    }

    return d_a;
}

// clone_() and load_() for GGraph3D are generated by Gem::Common::GReflectiveInterfaceT
// from class_name and localMembers_().

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * Allows to set the minimum marker size
 *
 * @param min_marker_size The minimum marker size; must be non-negative, otherwise an exception is thrown
 */
void GGraph4D::setMinMarkerSize(const double &min_marker_size) {
    if(min_marker_size < 0.) {
        throw geneva_exception(
            g_error_streamer(DO_LOG, Gem::Common::timeAndPlace())
            << "In GGraph4D::setMinMarkerSize(): Error!" << '\n'
            << "Received invalid minimum marker size: " << min_marker_size << '\n'
        );
    }

    min_marker_size_ = min_marker_size;
}

/******************************************************************************/
/**
 * Allows to set the maximum marker size
 *
 * @param max_marker_size The maximum marker size; must be non-negative and not smaller than the
 * previously set minimum marker size, otherwise an exception is thrown
 */
void GGraph4D::setMaxMarkerSize(const double &max_marker_size) {
    if(max_marker_size < 0. || max_marker_size < min_marker_size_) {
        throw geneva_exception(
            g_error_streamer(DO_LOG, Gem::Common::timeAndPlace())
            << "In GGraph4D::setMinMarkerSize(): Error!" << '\n'
            << "Received invalid minimum marker size: " << min_marker_size_ << " " << max_marker_size
            << "." << '\n'
            << "Always set the lower boundary first." << '\n'
        );
    }

    max_marker_size_ = max_marker_size;
}

/******************************************************************************/
/**
 * Allows to retrieve the minimum marker size
 *
 * @return The currently configured minimum marker size
 */
double GGraph4D::getMinMarkerSize() const {
    return min_marker_size_;
}

/******************************************************************************/
/**
 * Allows to retrieve the maximum marker size
 *
 * @return The currently configured maximum marker size
 */
double GGraph4D::getMaxMarkerSize() const {
    return max_marker_size_;
}

/******************************************************************************/
/**
 * Allows to specify whether small w yield large markers
 *
 * @param swlm If true, small fourth-component (w) values are mapped to large markers; if false, the reverse
 */
void GGraph4D::setSmallWLargeMarker(const bool &swlm) {
    small_w_large_marker_ = swlm;
}

/******************************************************************************/
/**
 * Allows to check whether small w yield large markers
 *
 * @return true if small fourth-component (w) values are mapped to large markers, false otherwise
 */
bool GGraph4D::getSmallWLargeMarker() const {
    return small_w_large_marker_;
}

/******************************************************************************/
/**
 * Allows to set the number of solutions the class should show. Setting the value
 * to 0 will result in all data being displayed.
 *
 * @param n_best The number of (best) solutions to display; 0 means display all data points
 */
void GGraph4D::setNBest(const std::size_t &n_best) {
    n_best_ = n_best;
}

/******************************************************************************/
/**
 * Allows to retrieve the number of solutions the class should show
 *
 * @return The number of (best) solutions to display; 0 means all data points are shown
 */
std::size_t GGraph4D::getNBest() const {
    return n_best_;
}

/******************************************************************************/
/**
 * Retrieves a unique name for this plotter
 *
 * @return A unique name identifying this plotter type
 */
std::string GGraph4D::getPlotterName() const {
    return "GGraph4D";
}

/******************************************************************************/
/**
 * Reports this plotter's choice as a GPlotSpec (a 4-d xyzw graph).
 *
 * @return A GPlotSpec describing this GGraph4D
 */
GPlotSpec GGraph4D::plotSpec() const {
    GPlotSpec spec = GBasePlotter::plotSpec();
    spec.kind = plotKind::graph_4d;
    spec.role = defaultRole(spec.kind);
    spec.columns = {"x", "y", "z", "w"};
    return spec;
}

// name_() and compare_() for GGraph4D are generated by Gem::Common::GReflectiveInterfaceT
// from class_name and localMembers_().

/******************************************************************************/
/**
 * Retrieve specific header settings for this plot. The four positional parameters
 * (is_secondary flag, parent id, own id and indentation string) are unused because this 4D
 * graph emits all of its ROOT code in the footer section.
 *
 * @return An empty string, as this 4D graph emits no header code
 */
std::string GGraph4D::headerData_([[maybe_unused]] bool is_secondary, [[maybe_unused]] std::size_t parent_id, [[maybe_unused]] std::size_t own_id, [[maybe_unused]] std::string const &indent) const {
    EmitStream const header_data; // NOLINT(cppcoreguidelines-init-variables)

    // nothing

    return header_data.str();
}

/******************************************************************************/
/**
 * Retrieves the actual data sets. The four positional parameters (is_secondary flag,
 * parent id, own id and indentation string) are unused because this 4D graph emits all of its
 * ROOT code in the footer section.
 *
 * @return An empty string, as this 4D graph emits no body data
 */
std::string GGraph4D::bodyData_([[maybe_unused]] bool is_secondary, [[maybe_unused]] std::size_t parent_id, [[maybe_unused]] std::size_t own_id, [[maybe_unused]] std::string const &indent) const {
    EmitStream const body_data; // NOLINT(cppcoreguidelines-init-variables)

    // nothing

    return body_data.str();
}

/******************************************************************************/
/**
 * Retrieves specific draw commands for this plot
 *
 * @param is_secondary Whether this plotter is a secondary plotter (true) or a primary one (false)
 * @param p_id The id of the parent plotter, used to build unique object names for secondary plotters
 * @param own_id This plotter's own emit index, threaded in by the caller (replaces the former mutated id_)
 * @param indent The indentation string prepended to every emitted line
 * @return The footer code creating the 3D frame and per-point poly-markers (sized by the fourth component)
 */
std::string
// NOLINTNEXTLINE(readability-function-size) -- one coherent 4D-scatter ROOT rendering kernel: w-ordered permutation, the TH3F frame's min/max bookkeeping and the per-point marker-size/draw emission all share the same ordered data; splitting would scatter tightly coupled state
GGraph4D::footerData_(bool is_secondary, std::size_t p_id, std::size_t own_id, const std::string &indent) const {
    // Read the four columns directly. Rather than copying the whole data set to
    // sort it on every emission, we sort an index permutation by the w-component
    // (axis 3) and read each point through that permutation; the columns stay put.
    const auto &x_col = this->column<0>();
    const auto &y_col = this->column<1>();
    const auto &z_col = this->column<2>();
    const auto &w_col = this->column<3>();
    const std::size_t data_size = this->currentSize();

    std::string const base_name = suffix(is_secondary, p_id, own_id);

    // Build the w-ordered index permutation, so we can select the n_best_ best more easily
    std::vector<std::size_t> order = std::views::iota(0uz, data_size)
        | std::ranges::to<std::vector<std::size_t>>();
    if(small_w_large_marker_) {
        std::ranges::sort(order, [&w_col](std::size_t a, std::size_t b) -> bool {
            return (w_col[a] < w_col[b]);
        });
    }
    else {
        std::ranges::sort(order, [&w_col](std::size_t a, std::size_t b) -> bool {
            return (w_col[a] > w_col[b]);
        });
    }

    EmitStream footer_data; // NOLINT(cppcoreguidelines-init-variables)

    // Find out about the minimum and maximum values of the data set. This preserves
    // the previous getMinMax(4D) contract, including its requirement of at least two
    // data items, while reading straight from the columns (no copy).
    if(data_size < static_cast<std::size_t>(2)) {
        throw geneva_exception(
            g_error_streamer(DO_LOG, Gem::Common::timeAndPlace())
            << "In GGraph4D::footerData_(): Error!" << '\n'
            << "Got vector of invalid size " << data_size << '\n'
        );
    }
    std::tuple<double, double, double, double, double, double, double, double> min_max{
        *std::ranges::min_element(x_col),
        *std::ranges::max_element(x_col),
        *std::ranges::min_element(y_col),
        *std::ranges::max_element(y_col),
        *std::ranges::min_element(z_col),
        *std::ranges::max_element(z_col),
        *std::ranges::min_element(w_col),
        *std::ranges::max_element(w_col)
    };

    // Set up the TH3F frame for our 3D data, spanning the minimum and maximum values. The
    // frame name carries the plot suffix so two 4D plots on one canvas do not collide.
    const std::string frame_name = std::string("fr_") + base_name;
    footer_data << indent << "TH3F *" << frame_name << " = new TH3F(\"" << frame_name << "\",\"" << frame_name << "\","
                << "10, " << std::get<0>(min_max) << ", " << std::get<1>(min_max) << ", "
                << "10, " << std::get<2>(min_max) << ", " << std::get<3>(min_max) << ", "
                << "10, " << std::get<4>(min_max) << ", " << std::get<5>(min_max) << ");" << '\n'
                << indent << frame_name << "->SetTitle(\" \");" << '\n'
                << indent << frame_name << "->GetXaxis()->SetTitle(\"" << rootEscape(xAxisLabel()) << "\");" << '\n'
                << indent << frame_name << "->GetXaxis()->SetTitleOffset(1.6);" << '\n'
                << indent << frame_name << "->GetYaxis()->SetTitle(\"" << rootEscape(yAxisLabel()) << "\");" << '\n'
                << indent << frame_name << "->GetYaxis()->SetTitleOffset(1.6);" << '\n'
                << indent << frame_name << "->GetZaxis()->SetTitle(\"" << rootEscape(zAxisLabel()) << "\");" << '\n'
                << indent << frame_name << "->GetZaxis()->SetTitleOffset(1.6);" << '\n'
                << '\n'
                << indent << frame_name << "->Draw();" << '\n';

    double const w_min = std::get<6>(min_max);
    double const w_max = std::get<7>(min_max);

    // Fill data from the columns into the arrays, following the w-ordered permutation
    double const w_range = w_max - w_min;
    std::size_t pos = 0;
    for(std::size_t const idx : order) {
        std::string const poly_marker_name =
            std::string("pm3d_") + base_name + std::string("_") + to_string(pos);

        // create a TPolyMarker3D for a single data point
        footer_data << indent << "TPolyMarker3D *" << poly_marker_name << " = new TPolyMarker3D(1);"
                    << '\n';

        double const x = x_col[idx];
        double const y = y_col[idx];
        double const z = z_col[idx];
        double const w = w_col[idx];

        // Translate the fourth component into a marker size. By default,
        // smaller values will yield the largest value
        double marker_size = 0.;
        if(0 == pos) {
            marker_size = 2 * max_marker_size_;
        }
        else {
            if(small_w_large_marker_) {
                marker_size = min_marker_size_ + ((max_marker_size_ - min_marker_size_) *
                                                   pow((1. - ((w - w_min) / w_range)), 8.));
            }
            else {
                marker_size = min_marker_size_ +
                              ((max_marker_size_ - min_marker_size_) * pow(((w - w_min) / w_range), 8));
            }
        }

        footer_data << indent << poly_marker_name << "->SetPoint(" << pos << ", " << x << ", " << y
                    << ", " << z << "); // w = " << w << '\n'
                    << indent << poly_marker_name << "->SetMarkerSize(" << marker_size << ");"
                    << '\n'
                    << indent << poly_marker_name << "->SetMarkerColor(" << (0 == pos ? 4 : 2)
                    << ");" << '\n'
                    << indent << poly_marker_name << "->SetMarkerStyle(8);" << '\n'
                    << indent << poly_marker_name << "->Draw();" << '\n'
                    << '\n';

        pos++;

        if(n_best_ && pos >= n_best_) {
            break;
        }
    }

    footer_data << '\n';

    return footer_data.str();
}

/******************************************************************************/
/**
 * Retrieve the current drawing arguments. The is_secondary flag parameter is unused,
 * as this 4D graph builds its draw commands entirely in the footer section.
 *
 * @return An empty string, as no generic draw-option string is used by this plotter
 */
std::string GGraph4D::drawingArguments([[maybe_unused]] bool is_secondary) const {
    std::string d_a;

    // nothing

    return d_a;
}

// clone_() and load_() for GGraph4D are generated by Gem::Common::GReflectiveInterfaceT
// from class_name and localMembers_().

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * The standard constructor. Some member variables may be initialized in the
 * class body.
 *
 * @param f_d The function description (a ROOT-style formula string) to be plotted
 * @param x_extremes A tuple holding the lower (get<0>) and upper (get<1>) boundary of the x-axis range
 */
GFunctionPlotter1D::GFunctionPlotter1D(
    const std::string &f_d,
    const std::tuple<double, double> &x_extremes
)
  : function_description_(f_d)
  , x_extremes_(x_extremes) { /* nothing */
}

/******************************************************************************/
/**
 * Allows to set the number of sampling points of the function on the x-axis
 *
 * @param n_samples_x The number of sampling points of the function on the x-axis
 */
void GFunctionPlotter1D::setNSamplesX(std::size_t n_samples_x) {
    n_samples_x_ = n_samples_x;
}

/******************************************************************************/
/**
 * Retrieves a unique name for this plotter
 *
 * @return A unique name identifying this plotter type
 */
std::string GFunctionPlotter1D::getPlotterName() const {
    return "GFunctionPlotter1D";
}

/******************************************************************************/
/**
 * Reports this plotter's choice as a GPlotSpec (a sampled 1-d function plot). A
 * function plotter carries no sampled data columns.
 *
 * @return A GPlotSpec describing this GFunctionPlotter1D
 */
GPlotSpec GFunctionPlotter1D::plotSpec() const {
    GPlotSpec spec = GBasePlotter::plotSpec();
    spec.kind = plotKind::function_1d;
    spec.role = defaultRole(spec.kind);
    return spec;
}

// name_() and compare_() for GFunctionPlotter1D are generated by Gem::Common::GReflectiveInterfaceT
// from class_name and localMembers_().

/******************************************************************************/
/**
 * Retrieve specific header settings for this plot
 *
 * @param is_secondary Whether this plotter is a secondary plotter (true) or a primary one (false)
 * @param p_id The id of the parent plotter, used to build a unique function name for secondary plotters
 * @param own_id This plotter's own emit index, threaded in by the caller (replaces the former mutated id_)
 * @param indent The indentation string prepended to every emitted line
 * @return The code to be added to the plot header for this function
 */
std::string GFunctionPlotter1D::headerData_(
    bool is_secondary,
    std::size_t p_id,
    std::size_t own_id,
    const std::string &indent
) const {
    // Check the extreme values for consistency
    if(std::get<0>(x_extremes_) >= std::get<1>(x_extremes_)) {
        throw geneva_exception(
            g_error_streamer(DO_LOG, Gem::Common::timeAndPlace())
            << "In GFunctionPlotter1D::headerData_(): Error!" << '\n'
            << "lower boundary >= upper boundary: " << std::get<0>(x_extremes_) << " / "
            << std::get<1>(x_extremes_) << '\n'
        );
    }

    EmitStream result; // NOLINT(cppcoreguidelines-init-variables)

    const std::string comment = dsMarkerComment(ds_marker_);

    std::string const function_name = "func1D" + suffix(is_secondary, p_id, own_id);
    result << indent << "TF1 *" << function_name << " = new TF1(\"" << function_name << "\", \""
           << rootEscape(function_description_) << "\"," << std::get<0>(x_extremes_) << ", "
           << std::get<1>(x_extremes_) << ");" << comment << '\n';

    return result.str();
}

/******************************************************************************/
/**
 * Retrieves the actual data sets. The three positional parameters (is_secondary flag,
 * parent id and indentation string) are unused, as a function plotter contributes no data points.
 *
 * @return The code to be added to the plot's data section for this function (always empty)
 */
std::string GFunctionPlotter1D::bodyData_([[maybe_unused]] bool is_secondary, [[maybe_unused]] std::size_t parent_id, [[maybe_unused]] std::size_t own_id, [[maybe_unused]] std::string const &indent) const {
    // No data needs to be added for a function plotter
    return {};
}

/******************************************************************************/
/**
 * Retrieves specific draw commands for this plot
 *
 * @param is_secondary Whether this plotter is a secondary plotter (true) or a primary one (false)
 * @param p_id The id of the parent plotter, used to build a unique function name for secondary plotters
 * @param own_id This plotter's own emit index, threaded in by the caller (replaces the former mutated id_)
 * @param indent The indentation string prepended to every emitted line
 * @return The draw command to be added to the plot's data for this function
 */
std::string GFunctionPlotter1D::footerData_(
    bool is_secondary,
    std::size_t p_id,
    std::size_t own_id,
    const std::string &indent
) const {
    EmitStream footer_data; // NOLINT(cppcoreguidelines-init-variables)

    const std::string comment = dsMarkerComment(ds_marker_);

    std::string const function_name = "func1D" + suffix(is_secondary, p_id, own_id);
    footer_data << indent << function_name << "->GetXaxis()->SetTitle(\"" << rootEscape(xAxisLabel()) << "\");"
                << '\n'
                << indent << function_name << "->GetYaxis()->SetTitle(\"" << rootEscape(yAxisLabel()) << "\");"
                << '\n'
                << indent << function_name << "->SetNpx(" << n_samples_x_ << ");" << '\n';

    emitRootTitle(footer_data, indent, function_name, plot_label_);

    std::string const d_a = this->drawingArguments(is_secondary);

    footer_data << indent << function_name << "->Draw(\"" << d_a << "\");"
                << comment << '\n'
                << '\n';

    return footer_data.str();
}

/******************************************************************************/
/**
 * Retrieve the current drawing arguments
 *
 * @param is_secondary Whether this plotter is a secondary plotter (true) or a primary one (false)
 * @return The ROOT draw-option string; secondary plotters get the "same" option appended
 */
std::string GFunctionPlotter1D::drawingArguments(bool is_secondary) const {
    std::string d_a;

    if(!this->drawing_arguments_.empty()) {
        d_a = this->drawing_arguments_;
    }

    if(is_secondary) {
        if(d_a.empty()) {
            d_a = "same";
        }
        else {
            d_a = d_a + ",same";
        }
    }

    return d_a;
}

// clone_() and load_() for GFunctionPlotter1D are generated by Gem::Common::GReflectiveInterfaceT
// from class_name and localMembers_().

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * The standard constructor
 *
 * @param f_d The function description (a ROOT-style formula string) to be plotted
 * @param x_extremes A tuple holding the lower (get<0>) and upper (get<1>) boundary of the x-axis range
 * @param y_extremes A tuple holding the lower (get<0>) and upper (get<1>) boundary of the y-axis range
 */
GFunctionPlotter2D::GFunctionPlotter2D(
    const std::string &f_d,
    const std::tuple<double, double> &x_extremes,
    const std::tuple<double, double> &y_extremes
)
  : function_description_(f_d)
  , x_extremes_(x_extremes)
  , y_extremes_(y_extremes) { /* nothing */
}

/******************************************************************************/
/**
 * Allows to set the number of sampling points of the function on the x-axis
 *
 * @param n_samples_x The number of sampling points of the function on the x-axis
 */
void GFunctionPlotter2D::setNSamplesX(std::size_t n_samples_x) {
    n_samples_x_ = n_samples_x;
}

/******************************************************************************/
/**
 * Allows to set the number of sampling points of the function on the y-axis
 *
 * @param n_samples_y The number of sampling points of the function on the y-axis
 */
void GFunctionPlotter2D::setNSamplesY(std::size_t n_samples_y) {
    n_samples_y_ = n_samples_y;
}

/******************************************************************************/
/**
 * Retrieves a unique name for this plotter
 *
 * @return A unique name identifying this plotter type
 */
std::string GFunctionPlotter2D::getPlotterName() const {
    return "GFunctionPlotter2D";
}

/******************************************************************************/
/**
 * Reports this plotter's choice as a GPlotSpec (a sampled 2-d function plot). A
 * function plotter carries no sampled data columns.
 *
 * @return A GPlotSpec describing this GFunctionPlotter2D
 */
GPlotSpec GFunctionPlotter2D::plotSpec() const {
    GPlotSpec spec = GBasePlotter::plotSpec();
    spec.kind = plotKind::function_2d;
    spec.role = defaultRole(spec.kind);
    return spec;
}

// name_() and compare_() for GFunctionPlotter2D are generated by Gem::Common::GReflectiveInterfaceT
// from class_name and localMembers_().

/******************************************************************************/
/**
 * Retrieve specific header settings for this plot
 *
 * @param is_secondary Whether this plotter is a secondary plotter (true) or a primary one (false)
 * @param p_id The id of the parent plotter, used to build a unique function name for secondary plotters
 * @param own_id This plotter's own emit index, threaded in by the caller (replaces the former mutated id_)
 * @param indent The indentation string prepended to every emitted line
 * @return The code to be added to the plot header for this function
 */
std::string GFunctionPlotter2D::headerData_(
    bool is_secondary,
    std::size_t p_id,
    std::size_t own_id,
    const std::string &indent
) const {
    // Check the extreme values for consistency
    if(std::get<0>(x_extremes_) >= std::get<1>(x_extremes_)) {
        throw geneva_exception(
            g_error_streamer(DO_LOG, Gem::Common::timeAndPlace())
            << "In GFunctionPlotter2D::headerData_(): Error!" << '\n'
            << "lower boundary(x) >= upper boundary(x): " << std::get<0>(x_extremes_) << " / "
            << std::get<1>(x_extremes_) << '\n'
        );
    }

    if(std::get<0>(y_extremes_) >= std::get<1>(y_extremes_)) {
        throw geneva_exception(
            g_error_streamer(DO_LOG, Gem::Common::timeAndPlace())
            << "In GFunctionPlotter2D::headerData_(): Error!" << '\n'
            << "lower boundary(y) >= upper boundary(y): " << std::get<0>(y_extremes_) << " / "
            << std::get<1>(y_extremes_) << '\n'
        );
    }

    EmitStream result; // NOLINT(cppcoreguidelines-init-variables)

    const std::string comment = dsMarkerComment(ds_marker_);

    std::string const function_name = "func2D" + suffix(is_secondary, p_id, own_id);
    result << indent << "TF2 *" << function_name << " = new TF2(\"" << function_name << "\", \""
           << rootEscape(function_description_) << "\"," << std::get<0>(x_extremes_) << ", "
           << std::get<1>(x_extremes_) << ", " << std::get<0>(y_extremes_) << ", "
           << std::get<1>(y_extremes_) << ");" << comment << '\n';

    return result.str();
}

/******************************************************************************/
/**
 * Retrieves the actual data sets. The three positional parameters (is_secondary flag,
 * parent id and indentation string) are unused, as a function plotter contributes no data points.
 *
 * @return The code to be added to the plot's data section for this function (always empty)
 */
std::string GFunctionPlotter2D::bodyData_([[maybe_unused]] bool is_secondary, [[maybe_unused]] std::size_t parent_id, [[maybe_unused]] std::size_t own_id, [[maybe_unused]] std::string const &indent) const {
    // No data needs to be added for a function plotter
    return {};
}

/******************************************************************************/
/**
 * Retrieves specific draw commands for this plot
 *
 * @param is_secondary Whether this plotter is a secondary plotter (true) or a primary one (false)
 * @param p_id The id of the parent plotter, used to build a unique function name for secondary plotters
 * @param own_id This plotter's own emit index, threaded in by the caller (replaces the former mutated id_)
 * @param indent The indentation string prepended to every emitted line
 * @return The draw command to be added to the plot's data for this function
 */
std::string GFunctionPlotter2D::footerData_(
    bool is_secondary,
    std::size_t p_id,
    std::size_t own_id,
    std::string const &indent
) const {
    EmitStream footer_data; // NOLINT(cppcoreguidelines-init-variables)

    const std::string comment = dsMarkerComment(ds_marker_);

    std::string const function_name = "func2D" + suffix(is_secondary, p_id, own_id);
    footer_data << indent << function_name << "->GetXaxis()->SetTitle(\"" << rootEscape(xAxisLabel()) << "\");"
                << '\n'
                << indent << function_name << "->GetYaxis()->SetTitle(\"" << rootEscape(yAxisLabel()) << "\");"
                << '\n'
                << indent << function_name << "->GetZaxis()->SetTitle(\"" << rootEscape(zAxisLabel()) << "\");"
                << '\n'
                << indent << function_name << "->SetNpx(" << n_samples_x_ << ");" << '\n'
                << indent << function_name << "->SetNpy(" << n_samples_y_ << ");" << '\n';

    emitRootTitle(footer_data, indent, function_name, plot_label_);

    std::string const d_a = this->drawingArguments(is_secondary);

    footer_data << indent << function_name << "->Draw(\"" << d_a << "\");"
                << comment << '\n'
                << '\n';

    return footer_data.str();
}

/******************************************************************************/
/**
 * Retrieve the current drawing arguments
 *
 * @param is_secondary Whether this plotter is a secondary plotter (true) or a primary one (false)
 * @return The ROOT draw-option string; secondary plotters get the "same" option appended
 */
std::string GFunctionPlotter2D::drawingArguments(bool is_secondary) const {
    std::string d_a;

    if(!this->drawing_arguments_.empty()) {
        d_a = this->drawing_arguments_;
    }

    if(is_secondary) {
        if(d_a.empty()) {
            d_a = "same";
        }
        else {
            d_a = d_a + ",same";
        }
    }

    return d_a;
}

// clone_() and load_() for GFunctionPlotter2D are generated by Gem::Common::GReflectiveInterfaceT
// from class_name and localMembers_().


/******************************************************************************/
} /* namespace Gem::Dietrich */
