/**
 * @file GMPISubClientParaboloidIndividualMultiD.hpp
 */

/********************************************************************************
 *
 * This file is part of the Geneva library collection. The following license
 * applies to this file:
 *
 * ------------------------------------------------------------------------------
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ------------------------------------------------------------------------------
 *
 * Note that other files in the Geneva library collection may use a different
 * license. Please see the licensing information in each file.
 *
 ********************************************************************************
 *
 * See the NOTICE file in the top-level directory of the Geneva library
 * collection for a list of contributors and copyright information.
 *
 ********************************************************************************/

#pragma once

// Global checks, defines and includes needed for all of Geneva
#include "common/GGlobalDefines.hpp"

// Standard header files go here
#include <iostream>
#include <optional>

// Boost header files go here

// Geneva header files go here
#include <courtier/GMPIHelperFunctions.hpp>
#include <geneva/genome/GGenomeBuilder.hpp>
#include <geneva/GMPISubClientIndividual.hpp>

#include <memory>

namespace Gem::Geneva {

// The MPI helper utilities moved into the Gem::Courtier namespace; pull in the types this header's
// method signatures reference.
using Gem::Courtier::MPICompletionStatus;

namespace OptimizationAlgorithms {
class GAdaptionConfigBase;
} // namespace OptimizationAlgorithms

/******************************************************************/
/**
     * This class demonstrates the functionality of GMPISubClientIndividual.
     * In the evaluate() function it will communicate to MPI sub-clients.
     * In this example we just send an example message. But in a real implementation
     * real data would be sent in order to solve the evaluation in a distributed manner.
     */
class GMPISubClientParaboloidIndividualMultiD
  : public Gem::Common::GReflectiveInterfaceT<GMPISubClientParaboloidIndividualMultiD, GMPISubClientIndividual> {
    /** @brief Make the class accessible to the GArchive serializer */
    /** @brief The GReflectiveInterfaceT mixin reaches the (empty) private localMembers_() through this shim. */
    friend struct Gem::Common::GReflectiveInterfaceAccess;

    /** @brief No serialised per-instance state -- M_PAR_MIN/M_PAR_MAX are const construction constants,
     *  never (de)serialised / loaded / compared -- so the member list is empty and
     *  serialize()/load_()/compare_()/clone_()/name_() are all generated by the mixin. */
    template <typename Self>
    auto localMembers_(this Self &) { return std::make_tuple(); }
    /**************************************************************/
public:
    /** @brief The class name, consumed by the GReflectiveInterfaceT-generated name_() and compare token. */
    static constexpr std::string_view class_name = "GMPISubClientParaboloidIndividualMultiD";

    /** @brief The default constructor */
    GMPISubClientParaboloidIndividualMultiD();

    /** @brief A standard copy constructor */
    GMPISubClientParaboloidIndividualMultiD(const GMPISubClientParaboloidIndividualMultiD &);

    static int subClientJob(MPI_Comm comm);

    /** @brief The OA-owned adaption config authoring this genome's per-parameter Gauss groups, built from
     *  the genome layout. Static (no adaptor data resides on the individual). */
    static std::shared_ptr<OptimizationAlgorithms::GAdaptionConfigBase>
    buildAdaptionConfig(const gen::GGenome &sample);

protected:
    /** @brief The evaluation hook: sum of squares of the genome (single criterion). */
    std::vector<double> evaluate() final;

private:
    /** @brief calculates the square of all parameters in this parameters set together with all sub-clients */
    [[nodiscard]] static MPICompletionStatus distributedSolveWhile(
        const std::optional<std::vector<double>> &sendVec,
        std::optional<std::vector<double>> &resultVec,
        const std::uint32_t &parsPerProc,
        const std::function<bool()> &runWhile
    );

    const double M_PAR_MIN;
    const double M_PAR_MAX;

    /** the number of parameters to optimize */
    inline const static std::uint32_t nParameters_{64};

    /** Simulated time required to calculate one parameter in this parameter set */
    inline const static std::uint32_t delayPerParameterMSec_{50};

    /** Interval for checking the result of mpi communication requests */
    inline const static std::uint32_t pollIntervalMSec_{5};

    /** Maximum time to wait before a timeout is triggered on an mpi communication request */
    inline const static std::uint32_t pollTimeoutMSec_{5000}; // 5 seconds
};

/******************************************************************/

} // namespace Gem::Geneva

