/********************************************************************************
 *
 * This file is part of the Geneva library collection. The following license
 * applies to this file:
 *
 * ------------------------------------------------------------------------------
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ------------------------------------------------------------------------------
 *
 * Note that other files in the Geneva library collection may use a different
 * license. Please see the licensing information in each file.
 *
 ********************************************************************************
 *
 * See the NOTICE file in the top-level directory of the Geneva library
 * collection for a list of contributors and copyright information.
 *
 ********************************************************************************/

#include "geneva/oa/GSimulatedAnnealing_PersonalityTraits.hpp"
#include "weft/GArchivePolymorphic.hpp" // GEM_REGISTER_ARCHIVABLE (GArchive polymorphic-pointer dispatch)
#include "common/GExpectationChecksT.hpp"
#include "geneva/GPersonalityTraits.hpp"
#include "geneva/oa/GBaseParChildPersonalityTraits.hpp"
#include <string>

GEM_REGISTER_ARCHIVABLE(Gem::Geneva::OptimizationAlgorithms::GSimulatedAnnealing_PersonalityTraits)       // NOLINT
namespace Gem::Geneva::OptimizationAlgorithms {

/******************************************************************************/
/** @brief A short identifier ("sa") suitable for storage in a std::map */
const std::string GSimulatedAnnealing_PersonalityTraits::nickname = "sa";

/******************************************************************************/
// compare_(), name_(), clone_() and load_() are generated by the
// Gem::Common::GReflectiveInterfaceT base from class_name and the empty localMembers_().

/******************************************************************************/
/**
 * @brief Retrieves the mnemonic of the optimization algorithm.
 *
 * @return The short identifier ("sa") of the simulated-annealing algorithm
 */
std::string GSimulatedAnnealing_PersonalityTraits::getMnemonic() const {
    return GSimulatedAnnealing_PersonalityTraits::nickname;
}


/******************************************************************************/

} /* namespace Gem::Geneva::OptimizationAlgorithms */
