/********************************************************************************
 *
 * This file is part of the Geneva library collection. The following license
 * applies to this file:
 *
 * ------------------------------------------------------------------------------
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ------------------------------------------------------------------------------
 *
 * Note that other files in the Geneva library collection may use a different
 * license. Please see the licensing information in each file.
 *
 ********************************************************************************
 *
 * See the NOTICE file in the top-level directory of the Geneva library
 * collection for a list of contributors and copyright information.
 *
 ********************************************************************************/

#pragma once

// Global checks, defines and includes needed for all of Geneva
#include "common/GGlobalDefines.hpp"

// Standard headers go here
#include <string>

// Geneva headers go here
#include "common/GReflectiveInterfaceT.hpp"
#include "geneva/oa/GPositionPersonalityTraits.hpp"

namespace Gem::Geneva::OptimizationAlgorithms {

/******************************************************************************/
/**
 * The one shared implementation behind the position-only personality-traits classes (Nelder-Mead,
 * CGD, parameter scan, GSA, ACO, PSO2011): each of those carries no state beyond the population
 * position its GPositionPersonalityTraits base provides, and used to repeat the identical
 * getMnemonic() / name_() / clone_() / serialize() boilerplate. A concrete traits class now only
 * supplies its identity:
 *
 * @code
 * class GNelderMead_PersonalityTraits
 *   : public GAlgorithmPersonalityTraitsT<GNelderMead_PersonalityTraits> {
 * public:
 *     static const std::string nickname;                       // "nm", defined in the .cpp
 *     static constexpr std::string_view class_name{"GNelderMead_PersonalityTraits"};
 * };
 * @endcode
 *
 * plus the usual GEM_REGISTER_ARCHIVABLE in its source file.
 *
 * Serialization note: the inherited serialize() emits the GPositionPersonalityTraits base under the
 * same NVP tag the per-class boilerplate produced, and the base slice is taken from the DERIVED type
 * (via the CRTP cast), so the archives a concrete traits class reads and writes are unchanged.
 *
 * @tparam derived_type The concrete personality-traits class (CRTP)
 */
template <typename derived_type>
class GAlgorithmPersonalityTraitsT // NOLINT(cppcoreguidelines-special-member-functions)
  : public Gem::Common::GReflectiveInterfaceT<derived_type, GPositionPersonalityTraits> {
public:
    /** @brief The default constructor */
    GAlgorithmPersonalityTraitsT() = default;
    /** @brief The copy constructor
     *  @param cp Another object of the same type whose state is copied */
    GAlgorithmPersonalityTraitsT(const GAlgorithmPersonalityTraitsT &cp) = default;
    /** @brief The standard destructor */
    ~GAlgorithmPersonalityTraitsT() override = default;

    /**
     * @brief Retrieves the mnemonic of the optimization algorithm.
     * @return The short mnemonic string (derived_type::nickname) identifying the algorithm
     */
    [[nodiscard]] std::string getMnemonic() const override {
        return derived_type::nickname;
    }

    // name_(), clone_(), load_(), compare_() and serialize() are generated by the
    // Gem::Common::GReflectiveInterfaceT base, keyed on derived_type (its class_name +
    // localMembers_). Because the generated load_/compare_ are per concrete type,
    // g_convert_and_compare rejects a foreign traits type on its own -- the former
    // shared exact-type check in GPositionPersonalityTraits is no longer needed.
};

/******************************************************************************/

} /* namespace Gem::Geneva::OptimizationAlgorithms */
