/********************************************************************************
 *
 * This file is part of the Geneva library collection. The following license
 * applies to this file:
 *
 * ------------------------------------------------------------------------------
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ------------------------------------------------------------------------------
 *
 * Note that other files in the Geneva library collection may use a different
 * license. Please see the licensing information in each file.
 *
 ********************************************************************************
 *
 * See the NOTICE file in the top-level directory of the Geneva library
 * collection for a list of contributors and copyright information.
 *
 ********************************************************************************/

#pragma once

// Global checks, defines and includes needed for all of Geneva
#include "common/GGlobalDefines.hpp"

// Standard headers go here
#include <tuple>

// Boost headers go here

// Geneva headers go here
#include "geneva/oa/GBaseParChildPersonalityTraits.hpp"
#include "geneva/oa/GParetoTag.hpp"

namespace Gem::Geneva::OptimizationAlgorithms {

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * This class adds variables and functions to GPersonalityTraits that are specific to the dimension-aware
 * adaptive evolutionary algorithm ("ea"). It is a near-twin of GSepCmaEvolutionStrategy_PersonalityTraits
 * (same pareto-front tag) but carries its own nickname so it self-registers a distinct mnemonic.
 */
class GEvolutionaryAlgorithm_PersonalityTraits // NOLINT(cppcoreguidelines-special-member-functions)
  : public Gem::Common::GReflectiveInterfaceT<GEvolutionaryAlgorithm_PersonalityTraits, GBaseParChildPersonalityTraits>
  , public GParetoTag {
    ///////////////////////////////////////////////////////////////////////
    // Gem::Weft::access default-constructs this concrete type on load;
    // GReflectiveInterfaceAccess lets the GReflectiveInterfaceT base reach localMembers_(). GParetoTag
    // is a plain mixin (no quartet); its is_on_pareto_front_ rides in localMembers_.
    friend struct Gem::Common::GReflectiveInterfaceAccess;

    /** @brief Single declaration of this class'es local data members */
    template <typename Self>
    auto localMembers_(this Self &self) {
        return std::make_tuple(Gem::Common::make_member("is_on_pareto_front_", self.is_on_pareto_front_));
    }
    ///////////////////////////////////////////////////////////////////////

public:
    /** @brief The class name, consumed by the GReflectiveInterfaceT-generated name_() / compare token. */
    static constexpr std::string_view class_name = "GEvolutionaryAlgorithm_PersonalityTraits";

    /** @brief An easy identifier for the class */
    static const std::string nickname; // Initialized in the .cpp definition file

    /** @brief The default constructor */
    GEvolutionaryAlgorithm_PersonalityTraits() = default;
    /** @brief The copy constructor */
    GEvolutionaryAlgorithm_PersonalityTraits(
        const GEvolutionaryAlgorithm_PersonalityTraits &
    ) = default;
    /** @brief The standard destructor */
    ~GEvolutionaryAlgorithm_PersonalityTraits() override = default;

    // The pareto-front tag (isOnParetoFront / resetParetoTag / setIsNotOnParetoFront)
    // is inherited from the GParetoTag mixin; the member is serialized below under
    // its historical NVP name.

    /**
     * @brief Retrieves the mnemonic of the optimization algorithm.
     * @return The short mnemonic string identifying the adaptive-evolutionary-algorithm personality
     */
    [[nodiscard]] std::string getMnemonic() const override;

protected:
    /***************************************************************************/
    // load_(), compare_(), name_() and clone_() are generated by the
    // Gem::Common::GReflectiveInterfaceT base from class_name and localMembers_().

    /***************************************************************************/
};

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/

} /* namespace Gem::Geneva::OptimizationAlgorithms */

