/********************************************************************************
 *
 * This file is part of the Geneva library collection. The following license
 * applies to this file:
 *
 * ------------------------------------------------------------------------------
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ------------------------------------------------------------------------------
 *
 * Note that other files in the Geneva library collection may use a different
 * license. Please see the licensing information in each file.
 *
 ********************************************************************************
 *
 * See the NOTICE file in the top-level directory of the Geneva library
 * collection for a list of contributors and copyright information.
 *
 ********************************************************************************/

#include "geneva/individuals/GFunctionIndividual.hpp"
#include "geneva/individuals/GBenchmarkFunctions.hpp"
#include "common/GCommonEnums.hpp"
#include "common/GCommonHelperFunctionsT.hpp"
#include "common/GCommonInterfaceT.hpp"
#include "common/GCommonMathHelperFunctionsT.hpp"
#include "common/GExceptions.hpp"
#include "common/GExpectationChecksT.hpp"
#include "common/GFactoryT.hpp"
#include "common/GLogger.hpp"
#include "common/GParserBuilder.hpp"
#include "geneva/GMultiConstraintT.hpp"
#include "geneva/ind/GGenome.hpp"
#include "geneva/ind/GGenomeBuilder.hpp"
#include "geneva/oa/GAdaption.hpp"
#include "geneva/oa/GAdaptionConfig.hpp"
#include "geneva/par/GOptimizableEntityFactory.hpp"
#include "geneva/par/GOptimizableEntityMultiConstraint.hpp"
#include "hap/GRandomT.hpp"
#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <filesystem>
#include <functional>
#include <iostream>
#include <istream>
#include <memory>
#include <ostream>
#include <ranges>
#include <tuple>
#include <utility>
#include <vector>

BOOST_CLASS_EXPORT_IMPLEMENT(Gem::Geneva::Individuals::GFunctionIndividual)        // NOLINT
BOOST_CLASS_EXPORT_IMPLEMENT(Gem::Geneva::Individuals::GFunctionIndividualFactory) // NOLINT
BOOST_CLASS_EXPORT_IMPLEMENT(Gem::Geneva::Individuals::GDoubleSumConstraint)       // NOLINT
BOOST_CLASS_EXPORT_IMPLEMENT(Gem::Geneva::Individuals::GDoubleSumGapConstraint)    // NOLINT
BOOST_CLASS_EXPORT_IMPLEMENT(Gem::Geneva::Individuals::GSphereConstraint)          // NOLINT

namespace Gem::Geneva::Individuals {

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * @brief Initialization with the constant.
 *
 * @param c The target constant against which the sum of the parameters is compared
 */
GDoubleSumConstraint::GDoubleSumConstraint(const double &c)
  : c_(c) { /* nothing */
}

/******************************************************************************/
// compare_(), load_(), name_() and clone_() for GDoubleSumConstraint are generated by
// the Gem::Common::GReflectiveInterfaceT base from class_name and localMembers_().

/******************************************************************************/
/**
 * @brief Adds local configuration options to a GParserBuilder object.
 *
 * @param gpb The GParserBuilder object to which configuration options should be added
 */
void GDoubleSumConstraint::addConfigurationOptions_(Gem::Common::GParserBuilder &gpb) {
    // Call our parent class'es function
    gen::GOptimizableEntityConstraint::addConfigurationOptions_(gpb);
}

/******************************************************************************/
/**
 * @brief Checks whether a given individual is valid (its parameter sum is below the target constant).
 *
 * @param p A pointer to the individual whose floating-point parameters are summed and checked
 * @return 0 if the parameter sum is below the constant c_; otherwise sum/c_ as a penalty measure
 */
double GDoubleSumConstraint::check_(const gen::GOptimizableEntity *p) const {
    std::vector<double> par_vec;
    p->streamlineFP(par_vec);

    const double sum = std::ranges::fold_left(par_vec, 0., std::plus{});

    if(sum < c_) {
        return 0.;
    }
            return sum / c_;
   
}

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * @brief Initialization with the constant and the allowed gap around it.
 *
 * @param c The target constant around which the sum of the parameters should lie
 * @param gap The half-width of the allowed corridor [c - gap, c + gap] for the parameter sum
 */
GDoubleSumGapConstraint::GDoubleSumGapConstraint(const double &c, const double &gap)
  : c_(c)
  , gap_(gap) { /* nothing */
}

/******************************************************************************/
// compare_(), load_(), name_() and clone_() for GDoubleSumGapConstraint are generated by
// the Gem::Common::GReflectiveInterfaceT base from class_name and localMembers_().

/******************************************************************************/
/**
 * @brief Adds local configuration options to a GParserBuilder object.
 *
 * @param gpb The GParserBuilder object to which configuration options should be added
 */
void GDoubleSumGapConstraint::addConfigurationOptions_(Gem::Common::GParserBuilder &gpb) {
    // Call our parent class'es function
    gen::GOptimizableEntityConstraint::addConfigurationOptions_(gpb);
}

/******************************************************************************/
/**
 * @brief Checks whether a given individual is valid (its parameter sum lies within the allowed corridor).
 *
 * @param p A pointer to the individual whose floating-point parameters are summed and checked
 * @return 0 if the parameter sum is within [c_ - gap_, c_ + gap_]; otherwise 1 + |sum - c_| / c_ as a penalty measure
 */
double GDoubleSumGapConstraint::check_(const gen::GOptimizableEntity *p) const {
    std::vector<double> par_vec;
    p->streamlineFP(par_vec);

    const double sum = std::ranges::fold_left(par_vec, 0., std::plus{});

    // Is the sum in the allowed corridor ?
    if(sum >= (c_ - gap_) && sum <= (c_ + gap_)) {
        return 0.;
    }
            return 1. + (fabs(sum - c_) / c_);
   
}

/******************************************************************************/
/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * @brief Initialization with the diameter.
 *
 * @param diameter The maximum allowed Euclidean norm of the parameter vector
 */
GSphereConstraint::GSphereConstraint(const double &diameter)
  : diameter_(diameter) { /* nothing */
}

/******************************************************************************/
// compare_(), load_(), name_() and clone_() for GSphereConstraint are generated by
// the Gem::Common::GReflectiveInterfaceT base from class_name and localMembers_().

/******************************************************************************/
/**
 * @brief Adds local configuration options to a GParserBuilder object.
 *
 * @param gpb The GParserBuilder object to which configuration options should be added
 */
void GSphereConstraint::addConfigurationOptions_(Gem::Common::GParserBuilder &gpb) {
    // Call our parent class'es function
    gen::GOptimizableEntityConstraint::addConfigurationOptions_(gpb);
}

/******************************************************************************/
/**
 * @brief Checks whether a given individual is valid (its parameter vector lies inside the sphere).
 *
 * @param p A pointer to the individual whose floating-point parameters form the vector whose norm is checked
 * @return 0 if the Euclidean norm of the parameters is at most diameter_; otherwise (norm / diameter_) squared as a penalty measure
 */
double GSphereConstraint::check_(const gen::GOptimizableEntity *p) const {
    std::vector<double> par_vec;
    p->streamlineFP(par_vec);

    const double sum = sqrt(std::ranges::fold_left(
        par_vec | std::views::transform([](double val) { return Gem::Common::gsquared(val); }),
        0.,
        std::plus{}));

    if(sum <= diameter_) {
        return 0.;
    }
            return Gem::Common::gsquared(sum / diameter_);
   
}


/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * @brief Initialization with the desired demo function.
 *
 * @param d_f The id of the demo (benchmark) function to optimize
 */
GFunctionIndividual::GFunctionIndividual(const solverFunction &d_f)
  : demo_function_(d_f) { /* nothing */
}

/******************************************************************************/
/**
 * @brief Allows external entities to set the fitness.
 *
 * @param result_vec A vector of result values to assign as this individual's fitness
 */
/******************************************************************************/
/**
 * @brief Adds local configuration options to a GParserBuilder object.
 *
 * @param gpb The GParserBuilder object to which configuration options should be added
 */
void GFunctionIndividual::addConfigurationOptions_(Gem::Common::GParserBuilder &gpb) {
    // Call our parent class'es function. The demo_function option (and all other configurable values)
    // is registered by the static describeConfig() hook and applied via applyConfig(), so the generic
    // GIndividualFactory<GFunctionIndividual> handles all of this individual's configuration.
    gen::GGenome::addConfigurationOptions_(gpb);
}

/******************************************************************************/
/**
 * @brief Allows to set the demo function.
 *
 * @param d_f The id of the demo (benchmark) function to optimize
 */
void GFunctionIndividual::setDemoFunction(solverFunction d_f) {
    demo_function_ = d_f;
}

/******************************************************************************/
/**
 * @brief Allows to retrieve the demo function.
 *
 * @return The id of the currently selected demo function
 */
solverFunction GFunctionIndividual::getDemoFunction() const {
    return demo_function_;
}

/******************************************************************************/
/**
 * @brief Allows to cross check the parameter size.
 *
 * @return The number of doubles stored in this object
 */
std::size_t GFunctionIndividual::getParameterSize() const {
    // Retrieve the parameters
    std::vector<double> par_vec;
    this->streamline(par_vec);
    return par_vec.size();
}

/******************************************************************************/
/**
 * @brief Applies modifications to this object. This is needed for testing purposes.
 *
 * @return A boolean which indicates whether modifications were made
 */
bool GFunctionIndividual::modify_GUnitTests_() {
#ifdef GEM_TESTING

    bool result = false;

    // Call the parent classes' functions
    if(gen::GGenome::modify_GUnitTests_()) {
        result = true;
    }

    // Change the parameter settings
    result = true;

    return result;

#else /* GEM_TESTING */ // If this function is called when GEM_TESTING isn't set, throw
    Gem::Common::condnotset("GFunctionIndividual::modify_GUnitTests", "GEM_TESTING");
    return false;
#endif                  /* GEM_TESTING */
}

/******************************************************************************/
/**
 * @brief Performs self-tests that are expected to succeed. This is needed for testing purposes.
 */
void GFunctionIndividual::specificTestsNoFailureExpected_GUnitTests_() {
#ifdef GEM_TESTING
    using namespace Gem::Geneva;

    // Call the parent classes' functions
    gen::GGenome::specificTestsNoFailureExpected_GUnitTests_();

    //------------------------------------------------------------------------------
    //------------------------------------------------------------------------------

#else /* GEM_TESTING */ // If this function is called when GEM_TESTING isn't set, throw
    Gem::Common::condnotset(
        "GFunctionIndividual::specificTestsNoFailureExpected_GUnitTests",
        "GEM_TESTING"
    );
#endif                  /* GEM_TESTING */
}

/******************************************************************************/
/**
 * @brief Performs self tests that are expected to fail. This is needed for testing purposes.
 */
void GFunctionIndividual::specificTestsFailuresExpected_GUnitTests_() {
#ifdef GEM_TESTING
    using namespace Gem::Geneva;

    // Call the parent classes' functions
    gen::GGenome::specificTestsFailuresExpected_GUnitTests_();

    //------------------------------------------------------------------------------
    //------------------------------------------------------------------------------

#else /* GEM_TESTING */ // If this function is called when GEM_TESTING isn't set, throw
    Gem::Common::condnotset(
        "GFunctionIndividual::specificTestsFailuresExpected_GUnitTests",
        "GEM_TESTING"
    );
#endif                  /* GEM_TESTING */
}

/******************************************************************************/
/**
 * @brief The evaluation hook: evaluates the selected benchmark function on the individual's parameters.
 *
 * Reads the demo function the factory set on the individual (via getDemoFunction()) and the external
 * parameter values (via streamline()) -- only through public accessors -- and returns the raw fitness.
 * Delegates the maths to Gem::Geneva::Benchmarks::eval() (shared CPU/CUDA implementations, all 15
 * solverFunction IDs 0-14). The (function, dimension) validity is a configuration invariant checked once in
 * applyConfig(), so this hot path carries no validation.
 *
 * @return The raw fitness as a one-element vector (a single-criterion problem)
 */
std::vector<double> GFunctionIndividual::evaluate() {
    std::vector<double> par_vec;
    this->streamline(par_vec);

    return {gbm::eval(
        static_cast<int>(this->getDemoFunction()),
        par_vec.data(),
        static_cast<int>(par_vec.size())
    )};
}

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * @brief Registers the config-file options, binding them to the passed Config.
 *
 * Registers the parameter-dimension / bounds / adaptor options plus the demo_function option, binding
 * each to a field of the passed Config (filled on parse).
 *
 * @param gpb The GParserBuilder object with which the configuration file options are registered
 * @param c The Config struct whose fields are bound to the registered options (filled on parse)
 */
// NOLINTNEXTLINE(readability-function-size) -- one coherent config-registration sweep binding every GFunctionIndividual::Config field; splitting would scatter the option list
void GFunctionIndividual::describeConfig(Gem::Common::GParserBuilder &gpb, Config &c) {
    std::string comment; // NOLINT(cppcoreguidelines-init-variables)

    comment = "";
    comment += "The probability for random adaption of values in evolutionary algorithms;";
    gpb.registerFileParameter<double>(
        "ad_prob", c.ad_prob, GFI_DEF_ADPROB, Gem::Common::VAR_IS_ESSENTIAL, comment
    );

    comment = "";
    comment +=
        "Determines the rate of adaption of ad_prob. Set to 0, if you do not need this feature;";
    gpb.registerFileParameter<double>(
        "adapt_ad_prob", c.adapt_ad_prob, GFI_DEF_ADAPTADPROB, Gem::Common::VAR_IS_ESSENTIAL, comment
    );

    comment = "";
    comment += "The lower allowed boundary for ad_prob-variation;";
    gpb.registerFileParameter<double>(
        "min_ad_prob", c.min_ad_prob, GFI_DEF_MINADPROB, Gem::Common::VAR_IS_ESSENTIAL, comment
    );

    comment = "";
    comment += "The upper allowed boundary for ad_prob-variation;";
    gpb.registerFileParameter<double>(
        "max_ad_prob", c.max_ad_prob, GFI_DEF_MAXADPROB, Gem::Common::VAR_IS_ESSENTIAL, comment
    );

    comment = "";
    comment += "The number of successful calls to an adaptor after which adaption;";
    comment += "of mutation parameters takes place (e.g sigma-variation in gauss mutation);";
    gpb.registerFileParameter<std::uint32_t>(
        "adaption_threshold", c.adaption_threshold, GFI_DEF_ADAPTIONTHRESHOLD,
        Gem::Common::VAR_IS_ESSENTIAL, comment
    );

    comment = "";
    comment += "Whether to use a double gaussion for the adaption of parmeters in ES;";
    gpb.registerFileParameter<bool>(
        "use_bi_gaussian", c.use_bi_gaussian, GFI_DEF_USEBIGAUSSIAN, Gem::Common::VAR_IS_ESSENTIAL,
        comment
    );

    comment = "";
    comment +=
        "The sigma for gauss-adaption in ES;(or the sigma of the left peak of a double gaussian);";
    gpb.registerFileParameter<double>(
        "sigma1", c.sigma1, GFI_DEF_SIGMA1, Gem::Common::VAR_IS_ESSENTIAL, comment
    );

    comment = "";
    comment += "Influences the self-adaption of gauss-mutation in ES;";
    gpb.registerFileParameter<double>(
        "sigma_sigma1", c.sigma_sigma1, GFI_DEF_SIGMASIGMA1, Gem::Common::VAR_IS_ESSENTIAL, comment
    );

    comment = "";
    comment += "The minimum value of sigma1;";
    gpb.registerFileParameter<double>(
        "min_sigma1", c.min_sigma1, GFI_DEF_MINSIGMA1, Gem::Common::VAR_IS_ESSENTIAL, comment
    );

    comment = "";
    comment += "The maximum value of sigma1;";
    gpb.registerFileParameter<double>(
        "max_sigma1", c.max_sigma1, GFI_DEF_MAXSIGMA1, Gem::Common::VAR_IS_ESSENTIAL, comment
    );

    comment = "";
    comment += "The sigma of the right peak of a double gaussian (if any);";
    gpb.registerFileParameter<double>(
        "sigma2", c.sigma2, GFI_DEF_SIGMA2, Gem::Common::VAR_IS_ESSENTIAL, comment
    );

    comment = "";
    comment += "Influences the self-adaption of gauss-mutation in ES;";
    gpb.registerFileParameter<double>(
        "sigma_sigma2", c.sigma_sigma2, GFI_DEF_SIGMASIGMA2, Gem::Common::VAR_IS_ESSENTIAL, comment
    );

    comment = "";
    comment += "The minimum value of sigma2;";
    gpb.registerFileParameter<double>(
        "min_sigma2", c.min_sigma2, GFI_DEF_MINSIGMA2, Gem::Common::VAR_IS_ESSENTIAL, comment
    );

    comment = "";
    comment += "The maximum value of sigma2;";
    gpb.registerFileParameter<double>(
        "max_sigma2", c.max_sigma2, GFI_DEF_MAXSIGMA2, Gem::Common::VAR_IS_ESSENTIAL, comment
    );

    comment = "";
    comment += "The start distance between both peaks used for bi-gaussian mutations in ES;";
    gpb.registerFileParameter<double>(
        "delta", c.delta, GFI_DEF_DELTA, Gem::Common::VAR_IS_ESSENTIAL, comment
    );

    comment = "";
    comment += "The width of the gaussian used for mutations of the delta parameter;";
    gpb.registerFileParameter<double>(
        "sigma_delta", c.sigma_delta, GFI_DEF_SIGMADELTA, Gem::Common::VAR_IS_ESSENTIAL, comment
    );

    comment = "";
    comment += "The minimum allowed value of delta;";
    gpb.registerFileParameter<double>(
        "min_delta", c.min_delta, GFI_DEF_MINDELTA, Gem::Common::VAR_IS_ESSENTIAL, comment
    );

    comment = "";
    comment += "The maximum allowed value of delta;";
    gpb.registerFileParameter<double>(
        "max_delta", c.max_delta, GFI_DEF_MAXDELTA, Gem::Common::VAR_IS_ESSENTIAL, comment
    );

    comment = "";
    comment += "The number of dimensions used for the demo function;";
    gpb.registerFileParameter<std::size_t>(
        "par_dim", c.par_dim, GFI_DEF_PARDIM, Gem::Common::VAR_IS_ESSENTIAL, comment
    );

    comment = "";
    comment += "The lower boundary of the initialization range for parameters;";
    gpb.registerFileParameter<double>(
        "min_var", c.min_var, GFI_DEF_MINVAR, Gem::Common::VAR_IS_ESSENTIAL, comment
    );

    comment = "";
    comment += "The upper boundary of the initialization range for parameters;";
    gpb.registerFileParameter<double>(
        "max_var", c.max_var, GFI_DEF_MAXVAR, Gem::Common::VAR_IS_ESSENTIAL, comment
    );

    comment = "";
    comment +=
        "Selects the flat-genome structure, along two axes -- bounded-vs-unbounded and shared-vs-per-"
        "parameter adaptor group;(0) unbounded, one shared group;(1) bounded, one shared group;(2) "
        "unbounded, one group per parameter;(3) bounded, one group per parameter;";
    gpb.registerFileParameter<parameterType>(
        "parameter_type", c.p_t, GFI_DEF_PARAMETERTYPE, Gem::Common::VAR_IS_ESSENTIAL, comment
    );

    comment = "";
    comment += "Specifies which benchmark function to minimise (maximise for NEGPARABOLA), by integer ID;";
    gpb.registerFileParameter<solverFunction>(
        "demo_function", c.demo_function, GO_DEF_EVALFUNCTION, Gem::Common::VAR_IS_ESSENTIAL, comment
    );
}

/******************************************************************************/
/**
 * @brief Builds the flat genome's STRUCTURE only.
 *
 * The five parameter-type modes differ in constrained-vs-unbounded and
 * whether the parameters share one adaption group (a *collection*) or each carry their own (a collection
 * of *objects* / individual objects). The configured Gauss / bi-Gauss adaptor settings live on the
 * OA-owned config (see buildAdaptionConfig()), not in the genome layout. The start value is the lower
 * perimeter; the optimization algorithm random-initialises within [min, max].
 *
 * @param c The Config supplying the parameter dimension (par_dim), the init range (min_var, max_var) and the parameter-object type (p_t)
 * @return The flat genome structure (GenomeData) for the selected parameter type
 */
gen::GenomeData GFunctionIndividual::buildGenome(const Config &c) {
    const std::size_t n_data = c.par_dim;
    const double min_v = c.min_var;
    const double max_v = c.max_var;

    gen::GGenomeBuilder b;
    switch(c.p_t) {
    case parameterType::UNBOUNDED_SHARED: { // unbounded, one shared group
        b.addDoublePlainGroup(n_data, min_v, max_v);
    } break;

    case parameterType::BOUNDED_SHARED: { // bounded, one shared group
        b.addDoubleGroup(n_data, min_v, max_v);
    } break;

    case parameterType::UNBOUNDED_PER_PARAMETER: { // unbounded, a group per parameter
        for(std::size_t i = 0; i < n_data; i++) {
            b.addDouble(min_v).perimeter(min_v, max_v);
        }
    } break;

    case parameterType::BOUNDED_PER_PARAMETER: { // bounded, a group per parameter
        for(std::size_t i = 0; i < n_data; i++) {
            b.addDouble(min_v, min_v, max_v);
        }
    } break;

    default: {
        throw geneva_exception(
            g_error_streamer(DO_LOG, Gem::Common::timeAndPlace())
            << "In GFunctionIndividual::buildGenome(): Error!"
            << "Found invalid parameter_type: " << c.p_t << '\n'
        );
    }
    }

    return b.build();
}

/******************************************************************************/
/**
 * @brief Builds the OA-owned adaption configuration for a genome produced by this factory.
 *
 * Every double group (one shared group for the collection modes, one per parameter for the object
 * modes) receives the configured single-Gauss or bi-Gauss adaptor.
 *
 * @param sample A sample flat genome whose group structure the adaption config is built against
 * @param c The Config supplying the adaptor parameters (sigmas, ad_prob, bi-gaussian flag, ...)
 * @return A shared pointer to the populated OA-owned adaption configuration
 */
std::shared_ptr<OptimizationAlgorithms::GAdaptionConfigBase>
GFunctionIndividual::buildAdaptionConfig(const gen::GGenome &sample, const Config &c) {
    namespace oa = Gem::Geneva::OptimizationAlgorithms;
    auto cfg = oa::makeAdaptionConfig<oa::GAdaptionConfigBase>(sample);
    for(std::size_t i = 0; i < cfg->doubleGroups().size(); i++) {
        if(c.use_bi_gaussian) {
            cfg->groupDouble(i).biGauss(
                c.sigma1, c.sigma_sigma1, c.min_sigma1, c.max_sigma1,
                c.sigma2, c.sigma_sigma2, c.min_sigma2, c.max_sigma2,
                c.delta, c.sigma_delta, c.min_delta, c.max_delta,
                c.ad_prob, /* use_symmetric_sigmas = */ false, c.adapt_ad_prob,
                c.adaption_threshold
            );
        }
        else {
            cfg->groupDouble(i).gauss(
                c.sigma1, c.sigma_sigma1, c.min_sigma1, c.max_sigma1,
                c.ad_prob, c.adapt_ad_prob, c.adaption_threshold,
                Gem::Geneva::adaptionMode::WITHPROBABILITY, c.min_ad_prob, c.max_ad_prob
            );
        }
    }
    return cfg;
}

/******************************************************************************/
/**
 * @brief Per-object post-config hook: applies the (non-genome) demo function to a produced individual.
 *
 * The demo function lives in the Config and is applied here, the symmetric companion to
 * buildAdaptionConfig().
 *
 * @param ind The individual to configure (mutated in place)
 * @param c The Config supplying the demo (benchmark) function to apply
 */
void GFunctionIndividual::applyConfig(GFunctionIndividual &ind, const Config &c) {
    ind.setDemoFunction(c.demo_function);

    // Validate the (function, dimension) combination once, at configuration time -- a few benchmark
    // functions are only defined for at least two dimensions (with fewer, e.g. Rosenbrock's sum has no
    // terms and would silently return 0). This is a configuration invariant, not a per-evaluation
    // concern, so it is enforced here for every build (release included), off the hot evaluate() path.
    // The genome has already been installed on ind (postProcess_ / buildConfigured set it before this).
    if(ind.getParameterSize() < 2 &&
       (c.demo_function == solverFunction::ROSENBROCK || c.demo_function == solverFunction::ACKLEY)) {
        throw geneva_exception(
            g_error_streamer(DO_LOG, Gem::Common::timeAndPlace())
            << "In GFunctionIndividual::applyConfig(): function " << static_cast<int>(c.demo_function)
            << " requires at least 2 dimensions, but the genome has only " << ind.getParameterSize()
            << '\n'
        );
    }
}

/******************************************************************************/
/**
 * @brief Reads a GFunctionIndividual config file into a Config.
 *
 * Used by callers that build individuals directly rather than through the factory (e.g. the
 * dimension-sweeping GOptimizationBenchmark / CUDA benchmark, which need a different genome dimension
 * per measurement row).
 *
 * @param configFile The path to the configuration file to read
 * @return A Config struct populated from the configuration file
 */
GFunctionIndividual::Config GFunctionIndividual::readConfig(std::filesystem::path const &configFile) {
    Config c;
    Gem::Common::GParserBuilder gpb;
    describeConfig(gpb, c);

    if(not gpb.parseConfigFile(configFile)) {
        throw geneva_exception(
            g_error_streamer(DO_LOG, Gem::Common::timeAndPlace())
            << "In GFunctionIndividual::readConfig(): Error!" << '\n'
            << "Could not parse configuration file " << configFile.string() << '\n'
        );
    }

    return c;
}

/******************************************************************************/
/**
 * @brief Builds an individual fully configured the way the factory's get_as<>() would, but with a caller-supplied genome dimension.
 *
 * The genome dimension is taken from @p c (which the caller may have overridden) rather than from the
 * config file. Mirrors the factory's getObject_ + describeLocalOptions_ + parse + postProcess_
 * sequence: the base GOptimizableEntity options (eval_policy, maxmode, validity thresholds, ...) are
 * registered and applied from @p configFile, the genome structure comes from buildGenome(c), and the
 * demo function from applyConfig(). The Config-shaping keys are bound to a throwaway Config so they
 * don't trip the unknown-key diagnostic -- the caller's @p c drives the genome instead.
 *
 * @param c The Config driving the genome structure (e.g. an overridden par_dim) and the demo function
 * @param configFile The path to the configuration file from which the base GOptimizableEntity options are parsed
 * @return A shared pointer to the newly created, fully configured GFunctionIndividual
 */
std::shared_ptr<GFunctionIndividual>
GFunctionIndividual::buildConfigured(const Config &c, std::filesystem::path const &configFile) {
    auto ind = std::make_shared<GFunctionIndividual>();

    Gem::Common::GParserBuilder gpb;
    Config sink;
    describeConfig(gpb, sink);          // bind the genome-shaping keys (suppresses unknown-key noise)
    ind->addConfigurationOptions(gpb);  // bind the base GOptimizableEntity options to this individual
    if(not gpb.parseConfigFile(configFile)) {
        throw geneva_exception(
            g_error_streamer(DO_LOG, Gem::Common::timeAndPlace())
            << "In GFunctionIndividual::buildConfigured(): Error!" << '\n'
            << "Could not parse configuration file " << configFile.string() << '\n'
        );
    }

    ind->setGenome(buildGenome(c));
    applyConfig(*ind, c);
    return ind;
}

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * @brief Provide an easy way to print the individual's content.
 *
 * @param s The output stream that is returned (the parameter dump itself is written to std::cout)
 * @param f The GFunctionIndividual whose raw fitness and parameter values are printed
 * @return The std::ostream object passed in as @p s
 */
std::ostream &operator<<(std::ostream &s, const Gem::Geneva::Individuals::GFunctionIndividual &f) {
    std::vector<double> par_vec;
    f.streamline(par_vec);

    std::cout << '\n' << "Raw fitness: " << f.raw_fitness(0) << '\n' << '\n';
    std::size_t pos = 0;
    std::cout << "Parameter values of best individual:" << '\n';
    for(const auto &val : par_vec) {
        std::cout << pos++ << ": " << val << '\n';
    }
    std::cout << '\n';

    return s;
}

/******************************************************************************/
/**
 * @brief Provide an easy way to print the individual's content through a smart-pointer.
 *
 * @param s The output stream that is returned (the parameter dump itself is written to std::cout)
 * @param f_ptr A shared pointer to the GFunctionIndividual whose content is printed (dereferenced internally)
 * @return The std::ostream object passed in as @p s
 */
std::ostream &operator<<(std::ostream &s, const std::shared_ptr<Gem::Geneva::Individuals::GFunctionIndividual>& f_ptr) {
    return operator<<(s, *f_ptr);
}

/******************************************************************************/

} /* namespace Gem::Geneva::Individuals */
