/*
 * This file is part of the Geneva library collection.
 *
 * See the NOTICE file in the top-level directory of the Geneva library
 * collection for a list of contributors and copyright information.
 *
 * The following license applies to the code IN THIS FILE:
 *
 * ***************************************************************************
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * ***************************************************************************
 *
 * NOTE THAT THE BOOST-LICENSE DOES NOT APPLY TO ANY OTHER FILES OF THE
 * GENEVA LIBRARY, UNLESS THIS IS EXPLICITLY STATED IN THE CORRESPONDING FILE!
 */

#pragma once

// Global checks, defines and includes needed for all of Geneva
#include "common/GGlobalDefines.hpp"

// Standard header files go here

#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <exception>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <memory>
#include <mutex>
#include <source_location>
#include <sstream>
#include <string>
#include <time.h>
#include <tuple>
#include <vector>

// Boost header files go here

// Geneva header files go here
#include "common/GCommonEnums.hpp"
#include "common/GExceptions.hpp"
#include "common/GSingletonT.hpp"
#include "common/GTupleIO.hpp"

namespace Gem::Common {

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * This class defines the interface of log targets, i.e. targets for the logging of
 * messages through the GLogStreamer class. Essentially all that is needed is
 * the log function. Pointers to this class are stored in the GLogStreamer. They
 * point to objects of the GConsoleLogger or GFileLogger classes, or other log targets
 * defined by the user.
 */
class GBaseLogTarget {
public:
    /*************************************************************************/
    // Defaulted or deleted constructors, destructor and assignment operators

    GBaseLogTarget() = default;
    GBaseLogTarget(GBaseLogTarget const &) = default;
    GBaseLogTarget(GBaseLogTarget &&) = default;

    virtual ~GBaseLogTarget() = default;

    GBaseLogTarget &operator=(GBaseLogTarget const &) = default;
    GBaseLogTarget &operator=(GBaseLogTarget &&) = default;

    /*************************************************************************/

    /**
     * @brief The logging interface
     *
     * @param message The log message to be emitted by the target
     */
    virtual void log(std::string const &message) const = 0;

    /**
     * @brief Logs a message together with information about its source
     *
     * @param message The log message to be emitted by the target
     * @param extension An identifier of the logging source (e.g. appended to a file name)
     */
    virtual void logWithSource(std::string const &message, std::string const &extension) const = 0;
};

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * The console logger writes log messages to the console.
 */
class GConsoleLogger : public GBaseLogTarget {
public:
    /*************************************************************************/
    // Defaulted or deleted constructors, destructor and assignment operators
    // rule of five

    GConsoleLogger() = default;
    GConsoleLogger(GConsoleLogger const &) = delete;
    GConsoleLogger(GConsoleLogger &&) = default;
    ~GConsoleLogger() override = default;

    GConsoleLogger &operator=(GConsoleLogger const &) = delete;
    GConsoleLogger &operator=(GConsoleLogger &&) = default;

    /*************************************************************************/

    /**
     * @brief Implements the logging to the console
     *
     * @param message The log message to be written to the console
     */
    void log(std::string const &msg) const override;

    /**
     * @brief Writes a message to the console, prefixed with its source specifier
     *
     * @param message The log message to be written to the console
     * @param extension An identifier of the logging source, emitted as a textual prefix
     */
    void logWithSource(std::string const &msg, std::string const &extension) const override;
};

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * The file logger writes log messages to a file.
 */
class GFileLogger : public GBaseLogTarget {
public:
    /**
     * @brief This constructor accepts a path to a log-file name as argument
     *
     * @param p The filesystem path of the log file to write to
     */
    explicit GFileLogger(std::filesystem::path const &p);

    /*************************************************************************/
    // Defaulted or deleted constructors, destructor and assignment operators
    // rule of five

    GFileLogger() = default;
    GFileLogger(GFileLogger const &) = delete;
    GFileLogger(GFileLogger &&) = default;
    ~GFileLogger() override = default;

    GFileLogger &operator=(GFileLogger const &) = delete;
    GFileLogger &operator=(GFileLogger &&) = default;

    /*************************************************************************/

    /**
     * @brief Implements logging to a file on disk
     *
     * @param message The log message to be appended to the file
     */
    void log(std::string const &msg) const override;

    /**
     * @brief Logs to a file whose name is extended with the source identifier
     *
     * @param message The log message to be appended to the file
     * @param extension An identifier of the logging source, appended (with an underscore) to the file name
     */
    void logWithSource(std::string const &msg, std::string const &extension) const override;

private:
    std::string fname_ = "Geneva-Library-Collection.log"; ///< The name of the log file
    mutable bool first_ = true; ///< Indicates whether any logging has already been done
};

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * This class serves as the front end of the logging infrastructure. An object of
 * this type is accessible through a singleton to all entities in the program.
 * Upon invocation of the streaming operator it produces an object which is supposed
 * to handle the rest of the work, either using the log targets stored in the
 * GLogger object or letting manipulators output the work.
 *
 * @tparam S The streamer type ("S") instantiated on each streaming operation (typically GLogStreamer)
 */
template <class S> // "S" means "streamer"
class GLogger {
public:
    /***************************************************************************/
    // Defaulted or deleted constructors / destructor and assignment operators
    // Rule of five

    GLogger() = default;
    GLogger(GLogger<S> const &) = delete;
    GLogger(GLogger<S> &&) noexcept(false) = default;
    ~GLogger() = default;

    GLogger<S> &operator=(GLogger<S> const &) = delete;
    GLogger<S> &operator=(GLogger<S> &&) noexcept(false) = default;

    /***************************************************************************/
    /**
		 * @brief Forwards a streamed value to a newly created streamer object
		 *
		 * This function will forward all arguments to a newly created object
		 * of type S. Note that the function returns the S object by value. It
		 * will not survive beyond the end of the stream-chain.
		 *
		 * @tparam T The type of the value being streamed
		 * @param t The value to be streamed into the new S object
		 * @return A freshly created S object holding the streamed value
		 */
    template <typename T>
    S operator<<(T const &t) {
        S s;
        s << t;
        return s;
    }

    /******************************************************************************/
    /**
	  * @brief Forwards a std::ostream manipulator (e.g. std::endl) to a new streamer
	  *
	  * Needed for ostringstream
	  *
	  * @param val A std::ostream manipulator function pointer
	  * @return A freshly created S object with the manipulator applied
	  */
    S operator<<(std::ostream &(*val)(std::ostream &)) {
        S s;
        s << val;
        return s;
    }

    /******************************************************************************/
    /**
	  * @brief Forwards a std::ios manipulator to a new streamer
	  *
	  * Needed for ostringstream
	  *
	  * @param val A std::ios manipulator function pointer
	  * @return A freshly created S object with the manipulator applied
	  */
    S operator<<(std::ios &(*val)(std::ios &)) {
        S s;
        s << val;
        return s;
    }

    /******************************************************************************/
    /**
	  * @brief Forwards a std::ios_base manipulator to a new streamer
	  *
	  *  Needed for ostringstream
	  *
	  * @param val A std::ios_base manipulator function pointer
	  * @return A freshly created S object with the manipulator applied
	  */
    S operator<<(std::ios_base &(*val)(std::ios_base &)) {
        S s;
        s << val;
        return s;
    }

    /***************************************************************************/
    /**
      * @brief Creates a streamer carrying a source-extension specifier
      *
      * This function instructs the logger architecture to emit additional
      * specifications for the data being logged. When writing to the console,
      * a corresponding text will be emitted. When writing to a file, the
      * modifier will be appended with an underscore to the filename.
      *
      * @param extension The source-extension specifier to attach to the streamer
      * @return A freshly created S object carrying the extension
      */
    S operator()(std::string const &extension) {
        S s(extension);
        return s;
    }

    /***************************************************************************/
    /**
      * @brief Creates a streamer that logs to a specific one-time log file
      *
      * This function instructs the logger architecture to emit data to the file
      * specified by the std::filesystem::path object
      *
      * @param p The path of the one-time log file to write to
      * @return A freshly created S object bound to the given log file
      */
    S operator()(std::filesystem::path p) {
        S s(p);
        return s;
    }

    /***************************************************************************/
    /**
		 * @brief Allows to set the default log target
		 *
		 * The default log target is used whenever no explicit log targets have been
		 * registered. Throws if a null pointer is supplied.
		 *
		 * @param gblt A shared pointer to the log target to be used as the default (must not be empty)
		 */
    void setDefaultLogTarget(std::shared_ptr<GBaseLogTarget> gblt) {
        // Serialise with concurrent log() / addLogTarget() etc.
        std::scoped_lock lk(logger_mutex_);

        if(gblt) {
            default_logger_ = gblt;
        }
        else {
            raiseException(
                "In GLogger::setDefaultLogTarget(): Error!"
                << '\n'
                << "Tried to register empty default logger" << '\n'
            );
        }
    }

    /***************************************************************************/
    /**
		 * @brief Adds a log target, such as console or file
		 *
		 * Throws if a null pointer is supplied.
		 *
		 * @param gblt A shared pointer to the log target to be added (must not be empty)
		 */
    void addLogTarget(std::shared_ptr<GBaseLogTarget> gblt) {
        // Serialise with concurrent log() / log_cnt_ readers.
        std::scoped_lock lk(logger_mutex_);

        if(gblt) {
            log_cnt_.push_back(gblt);
        }
        else {
            raiseException(
                "In GLogger::addLogTarget(): Error!" << '\n'
                                                     << "Tried to register empty logger"
                                                     << '\n'
            );
        }
    }

    /***************************************************************************/
    /**
		 * @brief Checks whether any log targets are present
		 *
		 * @return true if at least one log target has been registered, false otherwise
		 */
    bool hasLogTargets() const {
        // Read of log_cnt_ must be ordered against concurrent addLogTarget /
        // resetLogTargets writers. logger_mutex_ is mutable.
        std::scoped_lock lk(logger_mutex_);
        return not log_cnt_.empty();
    }

    /***************************************************************************/
    /**
		 * @brief Clears all registered local log-targets
		 */
    void resetLogTargets() {
        // Serialise with concurrent log() / addLogTarget().
        std::scoped_lock lk(logger_mutex_);
        log_cnt_.clear();
    }

    /***************************************************************************/
    /**
		 * @brief Allows S-objects to submit strings to the log targets
		 *
		 * Forwards the message to every registered log target, or to the default
		 * target if none are registered. Note that this function is thread-safe and
		 * thus may be called from different threads. Note that this function throws
		 * if neither any logging target nor a default target is available.
		 *
		 * @param message The message to be forwarded to the log targets
		 */
    void log(std::string const &message) const {
        // Make sure only one entity outputs data
        std::scoped_lock lk(logger_mutex_);

        if(not log_cnt_.empty()) {
            // Do the actual logging
            for(auto const &cit : log_cnt_) {
                cit->log(message);
            }
        }
        else {
            if(default_logger_) {
                default_logger_->log(message);
            }
            else {
                raiseException(
                    "In GLogger::log(): Error!" << '\n'
                                                << "No loggers found" << '\n'
                );
            }
        }
    }

    /***************************************************************************/
    /**
		 * @brief Allows S-objects to submit strings, together with a source identifier, to the log targets
		 *
		 * Forwards the message and its source identifier to every registered log
		 * target, or to the default target if none are registered. Note that this
		 * function is thread-safe and thus may be called from different threads.
		 * Note that this function throws if neither any logging target nor a default
		 * target is available.
		 *
		 * @param message The message to be forwarded to the log targets
		 * @param extension An identifier of the logging source forwarded alongside the message
		 */
    void logWithSource(std::string const &message, std::string const &extension) const {
        // Make sure only one entity outputs data
        std::scoped_lock lk(logger_mutex_);

        if(not log_cnt_.empty()) {
            // Do the actual logging
            for(auto cit : log_cnt_) { // std::shared_ptr max be copied
                cit->logWithSource(message, extension);
            }
        }
        else {
            if(default_logger_) {
                default_logger_->logWithSource(message, extension);
            }
            else {
                raiseException(
                    "In GLogger::logWithSource(): Error!" << '\n'
                                                          << "No loggers found" << '\n'
                );
            }
        }
    }

    /***************************************************************************/
    /**
		 * @brief Throws an exception from a global position
		 *
		 * This prevents exceptions thrown from within threads from getting lost. The
		 * mutex is released *before* the throw so that stack-unwinding exception
		 * handlers (which may re-enter the logger) do not deadlock against the lock
		 * we just held.
		 *
		 * @param error The error message carried by the thrown geneva_exception
		 */
    void throwException(std::string const &error) {
        // The `error` argument has already been built by the caller; we don't
        // touch any logger-protected state inside this function. The lock
        // exists purely to serialise with other terminate/throw paths if any
        // were ever added, so we take it briefly and release it before
        // throwing.
        {
            std::scoped_lock lk(logger_mutex_);
            // (no shared state to mutate here)
        }
        throw(geneva_exception(error));
    }

    /***************************************************************************/
    /**
		 * @brief Initiates the termination sequence
		 *
		 * Prints the error to std::cerr and calls std::terminate(). The mutex is
		 * released before std::terminate() runs so that any std::terminate_handler
		 * the user has installed sees a consistent global state (terminating while
		 * still holding a mutex leaves the lock owned by the now-terminating thread
		 * and is observable by some handlers).
		 *
		 * @param error The error message printed to std::cerr before terminating
		 */
    void terminateApplication(std::string const &error) {
        {
            std::scoped_lock lk(logger_mutex_);
            std::cerr << error;
        }
        std::terminate();
    }

    /***************************************************************************/
    /**
			 * @brief Performs a deliberate, clean program exit with a chosen return code
			 *
			 * Unlike terminateApplication() this does NOT std::terminate() (no core dump):
			 * it prints the message and calls std::exit(), which runs static destructors and
			 * atexit handlers. The mutex is released before std::exit() for the same reason
			 * as in terminateApplication().
			 *
			 * @param message The message printed to std::cerr before exiting
			 * @param return_code The process return code passed to std::exit()
			 */
    void exitApplication(std::string const &message, int return_code) {
        {
            std::scoped_lock lk(logger_mutex_);
            std::cerr << message << std::flush;
        }
        std::exit(return_code);
    }

    /***************************************************************************/
    /**
		 * @brief Output to stdout
		 *
		 * Writes the message to std::cout and flushes (the stream is buffered and may
		 * otherwise lose output on an abnormal exit). Thread-safe.
		 *
		 * @param message The message to be written to std::cout
		 */
    void toStdOut(std::string const &message) {
        // Make sure only one entity outputs data
        std::scoped_lock lk(logger_mutex_);

        // Flush: std::cout is buffered and may otherwise lose output on an
        // abnormal exit.
        std::cout << message << std::flush;
    }

    /***************************************************************************/
    /**
		 * @brief Output to stderr
		 *
		 * Writes the message to std::cerr. Thread-safe.
		 *
		 * @param message The message to be written to std::cerr
		 */
    void toStdErr(std::string const &message) {
        // Make sure only one entity outputs data
        std::scoped_lock lk(logger_mutex_);

        std::cerr << message;
    }

private:
    /***************************************************************************/

    std::vector<std::shared_ptr<GBaseLogTarget>> log_cnt_; ///< Contains the log targets
    mutable std::mutex logger_mutex_; ///< Needed for concurrent access to the log targets

    std::shared_ptr<GBaseLogTarget> default_logger_ =
        std::make_shared<GConsoleLogger>(); ///< The default log target
};

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * Objects of this class need to be added as the last element of a logging or
 * exception chain, possibly wrapped into a macro giving it information about
 * the file and lines from which it has been called.
 */
class GManipulator { // NOLINT(cppcoreguidelines-special-member-functions)
public:
    /**
     * @brief A constructor that stores the logging type only
     *
     * @param lt The type of logging event this manipulator triggers
     */
    explicit GManipulator(logType lt);
    /**
     * @brief A constructor that stores both accompanying information and the logging type
     *
     * @param accomp_info Accompanying information (e.g. a call-site location string)
     * @param lt The type of logging event this manipulator triggers
     */
    GManipulator(std::string const &accomp_info, logType lt);
    /**
     * @brief A constructor that additionally stores a process return code (for logType::EXIT)
     *
     * @param accomp_info Accompanying information (e.g. a call-site location string)
     * @param lt The type of logging event this manipulator triggers
     * @param return_code The process return code to be used by logType::EXIT
     */
    GManipulator(std::string const &accomp_info, logType lt, int return_code);

    /*************************************************************************/
    // Deleted and defaulted constructors, destructor and assignment operators.
    // Rule of five ...

    GManipulator() = delete; ///< Intentionally deleted -- enforce specific log types
    GManipulator(GManipulator const &) = default;
    GManipulator(GManipulator &&) noexcept = default;

    GManipulator &operator=(GManipulator const &) = default;
    GManipulator &operator=(GManipulator &&) = default;

    /*************************************************************************/

    /**
     * @brief Retrieves the stored logging type
     *
     * @return The logging type stored in this manipulator
     */
    logType getLogType() const;
    /**
     * @brief Retrieves stored accompanying information (if any)
     *
     * @return The accompanying information string (empty if none was stored)
     */
    std::string getAccompInfo() const;
    /**
     * @brief Checks whether any accompanying information is available
     *
     * @return true if accompanying information was stored, false otherwise
     */
    bool hasAccompInfo() const;
    /**
     * @brief Retrieves the stored process return code (meaningful for logType::EXIT)
     *
     * @return The stored process return code
     */
    int getReturnCode() const;

private:
    std::string accomp_info_; ///< Holds accompanying information
    logType log_type_; ///< Holds the type of logging event used for instantiating the manipulator
    int return_code_ = 0; ///< Process return code, used by logType::EXIT
};

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * Every entity in Geneva should be able to throw exceptions, regardless of whether
 * this happens from within a thread a in the context of serial execution. The output
 * should go to different log targets defined by the user, such as stdout or a file
 * (or possibly both). Emitting as much information as possible should be encouraged.
 * Hence adding information to the exception handler should be as easy as adding
 * data to a stream.
 */
class GLogStreamer {
public:
    /**
     * @brief A constructor that adds an extension string to the output
     *
     * @param extension A source-identifier string attached to the streamed output
     */
    explicit GLogStreamer(std::string const &extension);

    /**
     * @brief A constructor that logs data to a file specified by a std::filesystem::path object
     *
     * @param log_file The path of the one-time log file this streamer writes to
     */
    explicit GLogStreamer(std::filesystem::path log_file);

    /*************************************************************************/
    // Deleted and defaulted constructors, destructor and assignment operators.
    // Rule of five ...

    GLogStreamer() = default;
    GLogStreamer(GLogStreamer const &) = delete;
    GLogStreamer(GLogStreamer &&) = default;

    /** @brief A standard destructor */
    virtual ~GLogStreamer() = default;

    GLogStreamer &operator=(GLogStreamer const &) = delete;
    GLogStreamer &operator=(GLogStreamer &&) = default;

    /*************************************************************************/

    /**
     * @brief Streams a std::ostream manipulator (e.g. std::endl) into the streamer
     *
     * Needed for std::ostringstream
     *
     * @param val A std::ostream manipulator function pointer
     * @return A reference to this streamer, to allow chaining
     */
    GLogStreamer &operator<<(std::ostream &(*val)(std::ostream &));
    /**
     * @brief Streams a std::ios manipulator into the streamer
     *
     * Needed for std::ostringstream
     *
     * @param val A std::ios manipulator function pointer
     * @return A reference to this streamer, to allow chaining
     */
    GLogStreamer &operator<<(std::ios &(*val)(std::ios &));
    /**
     * @brief Streams a std::ios_base manipulator into the streamer
     *
     * Needed for std::ostringstream
     *
     * @param val A std::ios_base manipulator function pointer
     * @return A reference to this streamer, to allow chaining
     */
    GLogStreamer &operator<<(std::ios_base &(*val)(std::ios_base &));

    /**
     * @brief A GManipulator object triggers the actual logging procedure
     *
     * Intended to be the last element of a streaming chain; therefore it returns void.
     *
     * @param gm The manipulator whose log type dictates how the accumulated content is processed
     */
    void operator<<(GManipulator const &gm);

    /**
     * @brief Returns the content of the stream
     *
     * @return The accumulated streamed content as a string
     */
    std::string content() const;
    /** @brief Resets the stream content */
    void reset();

    /**
     * @brief Checks whether an extension string has been registered
     *
     * @return true if a non-empty source-extension string was registered, false otherwise
     */
    bool hasExtension() const;
    /**
     * @brief The content of the extension_ string
     *
     * @return The registered source-extension string (empty if none)
     */
    std::string getExtension() const;
    /**
     * @brief Checks whether a log file name has been registered
     *
     * @return true if a one-time log file path was registered, false otherwise
     */
    bool hasOneTimeLogFile() const;
    /**
     * @brief The name of the manually specified file
     *
     * @return The registered one-time log file path (empty if none)
     */
    std::filesystem::path getOneTimeLogFile() const;

    /****************************************************************************/
    /**
	  * @brief Output of all standard values and types with a predefined operator<<
	  *
	  * @tparam T The type of the value being streamed
	  * @param val The value to be appended to the internal stream
	  * @return A reference to this streamer, to allow chaining
	  */
    template <typename T>
    GLogStreamer &operator<<(T const &val) {
        oss_ << val;
        return *this;
    }

    /****************************************************************************/

private:
    /**
	  * Retrieve a string representing the current time and date. Note that
	  * this function is duplicated from a function in GCommonHelperFunctions.hpp
	  * in order to break circular header inclusion.
	  *
	  * @return A string representing the current time and date
	  */
    static std::string currentTimeAsString() {
        std::ostringstream oss; // NOLINT(cppcoreguidelines-init-variables)
        std::time_t now = std::chrono::system_clock::to_time_t(std::chrono::system_clock::now());
        struct tm time_info{};

#if defined(_MSC_VER) && (_MSC_VER >= 1020)
        localtime_s(&time_info, &now);
#else // We assume a POSIX-compliant platform
        localtime_r(&now, &time_info);
#endif

        oss << std::put_time(&time_info, "%c");
        return oss.str();
    }

    std::ostringstream oss_;         ///< Holds the actual streamed data
    std::string extension_;          ///< Additional information about the logging source
    std::filesystem::path log_file_; ///< The name of a manually specified log file
};

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/

/******************************************************************************/
/**
 * The logger is written to from arbitrary threads and even during static
 * destruction (e.g. worker threads still shutting down). Opt it into
 * never-destroy semantics so its instance outlives every other static and is
 * reclaimed only by the OS at process exit — this removes the static-destruction
 * use-after-free hazard structurally.
 */
template <>
struct gsingleton_never_destroy<GLogger<GLogStreamer>> : std::true_type {};

/******************************************************************************/

} /* namespace Gem::Common */

/******************************************************************************/
/**
* We currently require the global GLogStreamer object to be a singleton
*/
using log_singleton = Gem::Common::GSingletonT<Gem::Common::GLogger<Gem::Common::GLogStreamer>>;
#define glogger_ptr log_singleton::instance()
#define glogger     (*(log_singleton::instance()))

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
// Some related defines

namespace Gem::Common {
/**
 * @brief Returns a string describing the call site
 *
 * Returns an "in file <file> near line <line> (<function>)" string describing the
 * call site via C++20 std::source_location -- the function name is now included.
 * Used directly by the GEXCEPTION / GTERMINATION / GWARNING / GSTDERR manipulators.
 *
 * @param loc The source location to describe (defaults to the caller's location)
 * @return A human-readable string naming the file, line and function of the call site
 */
[[nodiscard]] inline std::string locationString(
    std::source_location const &loc = std::source_location::current()
) {
    return std::string("in file ") + loc.file_name() + std::string(" near line ") +
           std::to_string(loc.line()) + " (" + loc.function_name() + ")";
}
} // namespace Gem::Common

#define GEXCEPTION   Gem::Common::GManipulator(Gem::Common::locationString(), Gem::Common::logType::EXCEPTION)
#define GTERMINATION Gem::Common::GManipulator(Gem::Common::locationString(), Gem::Common::logType::TERMINATION)
#define GWARNING     Gem::Common::GManipulator(Gem::Common::locationString(), Gem::Common::logType::WARNING)
#define GLOGGING     Gem::Common::GManipulator(Gem::Common::logType::LOGGING)
#define GFILE        Gem::Common::GManipulator(Gem::Common::logType::FILE)
// Logs the streamed message and then exits the process CLEANLY with the given return code
// (std::exit, no core dump) -- the graceful counterpart to GTERMINATION, e.g. for command-line
// errors or other deliberate early exits.
#define LOGEXIT(returncode) Gem::Common::GManipulator(Gem::Common::locationString(), Gem::Common::logType::EXIT, (returncode))
#define GSTDOUT      Gem::Common::GManipulator(Gem::Common::logType::STDOUT)
#define GSTDERR      Gem::Common::GManipulator(Gem::Common::locationString(), Gem::Common::logType::STDERR)

/******************************************************************************/
