/********************************************************************************
 *
 * This file is part of the Geneva library collection. The following license
 * applies to this file:
 *
 * ------------------------------------------------------------------------------
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ------------------------------------------------------------------------------
 *
 * Note that other files in the Geneva library collection may use a different
 * license. Please see the licensing information in each file.
 *
 ********************************************************************************
 *
 * See the NOTICE file in the top-level directory of the Geneva library
 * collection for a list of contributors and copyright information.
 *
 ********************************************************************************/

#pragma once

// Global checks, defines and includes needed for all of Geneva
#include "common/GGlobalDefines.hpp"

// Standard headers go here

// Boost headers go here
#include <boost/serialization/base_object.hpp>
#include <boost/serialization/nvp.hpp>
#include <boost/serialization/shared_ptr.hpp>
#include <boost/serialization/split_member.hpp>
#include <boost/serialization/tracking.hpp>
#include <boost/serialization/utility.hpp>
#include <boost/serialization/vector.hpp>

// Geneva headers go here
#include "common/GBoilerplateT.hpp"
#include "common/GCommonInterfaceT.hpp"

namespace Gem::Common {

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * @brief Base of a hierarchy of serializable function objects.
 *
 * These function objects can be registered with serializable objects and thus
 * modify their behaviour. Being serializable themselves, they can travel over
 * the network alongside the objects they operate on. Derived classes implement
 * the actual behaviour by overriding process_().
 *
 * @tparam processable_type The type of object the function object operates on
 */
template <typename processable_type>
class GSerializableFunctionObjectT
  : public Gem::Common::GBoilerplateBaseT<
        GSerializableFunctionObjectT<processable_type>,
        GCommonInterfaceT<GSerializableFunctionObjectT<processable_type>>> {
    ///////////////////////////////////////////////////////////////////////
    // name_() / load_() / compare_() and serialize() are generated by the GBoilerplateBaseT mixin from
    // localMembers_() + class_name; this is a stateless abstract root (clone_ / process_ stay pure).
    friend class boost::serialization::access;
    friend struct Gem::Common::GBoilerplateAccess;

    template <typename Self>
    auto localMembers_(this Self &) { return std::make_tuple(); }

    ///////////////////////////////////////////////////////////////////////

public:
    /** @brief The class name, consumed by the GBoilerplateBaseT-generated name_() and compare token. */
    static constexpr std::string_view class_name = "GSerializableFunctionObjectT<processable_type>";
    /***************************************************************************/
    // Defaulted functions

    GSerializableFunctionObjectT() = default;
    GSerializableFunctionObjectT(GSerializableFunctionObjectT<processable_type> const &cp) =
        default;
    GSerializableFunctionObjectT(GSerializableFunctionObjectT<processable_type> &&cp) = default;
    ~GSerializableFunctionObjectT() override = default;

    GSerializableFunctionObjectT<processable_type> &
    operator=(GSerializableFunctionObjectT<processable_type> const &) = default;
    GSerializableFunctionObjectT<processable_type> &
    operator=(GSerializableFunctionObjectT<processable_type> &&) = default;

    /***************************************************************************/
    /**
	  * @brief Function call operator; applies this function object to p.
	  *
	  * @param p The object to be processed (modified in place by process_())
	  * @return The boolean result returned by the concrete process_() override
	  */
    bool operator()(processable_type &p) {
        return this->process_(p);
    }

protected:
    /***************************************************************************/
    /**
     * @brief Overload this function to make this class operational.
     * @param p The object to be processed (typically modified in place)
     * @return A boolean status defined by the concrete implementation
     */
    virtual bool process_(processable_type &p) = 0;

    /**
     * @brief Applies modifications to this object. This is needed for testing purposes.
     * @return true if a modification was made, false otherwise (here: always false)
     */
    bool modify_GUnitTests_() override {
        return false;
    };
    /** @brief Performs self tests that are expected to succeed. This is needed for testing purposes */
    void specificTestsNoFailureExpected_GUnitTests_() override { /* nothing */ };
    /** @brief Performs self tests that are expected to fail. This is needed for testing purposes */
    void specificTestsFailuresExpected_GUnitTests_() override { /* nothing */ };

private:
    /***************************************************************************/
    /** @brief Creates a deep clone of this object */
    [[nodiscard]] GSerializableFunctionObjectT<processable_type> *clone_() const override = 0;
};

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/

} /* namespace Gem::Common */

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
/**
 * @brief The content of the BOOST_SERIALIZATION_ASSUME_ABSTRACT(T) macro. Needed for Boost.Serialization
 */
namespace boost::serialization {
template <typename processable_type>
struct is_abstract<Gem::Common::GSerializableFunctionObjectT<processable_type>>
  : public std::true_type {};
template <typename processable_type>
struct is_abstract<const Gem::Common::GSerializableFunctionObjectT<processable_type>>
  : public std::true_type {};
} /* namespace boost::serialization */

/******************************************************************************/
////////////////////////////////////////////////////////////////////////////////
/******************************************************************************/
