/*
 * This file is part of the Geneva library collection.
 *
 * See the NOTICE file in the top-level directory of the Geneva library
 * collection for a list of contributors and copyright information.
 *
 * The following license applies to the code IN THIS FILE:
 *
 * ***************************************************************************
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * ***************************************************************************
 *
 * NOTE THAT THE BOOST-LICENSE DOES NOT APPLY TO ANY OTHER FILES OF THE
 * GENEVA LIBRARY, UNLESS THIS IS EXPLICITLY STATED IN THE CORRESPONDING FILE!
 */

#pragma once

// Global checks, defines and includes needed for all of Geneva
#include "common/GGlobalDefines.hpp"

// Standard headers go here
#include <iostream>
#include <ranges>
#include <sstream>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <vector>

// Gemfony headers go here

namespace Gem::Common {

/******************************************************************************/
// This set of functions allows to output tuples of any size, starting at 0.

/******************************************************************************/
/**
 * @brief Renders any stream-insertable type to a string via operator<<.
 *
 * Declared ahead of the tuple overload so that the tuple renderer's per-element
 * recursion resolves to it by ordinary unqualified lookup.
 *
 * @tparam T The type to be rendered (must support operator<< into an std::ostream)
 * @param t The value to be converted to a string
 * @return The string produced by streaming @p t through an std::ostringstream
 */
template <typename T>
std::string g_to_string(const T &t) {
    std::ostringstream oss; // NOLINT(cppcoreguidelines-init-variables)
    oss << t;
    return oss.str();
}

/******************************************************************************/
/**
 * @brief Renders a std::tuple to a parenthesised, comma-separated string.
 *
 * Each element is rendered via g_to_string (so a nested tuple renders parenthesised and any
 * other type goes through operator<<), and the rendered elements are joined with ", " between
 * them via std::views::join_with — no "separator unless last element" special case. Empty
 * tuples render as "()".
 *
 * @tparam args The element types of the tuple
 * @param t The tuple to be converted to a string
 * @return The tuple rendered as "(e0, e1, ...)", or "()" for an empty tuple
 */
template <class... args>
std::string g_to_string(const std::tuple<args...> &t) {
    std::vector<std::string> parts;
    parts.reserve(sizeof...(args));
    std::apply(
        [&parts](const auto &...elems) {
            (parts.push_back(g_to_string(elems)), ...);
        },
        t
    );
    return "(" +
           (parts | std::views::join_with(std::string_view(", ")) | std::ranges::to<std::string>()) +
           ")";
}

/******************************************************************************/
/**
 * @brief Stream insertion operator for std::tuple.
 *
 * @tparam args The element types of the tuple
 * @param o The output stream to write to
 * @param t The tuple to be streamed (rendered via g_to_string)
 * @return A reference to the output stream @p o, to allow chaining
 */
template <class... args>
std::ostream &operator<<(std::ostream &o, const std::tuple<args...> &t) {
    o << g_to_string(t);
    return o;
}

/******************************************************************************/

} /* namespace Gem::Common */
